### ISSUE TITLE
Construct octetString outside of the library

### ISSUE THREAD

**Issue by shyimo** [tngan/samlify#110]
In order to parse logout request, we need to parse in the express req the octetString and we need to generate it from the query params.
It is not necessary since the parse logout request function receive the query params and it will be much better if the function will generate it by her self.

**Comment by tngan** [comment]
@shyimo I am still looking for a good way to do this, v1 does the generation but v2 doesn't because we want to abstract the request interface, making samlify not bundled with express.js but also with other frameworks, say koa ... etc.

**Comment by tngan** [comment]
This will be revised later on.
