### ISSUE TITLE
Validates issuer when IDP initiated slo

### ISSUE THREAD

**Issue by shyimo** [tngan/samlify#111]
Is the any validation for the issuer in parseLogoutRequest when idp initiated the slo?
it seems not and it will be great if it will be.

**Comment by tngan** [comment]
@shyimo It is not included in this library now, the library only does the signature validation, decryption (for login response), and extract information from response, the others are left to developer.

Indeed I would like to put more common validations, saying issuer, and time conditions. Pull requests are welcome though.

**Comment by tngan** [comment]
So I will try to make it as a set of validator adapters and allow them to be explicitly injected in the configurations in the entity constructor as well.

For examples:

```js
const validator = samlify.validator;
const sp = samlify.serviceProvider({
  validators: [
    validator.issuer,
    validator.validTime,
    // ... etc
  ]
});
```

instead of leaving those to developers.

**Comment by tngan** [comment]
Basic validations are completed for logout and login response, will continue to add more later on.
