### ISSUE TITLE
How to handle errors for slo flow initiated by idp.

### ISSUE THREAD

**Issue by shyimo** [tngan/samlify#112]
When error occurs during the parsing of the logout request, how should we handle it? did the response to the client should also be redirect or we need to return error status?

**Comment by tngan** [comment]
@shyimo There is a field called StatusCode in response.

**Comment by ugolas** [comment]
@tngan in the case of a IDP initiated SLO, where the signature validation fails, what should be the response? continue the redirect to the IDP with an error in the status code of the SAMLResponse?

**Comment by tngan** [comment]
Signature should be the top level verification. Imagine if you don’t trust the entity, all responses and requests from untrusted source should be rejected, I do think it should send back the response to identity provider to complete the operation with status code

urn:oasis:names:tc:SAML:2.0:status:Requester

indicating failed request.

**Comment by ugolas** [comment]
ok sounds good.. Is there a way to use the samlify lib to construct such a response?

**Comment by tngan** [comment]
@ugolas What we can do right now is to use customize response template, and replace those tag during runtime, but it's not intuitive to do that, I am working on the examples now for both idp and sp. Maybe it's a good time to revise the flow of logout.

**Comment by tngan** [comment]
Already put it in pending list. Checkout #90.
