### ISSUE TITLE
Tweak to libSaml to support Encrypt-then-Sign signature Validation

### ISSUE THREAD

**Issue by haoleman** [tngan/samlify#113]
I support IDP Initiated SSO with IDP's that use both encrypt-then-sign and sign-then-encrypt .: I need to be able to support both. When "selecting" the x509 Cert(s) to verify in line https://github.com/tngan/samlify/blob/master/src/libsaml.ts#L475 from the Signature, the xpath select "queries" the entire SAML Response document and not just the signature Node. To fix this. add a "." (dot), so xpath.select will not search the entire document. Without the "." (dot), the [0].firstChild is the x509 cert used for encryption.

Fix (just adding the dot so xpath will not look in root):
`var x509Certificate = xpath_1.select(".//*[local-name(.)='X509Certificate']", s)[0].firstChild.data;`

**Comment by haoleman** [comment]
test sample:

`var xpath = require('xpath'),
    dom = require('xmldom').DOMParser

var xml = `<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_8e8dc5f69a98cc4c1ff3427e5ce34606fd672f91e6" Version="2.0" IssueInstant="2017-08-08T09:29:22.061Z" Destination="http://localhost/api" InResponseTo="nothing"><saml:Issuer>http://idp.example.com/metadata.php</saml:Issuer><samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></samlp:Status><saml:EncryptedAssertion><xenc:EncryptedData Type="http://www.w3.org/2001/04/xmlenc#Element" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"><xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/><KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#"><e:EncryptedKey xmlns:e="http://www.w3.org/2001/04/xmlenc#"><e:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-1_5"><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/></e:EncryptionMethod><KeyInfo><X509Data><X509Certificate>1111111111111111111111111111111111111111111111111111111111111111111</X509Certificate></X509Data></KeyInfo><e:CipherData><e:CipherValue>3333333333333333</e:CipherValue></e:CipherData></e:EncryptedKey></KeyInfo><xenc:CipherData><xenc:CipherValue>2222222222222222</xenc:CipherValue></xenc:CipherData></xenc:EncryptedData></saml:EncryptedAssertion><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><ds:Reference URI="#_8e8dc5f69a98cc4c1ff3427e5ce34606fd672f91e6"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><ds:DigestValue>44</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>656565656565</ds:SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509Certificate>999999999999999999999999999999999999999999999999999999999999999</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature></samlp:Response>`
var doc = new dom().parseFromString(xml);

var selection = xpath.select("//*[local-name(.)='Signature']", doc);
console.log(`selection:\n ${selection}`);

selection.forEach(function (s) {
    console.error(`===\n==\n S is:\n${s}`);
    var allCerts = xpath.select("//*[local-name(.)='X509Certificate']", s); //need the dot
    console.log(`\nAll Certs: \n${allCerts[0]}`);
    var x509Certificate = xpath.select("//*[local-name(.)='X509Certificate']", s)[0].firstChild.data; //need the dot or will search whole doc
    console.log(`\nx509 cert = \n${x509Certificate}`);

    //using . to not search whole doc
    let allCerts2 = xpath.select(".//*[local-name(.)='X509Certificate']", s); //need the dot
    console.log(`\nAll Certs2: \n ${allCerts2}`);
    let x509Certificate2 = xpath.select(".//*[local-name(.)='X509Certificate']", s)[0].firstChild.data; //need the dot or will search whole doc
    console.log(`\nx509 cert2 = \n${x509Certificate2}`);
    if (x509Certificate === x509Certificate2) {
        console.log('same certs')
    } else {
        console.log('NOT the same certs')
    }
});`

**Comment by haoleman** [comment]
upload test/sample code to show
[xpath_test.js.txt](https://github.com/tngan/samlify/files/1207824/xpath_test.js.txt)

**Comment by tngan** [comment]
@haoleman Nice catch.

**Comment by haoleman** [comment]
i figured u could do a quick fix, rather than me pushing an MR. If you want, I can put one together.

**Comment by haoleman** [comment]
yeah. need to move the signature in the SAMLResponse after the encryptedAssertion...i think

**Comment by haoleman** [comment]
I have fix and test case. Used signatureConfig, to change order of nodes. I'll push up PR tonight.

**Comment by tngan** [comment]
Will be included in the next release, which is v2.2.

**Comment by haoleman** [comment]
when u bumping to 2.2?

**Comment by tngan** [comment]
Friday 15:30 UTC

I need to document something else.

**Comment by tngan** [comment]
@haoleman v2.2.0 is already bumped.
