### ISSUE TITLE
Unable to disable signature verification 

### ISSUE THREAD

**Issue by hotienvu** [tngan/samlify#116]
Hi,
I want to disable the certificate verification of SAML response for the time being. The documentation suggests to set WantAssertionsSigned="false" in SP metadata. However it's not being honored and I'm getting uncaught exception in verifySignature() method. 
Looking at the source it seems like the signature is still checked and it requires a < ds:X509Certificate> tag to be included in the response which is not available. 
https://github.com/tngan/samlify/blob/f1d14a69ebf00d62281c70e82edc0a8923f19e6c/src/entity-sp.ts#L111

**Comment by tngan** [comment]
@hotienvu Let me update the documentation later on. We are sorry to not support unsigned response since SAML response must have signature, can be in assertion or entire message, or both.

I will check if the X509Certificate is optional in signature section later on.

**Comment by hotienvu** [comment]
No problem, actually the Idp admin just made change to include the X509Certificate in the response so it's working ok with the verification now. Just wonder if it is better to honor the WantAssertionsSigned by passing 
`this.entityMeta.isWantAssertionsSigned()` instead of `true`

**Comment by tngan** [comment]
Long time ago, it is. However we changed to `true` because response must have signature according to SAML specification.

If `WantAssertionsSigned` is set to false, we assume idp is using message signature implicitly.

**Comment by hotienvu** [comment]
Thanks for clarification (y)
