### ISSUE TITLE
createLoginRequest expected to return redirect url string?

### ISSUE THREAD

**Issue by hammadzz** [tngan/samlify#120]
I think there is a mistake in the examples that handle the redirect by expecting createLoginRequest to return a url string:
```js
router.get('/spinitsso-redirect', (req, res) => {
  res.redirect(sp.createLoginRequest(idp, 'redirect');
});
```

Is this the right fix:
```js
router.get('/saml/sso-redirect', (req, res) => {
  const url = sp.createLoginRequest(idp, 'redirect').context
  return res.redirect(url)
})
```

**Comment by tngan** [comment]
@hammadzz Yes, the document seems not updated.

**Comment by Dhinendran** [comment]
@tngan i getting error from  const url = sp.createLoginRequest(idp, 'redirect').context

ERR_INVALID_ARG_TYPE
