### ISSUE TITLE
Handling SAMLResponses with unknown encryption status

### ISSUE THREAD

**Issue by ahwitz** [tngan/samlify#124]
Don't know if this is desired, but I'm dealing with a multi-IdP situation wherein it'd be easier to not provide an `isAssertionEncrypted` value when creating the IdentityProvider object and let it be determined automatically. If I understand correctly, that should be as simple as an XPath call at https://github.com/tngan/samlify/blob/master/src/entity.ts#L246 with some additional error handling, but I'm not sure this functionality is either desired or as foolproof as I hope it is.

If this isn't desired, I do have ways to work around this. Wanted to submit an issue to see if it'd be straightforward before doing the work for a PR.

**Comment by tngan** [comment]
@ahwitz Yes, the construction of identity provider and service provider can be done during run time.

**Comment by tngan** [comment]
@ahwitz Since no update on this question thread for almost 3 weeks, I will close it first. Feel free to reopen it if necessary.
