### ISSUE TITLE
Error incorrect signature on SAML Assert

### ISSUE THREAD

**Issue by hammadzz** [tngan/samlify#125]
I am getting an "incorrect signature" error on SAML POST response hitting the assert endpoint. I traced it down in samlify source to this code in entity.ts:

``` js
// verify the signatures (for both assertion/message)
        if (!libsaml.verifySignature(res, {
          cert: opts.from.entityMeta,
          signatureAlgorithm: opts.from.entitySetting.requestSignatureAlgorithm,
        })) {
          throw new Error('incorrect signature');
        }
```

But when I check my response using this service: https://www.samltool.com/validate_response.php everything seems to validate fine. How can I debug this further?

**Comment by tngan** [comment]
@hammadzz There are some possibilities that the signature might get errors when you use samlify.

1. Importing a wrong key when construct the entity
1. Mismatch of signature algorithm
1. Inclusive namespace [xml-crypto#94](https://github.com/yaronn/xml-crypto/issues/94)

You are using the latest version of samlify, right ?

**Comment by hammadzz** [comment]
@tngan 

1. Do you mean the idP cert imported wrong? Would this be in the xml metadata or sp_setting?

2. Signature Algorithm is listed the same in idp_setting as is found in the saml response: <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />

3. Doesn't seem to be my issue as the saml response has no child in CanonicalizationMethod: <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />

Any tips on what can be done to debug this further. Is samltool.com wrong or the library has a bug?

**Comment by tngan** [comment]
@hammadzz 

Another possibility is the order of signature, in case if you have encryption in saml assertion as well, default is `sign-then-encrypt`, but most likely it would be `encrypt-then-sign`.

```js
const idp = saml.identityProvider({
  messageSigningOrders: 'encrypt-then-sign'
});
```

`Any tips on what can be done to debug this further. Is samltool.com wrong or the library has a bug?`

samltool.com is good enough. I cannot tell whether samlify has bug or configuration mistake at this stage until I know the exact problem, would you like to set up a sample repository then we can take a look deeply. Please send an email to `passify.io@gmail.com` if something you don't want to expose here.

**Comment by hammadzz** [comment]
@tngan I traced down the issue to being a mismatch on the digest value. The calculated digest of the canonized assertion does not match the value in the signature. This part of the code is in the xml-crypto library.

In the verifySignature method when using xml-crypto and calling checkSignature you can get the validationErrors. This helped me figure out the issue is with the digest value mismatch. 

```
var res = sig.checkSignature(xml)
if (!res) console.log(sig.validationErrors)
```

Still trying to figure out if it is an issue with how the assertion is canonized.

**Comment by tngan** [comment]
@hammadzz Have you tried out the messageSigningOrder option ?

**Comment by hammadzz** [comment]
@tngan Yes I tried setting it to encrypt-then-sign even though it is unencrypted

**Comment by tngan** [comment]
@hammadzz Would you like to create a sample repository, then we can go deeper on this issue ?

**Comment by tngan** [comment]
@hammadzz Due to inactivity for 3 weeks, and the email stated that it's possibly the known issue of handling canonicalization. I will close this issue first, and feel free to reopen if it's not fixed.
