### ISSUE TITLE
Checking signature required

### ISSUE THREAD

**Issue by AmineBena17** [tngan/samlify#128]
Hi, 

i'm using your library to implement the SSO in my project, but when i want to parse the login response i have some problems with the signature of my response, so i suggest if it's possible to not  force checking signature of the response because in the integration phase of a project it's not necessary. i tried to do a pull request in your library but i couldn't.

```js
 public parseLoginResponse(idp, binding, req: ESamlHttpRequest) {
    return this.genericParser({
      parserFormat: [{
        localName: 'StatusCode',
        attributes: ['Value'],
      }, {
        localName: 'Conditions',
        attributes: ['NotBefore', 'NotOnOrAfter'],
      }, 'Audience', 'Issuer', 'NameID', {
        localName: 'Signature',
        extractEntireBody: true,
      }, {
        localName: {
          tag: 'Attribute',
          key: 'Name',
        },
        valueTag: 'AttributeValue',
      }],
      from: idp,
      checkSignature: true, // make it false will be more userful
      supportBindings: ['post'],
      parserType: 'SAMLResponse',
      type: 'login',
    }, binding, req);
  }
```

Cordially.

**Comment by tngan** [comment]
@AmineBena17 It's recommended to do signature validation no matter in dev or production. It's because response must have signature according to SAML specification.

[This](https://github.com/tngan/samlify/issues/116) is another related issue.

**Comment by AmineBena17** [comment]
Hi.

I suggest if it's possible to make or variable and de can activate and desactivate when we need it. In my case i receive a non signed response from the IDO, and i put or false in the file .js to use it in my projet.


Thanks.

**Comment by tngan** [comment]
Previously we had a version using a variable to trigger the activation of signature validation, but it didn't follow the standard specification so we removed it. Please fork a new one and fit this in your use case, but we are not going to bring it back at this moment :)

Once you fork a new one, I can mention it in README.md as well and for those who are willing to disable the signature validation for whatever reason.

**Comment by AmineBena17** [comment]
Great ! thank you for your response.

**Comment by tngan** [comment]
I will close this issue first, please reopen it whenever it’s necessary.
