### ISSUE TITLE
libxml-xsd Dependency Introduces Breaking Change

### ISSUE THREAD

**Issue by phairoh** [tngan/samlify#129]
The v2.3.0 introduces a breaking change as a result of the addition of the `libxml-xsd` dependency. This library depends on `libxmljs-mt` which needs to be compiled and requires a number of additional dependencies (such as python) the lack of which will cause `npm install` to fail.

I suggest reverting and publishing a corrected version and republishing this version as a major release.

**Comment by tngan** [comment]
@phairoh Thanks for your report, which npm and node version are you using ?

**Comment by phairoh** [comment]
node: 8.6.0
npm: 5.3.0

**Comment by tngan** [comment]
@phairoh From the library level, it doesn't break the API, so I don't think we should upgrade the major version. I would rather like to do a `preinstall` script instead.

**Comment by cyberbobjr** [comment]
I confirm the breaking change, with many major bugs if we use PaaS environnement (like Bluemix)

**Comment by tngan** [comment]
@cyberbobjr Please provide more details about the major bugs in PaaS environment. Thank you so much.

**Comment by niswork** [comment]
I am sorry if this is not related to this particular issue, but I am receiving may "Warnings" while doing npm install. Here are these warnings... 

`
> libxmljs-mt@0.16.1 install /Users/phatanga/Documents/Visualization/TableauWebApp/node_modules/libxmljs-mt
> node-gyp rebuild

  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
../src/libxmljs.cc:69:17: warning: 'IsDead' is deprecated [-Wdeprecated-declarations]
    if (v8::V8::IsDead())
                ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8.h:6353:20: note: 'IsDead' has been explicitly marked deprecated here
  V8_INLINE static V8_DEPRECATED("Use isolate version", bool IsDead());
                   ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8config.h:336:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/xmljs/src/xml_attribute.o
../src/xml_attribute.cc:26:80: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    v8::Local<v8::Object> obj = Nan::New(constructor_template)->GetFunction()->NewInstance();
                                                                               ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8.h:3276:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8config.h:336:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/xml_attribute.cc:42:80: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    v8::Local<v8::Object> obj = Nan::New(constructor_template)->GetFunction()->NewInstance();
                                                                               ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8.h:3276:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8config.h:336:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
2 warnings generated.
  CXX(target) Release/obj.target/xmljs/src/xml_document.o
../src/xml_document.cc:206:80: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    v8::Local<v8::Object> obj = Nan::New(constructor_template)->GetFunction()->NewInstance();
                                                                               ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8.h:3276:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8config.h:336:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/xmljs/src/xml_element.o
../src/xml_element.cc:503:80: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    v8::Local<v8::Object> obj = Nan::New(constructor_template)->GetFunction()->NewInstance();
                                                                               ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8.h:3276:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8config.h:336:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/xmljs/src/xml_comment.o
../src/xml_comment.cc:90:80: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    v8::Local<v8::Object> obj = Nan::New(constructor_template)->GetFunction()->NewInstance();
                                                                               ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8.h:3276:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8config.h:336:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/xmljs/src/xml_namespace.o
../src/xml_namespace.cc:60:80: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    v8::Local<v8::Object> obj = Nan::New(constructor_template)->GetFunction()->NewInstance();
                                                                               ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8.h:3276:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8config.h:336:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/xmljs/src/xml_node.o
../src/xml_node.cc:79:55: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
      v8::Local<v8::Value> new_ns = define_namespace->NewInstance(argc, argv);
                                                      ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8.h:3271:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8config.h:336:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/xmljs/src/xml_sax_parser.o
  CXX(target) Release/obj.target/xmljs/src/xml_syntax_error.o
  CXX(target) Release/obj.target/xmljs/src/xml_text.o
../src/xml_text.cc:210:80: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    v8::Local<v8::Object> obj = Nan::New(constructor_template)->GetFunction()->NewInstance();
                                                                               ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8.h:3276:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8config.h:336:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/xmljs/src/xml_xpath_context.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/buf.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/catalog.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/chvalid.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/dict.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/encoding.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/entities.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/error.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/globals.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/hash.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/HTMLparser.o
../vendor/libxml/HTMLparser.c:4403:41: warning: missing field 'begin_pos' initializer [-Wmissing-field-initializers]
    htmlParserNodeInfo node_info = { 0, };
                                        ^
1 warning generated.
  CC(target) Release/obj.target/xmljs/vendor/libxml/HTMLtree.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/legacy.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/list.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/parser.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/parserInternals.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/pattern.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/relaxng.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/SAX2.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/SAX.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/tree.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/threads.o
../vendor/libxml/threads.c:444:9: warning: comparison of function 'pthread_mutex_lock' not equal to a null pointer is always true [-Wtautological-pointer-compare]
    if (pthread_mutex_lock != NULL)
        ^~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:444:9: note: prefix with the address-of operator to silence this warning
    if (pthread_mutex_lock != NULL)
        ^
        &
../vendor/libxml/threads.c:513:9: warning: comparison of function 'pthread_mutex_unlock' not equal to a null pointer is always true [-Wtautological-pointer-compare]
    if (pthread_mutex_unlock != NULL)
        ^~~~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:513:9: note: prefix with the address-of operator to silence this warning
    if (pthread_mutex_unlock != NULL)
        ^
        &
../vendor/libxml/threads.c:867:14: warning: comparison of function 'pthread_once' not equal to a null pointer is always true [-Wtautological-pointer-compare]
        if ((pthread_once != NULL) &&
             ^~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:867:14: note: prefix with the address-of operator to silence this warning
        if ((pthread_once != NULL) &&
             ^
             &
../vendor/libxml/threads.c:868:14: warning: comparison of function 'pthread_getspecific' not equal to a null pointer is always true [-Wtautological-pointer-compare]
            (pthread_getspecific != NULL) &&
             ^~~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:868:14: note: prefix with the address-of operator to silence this warning
            (pthread_getspecific != NULL) &&
             ^
             &
../vendor/libxml/threads.c:869:14: warning: comparison of function 'pthread_setspecific' not equal to a null pointer is always true [-Wtautological-pointer-compare]
            (pthread_setspecific != NULL) &&
             ^~~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:869:14: note: prefix with the address-of operator to silence this warning
            (pthread_setspecific != NULL) &&
             ^
             &
../vendor/libxml/threads.c:870:14: warning: comparison of function 'pthread_key_create' not equal to a null pointer is always true [-Wtautological-pointer-compare]
            (pthread_key_create != NULL) &&
             ^~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:870:14: note: prefix with the address-of operator to silence this warning
            (pthread_key_create != NULL) &&
             ^
             &
../vendor/libxml/threads.c:871:14: warning: comparison of function 'pthread_key_delete' not equal to a null pointer is always true [-Wtautological-pointer-compare]
            (pthread_key_delete != NULL) &&
             ^~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:871:14: note: prefix with the address-of operator to silence this warning
            (pthread_key_delete != NULL) &&
             ^
             &
../vendor/libxml/threads.c:872:14: warning: comparison of function 'pthread_mutex_init' not equal to a null pointer is always true [-Wtautological-pointer-compare]
            (pthread_mutex_init != NULL) &&
             ^~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:872:14: note: prefix with the address-of operator to silence this warning
            (pthread_mutex_init != NULL) &&
             ^
             &
../vendor/libxml/threads.c:873:14: warning: comparison of function 'pthread_mutex_destroy' not equal to a null pointer is always true [-Wtautological-pointer-compare]
            (pthread_mutex_destroy != NULL) &&
             ^~~~~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:873:14: note: prefix with the address-of operator to silence this warning
            (pthread_mutex_destroy != NULL) &&
             ^
             &
../vendor/libxml/threads.c:874:14: warning: comparison of function 'pthread_mutex_lock' not equal to a null pointer is always true [-Wtautological-pointer-compare]
            (pthread_mutex_lock != NULL) &&
             ^~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:874:14: note: prefix with the address-of operator to silence this warning
            (pthread_mutex_lock != NULL) &&
             ^
             &
../vendor/libxml/threads.c:875:14: warning: comparison of function 'pthread_mutex_unlock' not equal to a null pointer is always true [-Wtautological-pointer-compare]
            (pthread_mutex_unlock != NULL) &&
             ^~~~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:875:14: note: prefix with the address-of operator to silence this warning
            (pthread_mutex_unlock != NULL) &&
             ^
             &
../vendor/libxml/threads.c:876:14: warning: comparison of function 'pthread_cond_init' not equal to a null pointer is always true [-Wtautological-pointer-compare]
            (pthread_cond_init != NULL) &&
             ^~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:876:14: note: prefix with the address-of operator to silence this warning
            (pthread_cond_init != NULL) &&
             ^
             &
../vendor/libxml/threads.c:877:14: warning: comparison of function 'pthread_cond_destroy' not equal to a null pointer is always true [-Wtautological-pointer-compare]
            (pthread_cond_destroy != NULL) &&
             ^~~~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:877:14: note: prefix with the address-of operator to silence this warning
            (pthread_cond_destroy != NULL) &&
             ^
             &
../vendor/libxml/threads.c:878:14: warning: comparison of function 'pthread_cond_wait' not equal to a null pointer is always true [-Wtautological-pointer-compare]
            (pthread_cond_wait != NULL) &&
             ^~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:878:14: note: prefix with the address-of operator to silence this warning
            (pthread_cond_wait != NULL) &&
             ^
             &
../vendor/libxml/threads.c:879:14: warning: comparison of function 'pthread_equal' not equal to a null pointer is always true [-Wtautological-pointer-compare]
            (pthread_equal != NULL) &&
             ^~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:879:14: note: prefix with the address-of operator to silence this warning
            (pthread_equal != NULL) &&
             ^
             &
../vendor/libxml/threads.c:880:14: warning: comparison of function 'pthread_self' not equal to a null pointer is always true [-Wtautological-pointer-compare]
            (pthread_self != NULL) &&
             ^~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:880:14: note: prefix with the address-of operator to silence this warning
            (pthread_self != NULL) &&
             ^
             &
../vendor/libxml/threads.c:880:14: note: suffix with parentheses to turn this into a function call
            (pthread_self != NULL) &&
             ^
                         ()
../vendor/libxml/threads.c:881:14: warning: comparison of function 'pthread_cond_signal' not equal to a null pointer is always true [-Wtautological-pointer-compare]
            (pthread_cond_signal != NULL)) {
             ^~~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:881:14: note: prefix with the address-of operator to silence this warning
            (pthread_cond_signal != NULL)) {
             ^
             &
../vendor/libxml/threads.c:917:35: warning: comparison of function 'pthread_key_delete' not equal to a null pointer is always true [-Wtautological-pointer-compare]
    if ((libxml_is_threaded)  && (pthread_key_delete != NULL))
                                  ^~~~~~~~~~~~~~~~~~    ~~~~
../vendor/libxml/threads.c:917:35: note: prefix with the address-of operator to silence this warning
    if ((libxml_is_threaded)  && (pthread_key_delete != NULL))
                                  ^
                                  &
18 warnings generated.
  CC(target) Release/obj.target/xmljs/vendor/libxml/uri.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/valid.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xinclude.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xlink.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlIO.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlmemory.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlmodule.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlreader.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlregexp.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlsave.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlschemas.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlschemastypes.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlstring.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlunicode.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xmlwriter.o
  CC(target) Release/obj.target/xmljs/vendor/libxml/xpath.o
In file included from ../vendor/libxml/xpath.c:462:
../vendor/libxml/timsort.h:405:65: warning: comparison of integers of different signs: 'long long' and 'const size_t' (aka 'const unsigned long') [-Wsign-compare]
    if ((stack_curr == 2) && (stack[0].length + stack[1].length == size)) {
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~
In file included from ../vendor/libxml/xpath.c:476:
../vendor/libxml/trionan.c:194:1: warning: unused function 'trio_is_special_quantity' [-Wunused-function]
trio_is_special_quantity
^
../vendor/libxml/trionan.c:218:1: warning: unused function 'trio_is_negative' [-Wunused-function]
trio_is_negative
^
3 warnings generated.
  CC(target) Release/obj.target/xmljs/vendor/libxml/xpointer.o
  SOLINK(target) Release/xmljs.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]

> libxml-xsd@0.5.2 install /Users/phatanga/Documents/Visualization/TableauWebApp/node_modules/libxml-xsd
> node-gyp rebuild

  CXX(target) Release/obj.target/node-libxml-xsd/src/schema.o
../src/schema.cc:31:52: warning: 'NewInstance' is deprecated [-Wdeprecated-declarations]
    Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                   ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8.h:3276:3: note: 'NewInstance' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
  ^
/Users/phatanga/.node-gyp/6.11.4/include/node/v8config.h:336:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  CXX(target) Release/obj.target/node-libxml-xsd/src/node_libxml_xsd.o
../src/node_libxml_xsd.cc:1:9: warning: 'BUILDING_NODE_EXTENSION' macro redefined [-Wmacro-redefined]
#define BUILDING_NODE_EXTENSION
        ^
<command line>:8:9: note: previous definition is here
#define BUILDING_NODE_EXTENSION 1
        ^
1 warning generated.
  SOLINK_MODULE(target) Release/node-libxml-xsd.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]

> samlify@2.3.2 postinstall /Users/phatanga/Documents/Visualization/TableauWebApp/node_modules/samlify
> node postinstall

/Users/phatanga/Documents/Visualization/TableauWebApp
Not running from git clone, ignoring post install
`

**Comment by tngan** [comment]
The warning message are quite annoying, will have to investigate.

**Comment by tngan** [comment]
@niswork Which node version are you using ?

**Comment by niswork** [comment]
Hi @tngan I am on node v6.11.4 & npm 3.10.10.

**Comment by AlexeySafronov** [comment]
Hi! I confirm the breaking change too.  Only v2.2.0 can be installed.

Windows 10 Pro
node v8.9.0
npm 5.5.1
yarn 1.2.1

```
$ npm install samlify@2.3.0 --save
> libxmljs-mt@0.16.1 install D:\GitHub\ConrolPanel\web\services\sso.idp\node_modules\libxmljs-mt
> node-gyp rebuild

...
npm ERR! libxmljs-mt@0.16.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs-mt@0.16.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by tngan** [comment]
Some updates, I have discovered that the package.json of libxml-xsd is not updated, since according to their latest package.json, they are using libxmljs-mt@0.18 instead of 0.16.1. Please follow the issue I have reported [here](https://github.com/albanm/node-libxml-xsd/issues/25).

@AlexeySafronov Please take a look for this doc for window installation during the meantime.

https://github.com/albanm/node-libxml-xsd/blob/f9ff21e4bba489921235b47a5949e39398a0cb87/readme.hbs

**Comment by AlexeySafronov** [comment]
Thanks! It's helped me.

Can you add this note in Installation section for windows-developers?

> Node-package 'windows-build-tools' should be installed globally before installing samlify on Windows
```
npm install --global --production windows-build-tools
```

**Comment by tngan** [comment]
@AlexeySafronov I am thinking if I can do something in post-install hook.

**Comment by tkssharma** [comment]
i am having same issue 

```
In file included from ../vendor/libxml/xpath.c:462:
../vendor/libxml/timsort.h:405:65: warning: comparison of integers of different signs:
      'long long' and 'const size_t' (aka 'const unsigned long') [-Wsign-compare]
    if ((stack_curr == 2) && (stack[0].length + stack[1].length == size)) {
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~
In file included from ../vendor/libxml/xpath.c:476:
../vendor/libxml/trionan.c:194:1: warning: unused function 'trio_is_special_quantity'
      [-Wunused-function]
trio_is_special_quantity
^
../vendor/libxml/trionan.c:218:1: warning: unused function 'trio_is_negative'
      [-Wunused-function]
trio_is_negative
^
3 warnings generated.
  CC(target) Release/obj.target/xmljs/vendor/libxml/xpointer.o
  SOLINK(target) Release/xmljs.node

> libxml-xsd@0.5.2 install /Users/tarun.kumar/SSO SAML/IDP/node_modules/libxml-xsd
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/node-libxml-xsd/src/schema.o
clang: error: no such file or directory: 'SAML/IDP/node_modules/libxmljs-mt/src'
clang: error: no such file or directory: 'SAML/IDP/node_modules/libxmljs-mt/vendor/libxml/include'
clang: error: no such file or directory: 'SAML/IDP/node_modules/libxmljs-mt/vendor/libxml.conf/include'
make: *** [Release/obj.target/node-libxml-xsd/src/schema.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/tarun.kumar/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/Users/tarun.kumar/.nvm/versions/node/v8.0.0/bin/node" "/Users/tarun.kumar/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tarun.kumar/SSO SAML/IDP/node_modules/libxml-xsd
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxml-xsd@0.5.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxml-xsd@0.5.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging outputabove.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tarun.kumar/.npm/_logs/2018-03-26T07_37_35_380Z-debug.log
```

**Comment by nazarkulyk** [comment]
Having same issue on linux and macosx
`
> libxmljs-mt@0.16.1 install /usr/src/app/node_modules/libxmljs-mt
> node-gyp rebuild

make: Entering directory '/usr/src/app/node_modules/libxmljs-mt/build'
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
../src/libxmljs.cc: In function 'void libxmljs::adjustMem(ssize_t)':
../src/libxmljs.cc:69:9: error: 'IsDead' is not a member of 'v8::V8'
     if (v8::V8::IsDead())
         ^~
make: *** [xmljs.target.mk:159: Release/obj.target/xmljs/src/libxmljs.o] Error 1
make: Leaving directory '/usr/src/app/node_modules/libxmljs-mt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Linux 4.16.8
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/libxmljs-mt
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
`

**Comment by thaniyarasu** [comment]
npm install samlify

> libxmljs-mt@0.16.1 install /home/us1/github.com/mcguinness/demo/node_modules/libxmljs-mt
> node-gyp rebuild

make: Entering directory '/home/us1/github.com/mcguinness/demo/node_modules/libxmljs-mt/build'
  CXX(target) Release/obj.target/xmljs/src/libxmljs.o
../src/libxmljs.cc: In function ‘void libxmljs::adjustMem(ssize_t)’:
../src/libxmljs.cc:69:17: error: ‘IsDead’ is not a member of ‘v8::V8’
     if (v8::V8::IsDead())
                 ^~~~~~
xmljs.target.mk:159: recipe for target 'Release/obj.target/xmljs/src/libxmljs.o' failed
make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
make: Leaving directory '/home/us1/github.com/mcguinness/demo/node_modules/libxmljs-mt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/us1/.nodenv/versions/10.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.15.0-23-generic
gyp ERR! command "/home/us1/.nodenv/versions/10.5.0/bin/node" "/home/us1/.nodenv/versions/10.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/us1/github.com/mcguinness/demo/node_modules/libxmljs-mt
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/us1/github.com/mcguinness/demo/package.json'
npm WARN demo No description
npm WARN demo No repository field.
npm WARN demo No README data
npm WARN demo No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs-mt@0.16.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxmljs-mt@0.16.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/us1/.npm/_logs/2018-07-03T08_57_21_548Z-debug.log




ubuntu-18.04
node-10.5.0

**Comment by tngan** [comment]
I am currently evaluating and testing another library to do scheme validation.

**Comment by tngan** [comment]
I have updated samlify, using with new schema validator.

https://github.com/nikku/node-xsd-schema-validator

It is using Java runtime library to do the schema validation, and it should be more stable than the one we have chosen before. I haven't released the new version to npm repository yet, but if you want to try it out, you can try the latest code base in master branch first by modifying your `package.json`

```json
"samlify": "tngan/samlify"
```

**Comment by tngan** [comment]
@microadam Yes, this is the way we consider to get rid of those build issues across most of the platforms. However, I would consider the make this part out of the box in the near future, allowing to plug different schema validator with this library.

**Comment by tngan** [comment]
I will close this issue since we have changed to delegate the xml schema validation to JAVA runtime library. Please feel free to reopen it or create a new ticket once you encounter issue with the latest approach.

**Comment by turutosiya** [comment]
@tngan Thanks for your info. Which Java version did you tested with?
