### ISSUE TITLE
Documentation: "Use 3rd party IdP"

### ISSUE THREAD

**Issue by maitscha** [tngan/samlify#132]
The documentation states:

> Currently, we suggest developers to use other 3rd party IdP even though we provide the basic API for identity provider.

What is the reason for not suggesting to use this library for a SAML IdP?

**Comment by tngan** [comment]
@maitscha This module is experimental, for internal testing purpose. We will enhance this part, possibly becoming a commercial product called passify later on.

**Comment by maitscha** [comment]
Thanks for the info. There are already a lot of forks and developers using this lib. Is there a migration plan to passify, and will samlify be maintained later? I'm searching a node.js based SAML2 IdP ...

**Comment by tngan** [comment]
@maitscha No worries, samlify is still in active maintained. Passify is a product partially driven by samlify, it doesn’t affect the release cycle of samlify.

**Comment by yelexin** [comment]
Can I use this lib for a SAML idp? I want to become a SAML Identity Provider and I'm looking for some libs that implement the SAML lower level according to the specification. The document is not so clear about becoming an Idp.
> Currently, we suggest developers to use other 3rd party IdP even though we provide the basic API for identity provider.

Where is the basic API for idp? I can't find it.
Or, maybe I should use other libs to host an IdP and use this lib to talk with it.
Any reply. Thanks!

**Comment by tngan** [comment]
@yelexin I remembered some users use the older version to make an identity provider. In v1, we have an example of identity provider, you can use this as an example, be careful since the API has changed a bit.

https://github.com/tngan/samlify/tree/f2b6a2f8c36dc0ff887d0442c48cd0f2c0a4a778/examples/idp

In fact, the development of an open source identity federation is still in our roadmap.

**Comment by yelexin** [comment]
Thanks a lot. 😄 I'll check that.

**Comment by tngan** [comment]
@yelexin Feel free to open new ticket if you have any question.
