### ISSUE TITLE
Unknown xmlns being used on AuthnRequest

### ISSUE THREAD

**Issue by ergoithz** [tngan/samlify#133]
Non-defined namespace 'ds' is being used on signed AuthnRequest, which results on strictly invalid XML.

https://github.com/tngan/samlify/blob/6f4de03a70c7f79d5fb1765adb1c880d885f528b/src/libsaml.ts#L599

https://github.com/tngan/samlify/blob/6f4de03a70c7f79d5fb1765adb1c880d885f528b/src/libsaml.ts#L439

https://github.com/tngan/samlify/blob/6f4de03a70c7f79d5fb1765adb1c880d885f528b/src/libsaml.ts#L133

**Comment by tngan** [comment]
@ergoithz Yep, this part has to be enhanced after we introduce schema validation.

**Comment by ergoithz** [comment]
Meanwhile you could simply add `{prefix: 'ds'}` signatureConfig to `sig.computeSignature` calls in both
https://github.com/tngan/samlify/blob/6f4de03a70c7f79d5fb1765adb1c880d885f528b/src/libsaml.ts#L443
and
https://github.com/tngan/samlify/blob/6f4de03a70c7f79d5fb1765adb1c880d885f528b/src/libsaml.ts#L445 
as current SAML signed AuthnRequests are failling on most IdP due XML parsing errors.

**Comment by tngan** [comment]
@ergoithz Now there is no `ds:` prefix unless you add a prefix in `signatureConfig`.
