### ISSUE TITLE
configuration for alternative parameter for SAMLResponse

### ISSUE THREAD

**Issue by haoleman** [tngan/samlify#134]
Question really......

Is there a configuration option for setting the parameter name for  LoginResponse POST?  I have a request coming to my ACS, and the "saml response" parameter is not named SAMLResponse.  It would be handy to be able to override per IDP, if it does not exist.  Does the question make sense?

Thanks.

**Comment by tngan** [comment]
@haoleman You can use the `logoutResponseTemplate`.
