### ISSUE TITLE
Is samlify suppose to handle multiple KeyDescriptor certificates for IDPSSODescriptor?

### ISSUE THREAD

**Issue by gtothesquare** [tngan/samlify#135]
I'm testing samlify with multiple Identity providers and I ran intro problems with Azure AD when using there `FederationMetadata.xmll` (more info on Azure AD [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-saml-protocol-reference))

The metadata provided, contains multiple `KeyDescriptior` certificates as shown at the end of this post (I removed the actual certificate for security reasons). 

When Azure AD comes back to my server, i get the following error:

```
Error: certificate in document is not matched those specified in metadata
    at node_modules/samlify/build/src/libsaml.js:415:31
    at Array.forEach (<anonymous>)
    at Object.verifySignature (node_modules/samlify/build/src/libsaml.js:397:23)
    at ServiceProvider.<anonymous> (node_modules/samlify/build/src/entity.js:278:52)
    at step (node_modules/samlify/build/src/entity.js:40:23)
    at Object.next (node_modules/samlify/build/src/entity.js:21:53)
    at fulfilled (node_modules/samlify/build/src/entity.js:12:58)
    at <anonymous>

```

After debugging found that the issue is the `metadataCert` in [libsaml.ts](https://github.com/tngan/samlify/blob/master/src/libsaml.ts#L472) is nested array of certificates. However, from the `metadataCert.map`, seems that it is expected to be a flat array, since `normalizeCerString ` converts an element to string before removing spaces, newlines, etc. However, when the nested array is converted to String, it will merge the certificates into a single element with a comma in between. For example:

`['cert1', ['cert2', ['cert3', 'cert4']]]` becomes `['cert1', 'cert2,cert3,cert4']`

I tried applying a `flattenDeep`, but some tests failed (also shown at the end of the post), so I was wondering what are the expectations for a number of certs and nesting.

Example Metadaata

```
<?xml version="1.0" encoding="utf-8"?>
<EntityDescriptor ID="_68385e75-76f1-4308-b2d0-1a25b10fb410"
                  entityID="https://sts.windows.net/[id]/"
                  xmlns="urn:oasis:names:tc:SAML:2.0:metadata">
    <IDPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        <KeyDescriptor use="signing">
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <X509Data>
                    <X509Certificate>some cert</X509Certificate>
                </X509Data>
            </KeyInfo>
        </KeyDescriptor>
        <KeyDescriptor use="signing">
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <X509Data>
                    <X509Certificate>some cert</X509Certificate>
                </X509Data>
            </KeyInfo>
        </KeyDescriptor>
        <KeyDescriptor use="signing">
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <X509Data>
                    <X509Certificate>some cert</X509Certificate>
                </X509Data>
            </KeyInfo>
        </KeyDescriptor>
        <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                             Location="https://login.microsoftonline.com/[id]/saml2"/>
        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                             Location="https://login.microsoftonline.com/[id]/saml2"/>
        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                             Location="https://login.microsoftonline.com/[id]/saml2"/>
    </IDPSSODescriptor>
</EntityDescriptor>
```

Failed tests

```
 flow › send login response with [custom template] and signed assertion + signed message and parse it

  Rejected promise returned by test

  Rejection reason:

    "Invalid XSD schema"




  flow › send login response with signed assertion + signed message and parse it

  Rejected promise returned by test

  Rejection reason:

    "Invalid XSD schema"

```

**Comment by tngan** [comment]
@gtothesquare  Yes, samlify is supposed to handle multiple key descriptors, apparently it is a bug. If you have already fixed it, I would be happy to accept a pull request, I will take care of the failed tests.

For the failed tests, it could be because of failed schema validation.

https://github.com/tngan/samlify/blob/13aff6a5ee22fd5ba5cc51d7b5b246d500c52ff6/src/libsaml.ts#L704-L708

**Comment by gtothesquare** [comment]
@tngan damn, you are fast 🥇. Thanks!

**Comment by tngan** [comment]
@gtothesquare For the failed build, it's a bit of weird in travis ci, sometimes when I rebuilt is good but sometimes isn't, I will change to use `npm install` instead of `yarn` in travis ci config later on.

The commit will be patched on this friday. 15:00 UTC
