### ISSUE TITLE
Is version 2.3.3 published on npm?

### ISSUE THREAD

**Issue by gtothesquare** [tngan/samlify#140]
I'm having issues with the latest npm deploy. I made sure version 2.3.3 was installed. However, the fix for parsing `SessionIndex` (was added in PR #137), is not working. 

I tried installing it via pulling from the latest from master, building it locally (`yarn build`) and then installing via local file ref in the package json (`"samlify": "file:../samlify"`) and it works.

Not familiar with how packages build with TS work but @tngan maybe you forgot to build it before releasing it ?

**Comment by tngan** [comment]
@gtothesquare It should be included. You can check out both `src/entity-sp.ts` and `build/src/entity-sp.js`, the pull request and its build are included.

**Comment by gtothesquare** [comment]
@tngan is missing in the build
![image](https://user-images.githubusercontent.com/370567/31824287-dd2ea9fc-b5ae-11e7-9269-7b6c029a4c2d.png)

Here is the `ts` source
![image](https://user-images.githubusercontent.com/370567/31824337-0445de2a-b5af-11e7-8259-e637bb9bc976.png)

**Comment by tngan** [comment]
@gtothesquare I have reinstalled samlify with npm, and check inside `node_modules`, the changes are included in the `entity-sp.js` line 110. Please also let me know which `npm` version you are using.

```bash
# my reinstallation script
$ npm install samlify@latest
$ vi node_modules/samlify/build/src/entity-sp.js
```

**Comment by tngan** [comment]
@gtothesquare Please also send an email to `passify.io@gmail.com` if you still encounter same problem, we can probably schedule a call to get rid of it.

**Comment by tngan** [comment]
@gtothesquare The deletion of changelog is not yet pushed to npm. I know what problem in my computer as well, the `node_module/samlify` folder somehow symlinks with my local development folder, so what I have seen is the build version, that's why I saw the changes. I will publish a new version for it now.

**Comment by tngan** [comment]
@gtothesquare Sorry for causing inconvenience, it's bumped to v2.3.4 now.

**Comment by gtothesquare** [comment]
@tngan thanks!!!!

**Comment by tngan** [comment]
@gtothesquare Before I published to npm, I would run test first, and the test script includes the build script as well. I will try to made a pre-push hook to streamline and avoid same issue from happening again, thank you for raising the issue. 👍
