### ISSUE TITLE
Many of the XML Namespaces are messed up or ignored when passing around and between libraries

### ISSUE THREAD

**Issue by wwindcloud** [tngan/samlify#146]
When extracting metadata from established IDP or SP, the namespaces seem to be messed up, or rather, samlify just pretend they did not exist except at the document node.

E.g. in IdpMetadata or SpMetadata, an xml string is generated at the constructor. However, the generated xml is considered malformed once their namespaces are taken into account.  I know it's because the underlying xml library doesn't really care about namespaces, but standard SAML **do** care. In order to fix this, I have to replace "xmlns:md" with "xmlns" and fix <KeyInfo/>, <X509.../> with their equivalent namespace. I suggest the author better replace the "xml" library with xmldom and use DOM functions with proper NS support instead of passing around with namespace-less shortcuts.

Another bigger problem I found out is in the SAML response generation, you assumed there's a tagPrefix for EncryptedAssertion, but did not give it a correct namespace URI, that way, xmldom has no way of knowing which correct namespace you are referring to. So everytime generating SAML response, I got something like <saml:EncryptedAssertion xmlns:saml="">....</saml:EncryptedAssertion>, well, some picky program complain about this, and I cannot really fix it outside because the whole XML is signed.

There seems to more of these things lying around but the two aforementioned problems stand out to me for the time being. I think for the the better of this library, we should start to take **XML Namespace** more seriously.

Other than that, props to @tngan on making this library. It makes my job easier. Thanks.

**Comment by tngan** [comment]
@wwindcloud Thanks for your feedback, I really appreciated that. I have tried to build from a minimal viable example. Since more and more people are using this library, we will try to include more validations like schema check following the SAML standard. I agree the namespaces things are quite messed up, and those assumptions will be removed as soon as we can. Pull requests are welcome as well.

**Comment by tngan** [comment]
@wwindcloud The above two pull requested will be patched today around 15:00 UTC.

**Comment by tngan** [comment]
Patched (#147, #148) in v2.3.5.

**Comment by wwindcloud** [comment]
Hey @tngan, thanks for merging my pull requests. I think that's all the namespace fixes I have for now.

Another thing I have noticed, which is not namespace related. Perhaps to open another issue???

Well, I have found out IdentityProvider/ServiceProvider does not decode the metadata xml correctly if KeyDescriptor has no *use* attribute. According to spec, that is supposed to be a shortcut for specifying both signing and encryption using the same certificate. I am tempted to fix that inside libsaml.extrator, but I guess that function is kind of like your quick generic xml extraction routine, so better to leave that to you since I think you eventually will have to revamp those parts to allow more functionality.

**Comment by tngan** [comment]
@wwindcloud Thanks for your contribution. Besides, I have also written a short release note for every release and given credits to each contributor as well.

`Another thing I have noticed, which is not namespace related. Perhaps to open another issue???`

Yes, please open another one. For my short answer, you are right, this function will be eventually rewritten. If I don't understand wrongly, service provider will need to try each certificate for signature verification/encryption during runtime if `use` is not specified. Let's continue the discussion in the new thread.

So, I will close this issue for now, we can reopen it when we find any issues related later on.
