### ISSUE TITLE
Invalid metadata

### ISSUE THREAD

**Issue by stelescuraul** [tngan/samlify#149]
@Hello,

I have tried to create SP metadata using the following configuration: 

```js
const settings = {
  allowCreate: false,
  authnRequestsSigned: false,
  generateID: true,
  isAssertionEncrypted: false,
  encryptCert: undefined,
  nameIDFormat: [
    'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'
  ],
  requestSignatureAlgorithm: 'http://www.w3.org/2000/09/xmldsig#rsa-sha1',
  wantAssertionsSigned: true,
  wantMessageSigned: false,
  assertionConsumerService: [
    {
      Binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
      Location: 'https://localhost:3000/consume',
      isDefault: true
    }
  ],
  entityID: 'TEST'
};

const sp = saml.ServiceProvider(settings);

console.log(sp.getMetadata());
```

The xml produced is:
`<EntityDescriptor entityID="TEST"
  xmlns="urn:oasis:names:tc:SAML:2.0:metadata"
  xmlns:assertion="urn:oasis:names:tc:SAML:2.0:assertion"
  xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
  <SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat>
    <AssertionConsumerService index="0" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://localhost:3000/consume" isDefault="true"></AssertionConsumerService>
  </SPSSODescriptor>
</EntityDescriptor>`

which is alright, but it fails to validate (both on samltools and in ADFS when trying to upload a file with that config). However, if I add `md:` to each element it does work. So the previous xml should be: 
`
<md:EntityDescriptor entityID="TEST"
  xmlns="urn:oasis:names:tc:SAML:2.0:metadata"
  xmlns:assertion="urn:oasis:names:tc:SAML:2.0:assertion"
  xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
  <md:SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
    <md:AssertionConsumerService index="0" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://localhost:3000/consume" isDefault="true"></md:AssertionConsumerService>
  </md:SPSSODescriptor>
</md:EntityDescriptor>`
 Notice the `md` for elements. I have found [this](https://github.com/tngan/samlify/issues/32) Issue which was closed but cannot find any solution. Has this been fixed / is it supported ? If it is supported, how do i enforce it ? 

Another option is to remove the `:md` from `xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"` but then I believe there would be issues with signature tags or assertion tags.

**Comment by stelescuraul** [comment]
I saw the PR and the modifications for this. I updated the package locally and it works fine now :)

**Comment by tngan** [comment]
@stelescuraul Glad to hear you have worked this out.
