### ISSUE TITLE
Signing SAML Response message results in invalid Signature (Reference URI is empty)

### ISSUE THREAD

**Issue by wwindcloud** [tngan/samlify#153]
I have a client complaining that we were generating an invalid signature in SAML response. After checking through the code, specifically in https://github.com/tngan/samlify/blob/fb36823a9df5ba1bc61bc22443d84c28bb430d17/src/libsaml.ts, the function constructSAMLSignature, I have found out it's passing **true** in the last argument to addReference. However according to SAML spec

> 5.4.2 References
> Signed SAML assertions and protocol messages MUST supply a value for the identifier attribute on the root element (<Assertion>, <Request>, or <Response>). The assertion’s or message's root element may or may not be the root element of the actual XML document containing the signed assertion or message.
> Signatures MUST contain a single <ds:Reference> containing a URI reference to the identifier attribute value of the root element of the message being signed. For example, if the attribute value is "foo", then the URI attribute in the <ds:Reference> element MUST be "#foo".

Is there any reason why we want an empty URI in **ds:Reference** ? If not, can we fix it by simply passing a false or remove that argument. Thanks.

**Comment by tngan** [comment]
@wwindcloud I am out of town these few days, sorry for the late reply. May I ask how is the SAML response being signed, assertion or entire message ?

I will review the steps of doing signature during weekend and help to get rid of it.

**Comment by wwindcloud** [comment]
@tngan Actually this is a very minor issue as everything is doing pretty much ok. It's when some SP taking a strict security measure complaining the signed Response having an empty Reference URI attribute. That is if the root node is <samlp:Response ... ID="abc">...</samlp:Response>, then the signature generated should have a <Reference URI=\"#abc\"/> within <SignedInfo\/>.

The problem is that your code generate a <Reference URI=\"\"/> instead, and the culprit is it's passing a "true" in the last argument of addReference in constructSAMLSignature.
The <Reference URI=\"\"/> happens when anyone wantMessageSigned = true in SAML Response. However, the URI emit correctly inside <Assertion\/> for wantAssertionSigned = true. Hope's that helps.

**Comment by tngan** [comment]
@wwindcloud Yes, this is because of the issue in root element signature (i.e. the message), the code to generate message signature is referred to this issue (https://github.com/yaronn/xml-crypto/issues/122).

I am currently overloaded during this few weeks, but pull request is absolutely welcome, and this repository is still actively maintained.
