### ISSUE TITLE
Use case example location

### ISSUE THREAD

**Issue by darraghpjones** [tngan/samlify#154]
I'm having trouble locating/generating the examples discussed in the wiki documentation here:  

https://github.com/tngan/samlify/wiki/Use-cases 

Are these located somewhere else or is there specific instructions for generating them?

**Comment by tngan** [comment]
@darraghpjones Those examples are removed since the commits included in this issue (#76).

**Comment by tngan** [comment]
@darraghpjones Feel free to ask questions via email passify.io@gmail.com, in case if you don't wan to expose your business logic and secret here.
