### ISSUE TITLE
Support for ForceAuthn

### ISSUE THREAD

**Issue by gsvitak** [tngan/samlify#155]
Hello

Curious if the library currently support setting ForceAuthn to make the IDP authenticate on every request.

Could you point me in the direction if we needed to implement this feature?

Thanks,
G

**Comment by tngan** [comment]
@gsvitak Currently it's possible to override the default login request template, add `ForceAuthn` property inside and set its value during runtime. The following test example illustrates the usage for overriding template.

https://github.com/tngan/samlify/blob/56480f7852baba147389403cc5f3fe826c0f2e39/test/flow.ts#L181-L194

**Comment by tngan** [comment]
@gsvitak We have it in documentation, see [here](https://samlify.js.org/#/template?id=custom-templates).
