### ISSUE TITLE
Error on the server side : Cannot read property 'SAMLResponse' of undefined

### ISSUE THREAD

**Issue by Antho2407** [tngan/samlify#156]
Hey there ! I am trying to sort my onelogin sso authentification following this example : 
https://samlify.js.org/#/onelogin

I'm a bit confused by this bit : 
```
router.get('/spinitsso-redirect', (req, res) => {
    const url = sp.createLoginRequest(idp, 'redirect');
    return res.redirect(url);
});
```
The "url" returned is actually an object ? I had to do ```url.context``` to get the url back

I am now trying to access ```myurl/sso/spinitsso-redirect``` but getting the following error : 
```TypeError: Cannot read property 'SAMLResponse' of undefined```

Any ideas why ? Am I missing something ?

**Comment by tngan** [comment]
@Antho2407 Yes, I have to admit that the example is not being updated properly. The API has changed after a long discussion in this thread (https://github.com/tngan/samlify/issues/50). During the meantime of developing the separate example repository [passify/samlify-ap](https://github.com/passify/samlify-sp), you can basically refer to those test cases in flow.ts which cover most of the common use cases.

I also want to know how you construct the `sp` as well.

**Comment by tngan** [comment]
This is how we can kickstart sp-initiated sso.

https://github.com/tngan/samlify/blob/master/test/flow.ts#L130-L145

Another endpoint is created for accepting the response from your idp.

https://github.com/tngan/samlify/blob/master/test/flow.ts#L261-L274

In other words, idp-initiated sso is the last step of sp-initiated sso.

**Comment by Antho2407** [comment]
@tngan this was my original code : 
```
const fs = require('fs')
const path = require('path')
const saml = require('samlify')
const express = require('express')
const router = express.Router()
const ServiceProvider = saml.ServiceProvider
const IdentityProvider = saml.IdentityProvider

// Configure your endpoint for IdP-initiated / SP-initiated SSO
const sp = ServiceProvider({
    metadata: fs.readFileSync(path.join(__dirname, '/metadata/app.xml'))
})
const idp = IdentityProvider({
    metadata: fs.readFileSync(path.join(__dirname, '/metadata/onelogin.xml'))
})

// Release the metadata publicly
router.get('/metadata', function (req, res) {
    res.header('Content-Type', 'text/xml').send(sp.getMetadata())
})

// Access URL for implementing SP-init SSO
router.get('/spinitsso-redirect', function (req, res) {
    const url = sp.createLoginRequest(idp, 'redirect')
    res.redirect(url.context)
})

// If your application only supports IdP-initiated SSO, just make this route is enough
// This is the assertion service url where SAML Response is sent to
router.post('/acs', function (req, res) {
    sp.parseLoginResponse(idp, 'post', req)
        .then(parseResult => {})
        .catch(console.error)
})

module.exports = router

```

**Comment by tngan** [comment]
@Antho2407 The code looks fine. Did you see the url changed ? If everything goes correctly, you will be stopped by the onelogin portal (if you didn't login before, otherwise, the assertion service url /acs will be hit by the response from onelogin).

**Comment by Antho2407** [comment]
Yep it was redirecting me to onelogin and it's definitely trying to hit ```/acs```, but I'm getting the error described and nothing happens 😢

**Comment by Antho2407** [comment]
Was assuming something was wrong in my config

**Comment by tngan** [comment]
The api of handler `parseLoginResponse` is changed, the following is the example.

So, can you log the `req.body` and see what is inside, possibly the parser is not set properly.

```js
const { samlContent, extract } = await sp.parseLoginResponse(
  idp, 
  'post', 
  { body: { SAMLResponse } }
);
```

**Comment by Antho2407** [comment]
tried the following : 
```
router.post('/acs', function (req, res) {
    // sender (caution: only use metadata and public key when declare pair-up in oppoent entity
    const { context: SAMLResponse } = idp.createLoginResponse(
        sp,
        { extract: { authnrequest: { id: 'request_id' } } }, 'post',
        { email: 'user@esaml2.com' }
    )
    console.log('SAMK', SAMLResponse)
    sp.parseLoginResponse(idp, 'post', { body: { SAMLResponse } })
        .then(parseResult => {
        })
        .catch(console.error)
})
```
the SAMLResponse is apparently undefined (as was req.body)

**Comment by tngan** [comment]
Then I guess you need the body-parser middleware. (https://www.npmjs.com/package/body-parser)

**Comment by tngan** [comment]
For the above code you provided for debugging, it shows some configurations are missing as well. You have mentioned that onelogin does redirect back to /acs with a POST/ response, so I want to see what is inside the response as well, normally you can get the content from `req.body.SAMLResponse`.

I don't know your metadata right now, so I don't know what is exactly missing. If you don't want to expose the secret, please kindly send the email to passify.io@gmail.com. We're glad to help you to get rid of it.

**Comment by Antho2407** [comment]
@tngan The body parser was definitely part of the issue, added the middleware and tweaked a bit the configuration, i'm now getting a SAML response back, thanks a lot !

Will close the issue for now and reopen it if i'm having new issues

**Comment by tngan** [comment]
@Antho2407 Cool, glad to hear that you have solved the problem.

**Comment by litianc** [comment]
@Antho2407 @tngan  I also meet the same problem. 
I install the body-parser with `npm install body-parser`, but the error is still there.
TypeError: Cannot read property 'SAMLResponse' of undefined
How did you solve the problem with body-parser? Could you show me the code?

**Comment by kevboutin** [comment]
> @Antho2407 @tngan I also meet the same problem.
> I install the body-parser with `npm install body-parser`, but the error is still there.
> TypeError: Cannot read property 'SAMLResponse' of undefined
> How did you solve the problem with body-parser? Could you show me the code?


```
const urlencodedParser = bodyParser.urlencoded({ extended: false });

router.post('/acs', urlencodedParser, (req, res) => {
    // Sender (caution: only use metadata and public key when declare pair-up in oppoent entity)
    const { context: SAMLResponse } = idp.createLoginResponse(
        sp,
        { extract: { authnrequest: { id: 'request_id' } } }, 'post',
        { email: 'user@esaml2.com' }
    );
    // Handles signature and issuer name validation.
    sp.parseLoginResponse(idp, 'post', { body: { SAMLResponse: req.body.SAMLResponse } }).then(parseResult => { ...
```

**Comment by tngan** [comment]
@kevboutin Which samlify version are you using ? This is the sample express server in the example, the example is sp-initiated single sign on.

https://github.com/passify/react-samlify/blob/master/server.ts

**Comment by hackintoshsa** [comment]
@Antho2407 I need help @tngan i need help, wanted to run this but keep getting this error 
TypeError: Cannot read property 'SAMLResponse' of undefined
