### ISSUE TITLE
RelayState not being returned in parseLoginResponse

### ISSUE THREAD

**Issue by jamespedid** [tngan/samlify#157]
Hello; it would appear that the RelayState parameter is not being returned in the sp.parseLoginResponse payload. Is this intentional?

**Comment by tngan** [comment]
@jamespedid We haven't included it in the parser for login response yet, but it's possible. Please also let me know more about your use case. Of course, pull request is welcome.

**Comment by tngan** [comment]
@jamespedid Since it's not being updated for 3 months, I will close this and continue the discussion to #163. We may change the way to handle relay state.
