### ISSUE TITLE
Signed AuthN request does not appear to produce valid signature

### ISSUE THREAD

**Issue by gsvitak** [tngan/samlify#159]
Hello,

Thank you for the great work. 

I am really stumped and would like to share my findings to see if anyone can suggest a resolution. We have v2.2.0 working in production with IDPs that do not require a signed authn request. We now have to add support for a signed request via HTTP-Redirect. 

I have tried to follow the documentation and it appears v 2.3.6 does not produce a valid signature that works with Shibboleth. I have also tried to validate the request via https://www.samltool.com/validate_authn_req.php and it is failing validation.

One other stumping note, we have a separate product that is written in python. I have configured the SP on the python product to point to the Shibboleth IDP and it works great. We use https://github.com/onelogin/python3-saml for the other product. I used the same certs and private key as the samlify implementation. 

Other points of note: I have verified that the timestamps on both servers are matched. I have also verified the IDP settings has 'WantAuthnRequestsSigned'=true.

As far as how I have implemented the changes, I have followed the documentation and added the following.

```
if (signRequest) {
        const privateKeyPassFile = process.env.FULL_PRIVATE_KEY_FILE_PATH || privateKey;
        const privateKeyPassword = process.env.PRIVATE_KEY_PASSWORD || privateKeyPass;
        setting.privateKey = fs.readFileSync(privateKeyPassFile);
        setting.privateKeyPass = privateKeyPassword;
        setting.requestSignatureAlgorithm = requestSignatureAlgorithm;
        setting.authnRequestsSigned =true;
    }

    return ServiceProvider(setting);
```

One question. I have cloned the repo to try to add a few tests with our certs to see if the signature would line up. What tool do you use to generate the signature for the following? I am asking so I can see if my tests will pass and I need to generate my own hard coded test harness data.

` const dummySmokeSignRequest: string =`

Any suggestions of other items to try?

Thanks
G

**Comment by gsvitak** [comment]
Update.. we figured out the issue. It appears the main issue was an XML namespace issue. The service provider metadata file was missing a namespace on the KeyDescriptor element. I think we might made a dumb mistake because we might have copied and pasted from one of the examples that did not have namespace elements.

Thanks again for the hard work.

```
<KeyDescriptor use="signing">
<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:X509Data>
<ds:X509Certificate>
cert value</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</KeyDescriptor>
```

**Comment by tngan** [comment]
@gsvitak Glad to hear you have worked this out.
