### ISSUE TITLE
error with angular2

### ISSUE THREAD

**Issue by mathmans** [tngan/samlify#160]
Hello,

I try to add your module to an angular2 application and I have these compilations errors

![image](https://user-images.githubusercontent.com/13812903/35463264-0d89e614-02f0-11e8-84d0-3e162a0ad55c.png)

**Comment by tngan** [comment]
@mathmans Would you like to make a sample boilerplate repo or gist for the ng2 application ?

**Comment by tngan** [comment]
@manuvalle Since it's not being updated for a while, I will close it first. Please reopen if needed.
