### ISSUE TITLE
Making x509 cert in auth response optional

### ISSUE THREAD

**Issue by nilsve** [tngan/samlify#162]
I have created a SSO link with a Dutch school IDP, and had trouble with samlify not being able to parse their login response.

Samlify expected the IDP to always include the certificate in the response, but the IDP doesn't.

I have made it optional in my fork, it will first look for a certificate in the response, and will fall back to the metadata.xml certificate if it can't find one.

https://github.com/nilsve/samlify/commit/7eb057f5c9e342bc65c93d043ae8e9e30d60b075

**Comment by tngan** [comment]
@nilsve 

Thank you so much for reporting this use case. We may consider to integrate a flag in entity level for this use case in the near future. Let me close it first, and will link a new issue to it later on when we start working on the enhancement.
