### ISSUE TITLE
Memory leak in parseLoginRequest

### ISSUE THREAD

**Issue by nilsve** [tngan/samlify#165]
Ever since we upgraded from express-saml to samlify, our servers are crashing daily because of a memory leak in combination with the volume of requests we receive. We have narrowed it down to the `isValidXml` function, which gets called from `parseLoginRequest`.

I have looked around for a bit, and it seems the problem lays deep somewhere in native C++ code. 

We're going to try to change to the `xml-xsd-validation` library. If this fixes it for us I will submit a PR.

Just a heads up for anyone wanting to use this library who receive a lot of traffic

UPDATE:

We ended up just removing the whole xml validation code. Our use case requires a signed response anyways, so its not possible for an attacker to send us invalid data.

**Comment by tngan** [comment]
@nilsve Thanks for your update. I am also considering to replace the xml validation with some libraries else since the current one introduces a lot of problems.
