### ISSUE TITLE
parseLoginResponse does not validate the SAML Assertion Expiration (NotBefore, NotOnOrAfter)

### ISSUE THREAD

**Issue by ikkisoft** [tngan/samlify#166]
It appears that this library does not validate the SAML assertion expiration by default. I've verified on a testing setup and the _NotBefore_, _NotOnOrAfter_ fields are not checked.

According to https://github.com/tngan/samlify/blob/1c081f95c074c9ee95a3fcaade4930a17cf16c67/docs/saml-response.md

> We do the basic checking and leave for developers to write their own callback. (e.g. verify the conditions, status code ... etc).

In my opinion, this should be considered as a security bug since I would expect something as important as expire dates to be verified. 

In case of expiration, this should not return _success_. This insecure default setting leaves applications vulnerable to reply attacks.

**Comment by tngan** [comment]
@ikkisoft Yes, there is a proposal on #111. We will handle the basic validation soon.

**Comment by ikkisoft** [comment]
Great, missed that it was already mentioned somewhere. 

May I suggest to create a label "security" so it's easy for people like me to understand open issues with security implications. Thanks!

**Comment by tngan** [comment]
@ikkisoft Sure. Let me link this issue back to #111. Then I will close this one as well.
