### ISSUE TITLE
node-forge dependency vulnerable to Regular Expression Denial of Service 

### ISSUE THREAD

**Issue by ikkisoft** [tngan/samlify#167]
One of the dependencies of Samlify - **node-forge** is affected by a known RegExp DoS vulnerability.

* _samlify@2.3.6 > node-forge@0.7.1_
* _samlify@2.3.6 > xml-encryption@0.11.0 > node-forge@0.7.1_

See for more details
https://snyk.io/vuln/npm:node-forge:20180226

Once the maintainer fixes the issue, you would need to bump the version of both deps.

**Comment by tngan** [comment]
@ikkisoft Some updates on this critical issue.

node-forge is upgraded to 0.7.4 to fix this issue two days ago, I have opened a [pull request](https://github.com/auth0/node-xml-encryption/pull/42) to xml-encryption to fix that as well.

**Comment by tngan** [comment]
@ikkisoft The new version is just released to v2.3.7. Checkout the release note [here](https://github.com/tngan/samlify/releases/tag/v2.3.7). Thank you so much again 👍 .
