### ISSUE TITLE
Migrating from express-saml2

### ISSUE THREAD

**Issue by mikevbaker** [tngan/samlify#169]
Hi. Thanks for all the work you put in on this. I'm looking at the steps needed to change over from express-saml2 to samlify and I have a question about the sample. I used the IdP, SP1 and SP2 samples from express-saml2 to figure out how to implement. The sample code in [this doc](https://samlify.js.org/#/onelogin) has just about everything I have, but in my code I have a handler for * that checks the storage and re-directs. 

`
    // Send all requests to index.html so browserHistory works
    app.get('*', function (req, res) {
        if (cookieVault.read(req) === COOKIE_CODE) {
            res.sendFile(path.join(__dirname, publicPath, 'index.html'))
        } else {
            if (!req.url.includes('favicon'))
                res.redirect('/sso/login');
        }
    })
`

The sample at [samlify-sp](https://github.com/passify/samlify-sp) is nothing like the express sample in the doc. Is there a finished sample that uses the code from the OneLogin doc? I'd like to make sure I'm handling all the routes correctly.

Thanks,
Mike

**Comment by tngan** [comment]
@mikevbaker For samlify-sp, this is the example for dynamically configuration of identity provider on-the-fly. And those functionalities, for examples send request, parse response are still WIP (due to my recent heavy daily workload, it won't be finished by the end of Q1). By following the example in the doc, you should be able to make the first pass.

I am happy to be your helping hands in order to migrate from the old version to the new one. Please send your questions to passify.io@gmail.com since you may not want to expose those business logic here.

**Comment by mikevbaker** [comment]
I have an update for this. I haven't touched this project for over a year and I had to spend some time figuring out the debugger again. Once I did that I think I figured out an issue with the documentation. In the [OneLogin](https://samlify.js.org/#/onelogin?id=work-with-onelogin) doc the redirect works like this

```
router.get('/spinitsso-redirect', (req, res) => {
    const url = sp.createLoginRequest(idp, 'redirect');
    return res.redirect(url);
});
```

The problem is that the `createLoginRequest(idp, 'redirect');` function returns an object rather than an URL. The redirect works if I use this instead:

```
app.get('/sso/login', function(req, res) {
    const redirectRequest = sp.createLoginRequest(idp, 'redirect');
    res.redirect(redirectRequest.context);
});
```
Mike

**Comment by tngan** [comment]
@mikevbaker Yes, the API got changed in the version (>=2), the documentation is not updated, thanks for your report.

**Comment by tngan** [comment]
@mikevbaker The documentation has been finally updated for the change.

**Comment by mikevbaker** [comment]
Thanks! J

**Comment by mikevbaker** [comment]
Hey Tony,

 

I finally got around to writing that article on my experience putting samlify to work in AWS. If you’re interested you can find it here for the time being…

 

http://relianceinteractive.com/Articles/angularjs-aws-and-sso/angularjs-aws-and-sso.htm

 

Let me know if you want me to make any corrections.

 

Mike

 

 

From: Michael Baker [mailto:Mike.Baker@RelianceInteractive.com] 
Sent: Friday, May 04, 2018 1:34 PM
To: 'tngan/samlify'
Subject: RE: [tngan/samlify] Migrating from express-saml2 (#169)

 

Thanks! J
