### ISSUE TITLE
Where are these express example !! 

### ISSUE THREAD

**Issue by tkssharma** [tngan/samlify#172]
Use cases

For those who may be interested, there are three express application simulating one identity provider and service provider.

**Comment by tngan** [comment]
@tkssharma Sorry for late reply. I didn't have enough time to work on it recently. Basically, most of the common use cases can be found in the test file including login and logout flow with different binding.

**Comment by tngan** [comment]
@tkssharma Please reopen this ticket if you have encountered problems in your implementation.
