### ISSUE TITLE
NameIDFormat incorrectly replaced and usage

### ISSUE THREAD

**Issue by bhamon** [tngan/samlify#173]
The issue #67 corrects a naming problem in `binding-redirect.ts`. There is the exact same problem in https://github.com/tngan/samlify/blob/6612d586274b51f0ebe521a4be27e232bb3d2a4b/src/binding-post.ts#L44.

Apart from that, I can't find any way to use the `loginNameIDFormat` nor the `logoutNameIDFormat`.
The `ServiceProviderSetting` definition doesn't seem to allow those properties anymore: https://github.com/tngan/samlify/blob/d3b3e4a2ca4af68e5163771303dbb1b193e48d39/src/types.ts#L62

Can you provide me an example of how I can overwrite the `NameIDPolicy` `Format` attribute?
In the meantime I use a custom template.

**Comment by tngan** [comment]
@bhamon Good catch, will fix it soon.

**Comment by juckerf** [comment]
am I wrong or is there still no way to set loginNameIDFormat/logoutNameIDFormat?

**Comment by tngan** [comment]
@juckerf Just pass in `logoutNameIDFormat` in the entity (sp/idp) constructor.

For the value of `loginNameIDFormat`, it is well defined as the one of the following values. (e.g. `emailAddress` ... )

https://github.com/tngan/samlify/blob/031cafdbb068dd32c4ec247bf829ab0598701046/src/urn.ts#L24-L31

**Comment by juckerf** [comment]
@tngan 
hmm... if I create a new ServiceProvider as follows, the `nameIdFormat` in the login request sent to our 3rd party IdP (shibboleth) remains `emailAddress`:
```js
new saml.ServiceProvider({
      ...additionalOptions,
      encPrivateKeyPass: keyPass,
      encPrivateKey: fs.readFileSync(keyPath),
      encryptCert: spCert,
      signingCert: spCert,
      nameIDFormat: [saml.Constants.namespace.format.transient],
      loginNameIDFormat: saml.Constants.namespace.format.transient,
    });
```
resulting login request:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<samlp:AuthnRequest
    AssertionConsumerServiceURL="http://localhost:3000/shibboleth/assert"
    Destination="https://aaidev.tam.ch/idp/profile/SAML2/Redirect/SSO"
    ID="_6b8ad5a5-a1d0-4923-a235-9d5949483621"
    IssueInstant="2018-08-17T11:58:32.959Z"
    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    Version="2.0" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <saml:Issuer>http://localhost:3000/shibboleth</saml:Issuer>
    <samlp:NameIDPolicy AllowCreate="false" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"/>
</samlp:AuthnRequest>
```

(I'm using samlify 2.4.0-rc1)

**Comment by eugene1g** [comment]
@juckerf @tngan Looks like the correct syntax to specify `NameIDPolicy` is to use one of the string keys as specified at https://github.com/tngan/samlify/blob/15db8b4cb2fc0cfadd074187adc8a11b14e7cc29/src/urn.ts%23L61 rather than using the `Constants` value. So this works:
```js
new saml.ServiceProvider({
      ...additionalOptions,
      loginNameIDFormat: "transient"
    });
```
