### ISSUE TITLE
Syntax error in type libsaml.d.ts

### ISSUE THREAD

**Issue by samgauklrna** [tngan/samlify#174]
Using 
```
"typescript": "2.7.2",
"samlify": 2.3.7
```

Results in syntax error when compiling

```
node_modules/samlify/types/src/libsaml.d.ts(99,24): error TS1005: ';' expected.
node_modules/samlify/types/src/libsaml.d.ts(105,29): error TS1005: ';' expected.
```

I've cloned and built project and did not end up with the same issues. Has something went wrong while uploading to npm? 

The block that has issues in libsaml.d.ts
```
    createKeySection(use: KeyUse, certString: string | Buffer): {
        KeyDescriptor: ({
            _attr: {
                use: KeyUse;
            };
            ds:KeyInfo?: undefined; <-- ? 
        } | {
            'ds:KeyInfo': ({
                _attr: {
                    'xmlns:ds': string;
                };
                ds:X509Data?: undefined; <-- ?
            } | {
                'ds:X509Data': {
                    'ds:X509Certificate': string;
                }[];
                _attr?: undefined;
            })[];
            _attr?: undefined;
        })[];
```

**Comment by dhruvbhatt22** [comment]
I am using angular CLI and getting the same error as above on the same lines mentioned by [samgauklrna](https://github.com/samgauklrna)

 `ERROR in node_modules/samlify/types/src/libsaml.d.ts(99,23): error TS1005: ';' expected.
node_modules/samlify/types/src/libsaml.d.ts(99,24): error TS1131: Property or signature expected.
node_modules/samlify/types/src/libsaml.d.ts(105,28): error TS1005: ';' expected.
node_modules/samlify/types/src/libsaml.d.ts(105,29): error TS1131: Property or signature expected.`
