### ISSUE TITLE
problem with sp.createLoginRequest

### ISSUE THREAD

**Issue by tinque** [tngan/samlify#176]
In the documentation you have the following exemple : 
```(javascript)
router.get('/spinitsso-redirect', (req, res) => {
    res.redirect(sp.createLoginRequest(idp, 'redirect'));
});
```
but the method `sp.createLoginRequest(idp, 'redirect')` return the object : 
```(javascript)
{ id: '_53e9c609-30f5-42fa-b22e-7c7902b5fdba',
  context: 'URL to redirect' }
```

Is it a documentation problem or a bug ?

**Comment by tngan** [comment]
@tinque The documentation isn't updated.

**Comment by tinque** [comment]
Thanks !

**Comment by tngan** [comment]
@tinque I will updated it soon. Thanks for catching it.
