### ISSUE TITLE
Binding typo in redirect

### ISSUE THREAD

**Issue by JbIPS** [tngan/samlify#179]
Hello,

I spotted a weird thing in the [binding-redirect file](https://github.com/tngan/samlify/blob/master/src/binding-redirect.ts#L98): is `binding.post` on purpose or is it a typo?

Thanks

**Comment by tngan** [comment]
@JbIPS Sorry for the late reply. The URL specified by assertion consumer service is where the IDP's response hits SP, it only supports POST binding and Artifact binding but we only support POST binding.

>In step 5, the identity provider issues a <Response> message to be delivered by the user agent to the service provider. Either the HTTP POST, or HTTP Artifact binding can be used to transfer the message to the service provider through the user agent. The message may indicate an error, or will include (at least) an authentication assertion. The HTTP Redirect binding MUST NOT be used, as the response will typically exceed the URL length permitted by most user agents.

FYI: [Section 4.1.2-5 Identity Provider issues <Response> to Service Provider](http://docs.oasis-open.org/security/saml/v2.0/saml-profiles-2.0-os.pdf)
