### ISSUE TITLE
XML escape characters are not encoded

### ISSUE THREAD

**Issue by Chrn** [tngan/samlify#183]
Hi,

I noticed when the metadata xml contains any escape characters such as `&amp;`, when it is encoded into the SAMLRequest xml escaped character is not encoded properly and only the `&` gets encoded.

Metadata

```xml
<EntityDescriptor xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  entityID="https://test.com/test" xmlns="urn:oasis:names:tc:SAML:2.0:metadata">
    <IDPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        <KeyDescriptor use="signing">
            <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
                <X509Data>
                    <X509Certificate>example1</X509Certificate>
                </X509Data>
            </KeyInfo>
        </KeyDescriptor>
        <SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                             Location="https://test.com/applogout/appkey/test /><NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</NameIDFormat><NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</NameIDFormat><NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName</NameIDFormat><NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:WindowsDomainQualifiedName</NameIDFormat><NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:kerberos</NameIDFormat><NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:entity</NameIDFormat><NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</NameIDFormat><NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</NameIDFormat><SingleSignOnService Binding="
                             urn:oasis :names:tc :SAML:2.0 :bindings:HTTP-POST" Location="https:
        //testcom/run?appkey=test&amp;customerId=test" />
        <SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                             Location="https://test.com/run?appkey=test&amp;customerId=test"/>
        <Attribute Name="Email Address" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                   xmlns="urn:oasis:names:tc:SAML:2.0:assertion"/>
    </IDPSSODescriptor>
</EntityDescriptor>
```

SAML Request

`
SAMLRequest=fZJfT8IwFMW%2FytIH3%2FaPTTIahkGIkQSVCPrgi%2Bm6O2jo2tnbqnx7y9BEH%2BSlSU%2Fvuff82o6RtbKjU2d36hHeHKANPlupkPYHJXFGUc1QIFWsBaSW0%2FX0bkkHUUI7o63mWpJflvMOhgjGCq1IsJiX5DWtcn5ZpBBmVVGHeZYUIWN%2BgWxUVKNmNMibIQmewaD3lMS38EZEBwuFlinrpSQtwmQYpoNNmtMko3kWJenohQRzzyIUs71zZ22HNI6tFyOu29g4dcW6bg%2BH8qhdcIdWt2AWdb8nweob7lqoWqjtea7qVIT0drNZhauH9YYE0x%2FWmVbofOs1mHfB4elxecrj46itO4DSZhsdh9IiKZL4eIux1FuhYs6krBjfk8n4qNIe3Uz%2BN4%2Fj33Xj0%2BPe%2B7iL%2BUpLwQ%2FBjTYts%2F%2FTpFHaK6IOm76UOoUdcNEIqD2UlPpjZoBZKEnDJAKJJ6epf3%2FR5As%3D
`

If you url decode and Base64 Decode + Inflate it will not contain the xml escaped characters

**Comment by tngan** [comment]
When we parse the `SAMLRequest` in identity provider side, we did url decode then base64 decode + inflate. You can check with following test case, by setting `test` to `test.only` and modify `spmeta.xml` with `&amp;`, then log the context of `extract` from `parseLoginRequest` function in Line 118. 

https://github.com/tngan/samlify/blob/70d1f529858d665f30dd9fc3ea0b84c82e23c59e/test/flow.ts#L108-L123

```
```

By the way, the given metadata is for identity provider, for idp initiated single sign on, it will directly send back the `SAMLResponse` and it must be with HTTP-POST binding.
