### ISSUE TITLE
NPM install fails when building libxmljs-mt

### ISSUE THREAD

**Issue by AdamContois** [tngan/samlify#184]
Hi,

I am trying to run `npm install samlify` but when I do it fails to build, returning back the following error.

> ..\src\xml_text.cc(210): error C2661: 'v8::Function::NewInstance': no overloaded function takes 0 arguments  [C:\User
s\acontois\workspace\ps\ps\node_modules\libxmljs-mt\build\xmljs.vcxproj]

I am using... 
node v10.1.0
node-gyp v3.6.2
npm v5.6.0

Any help here would be appreciated

**Comment by tngan** [comment]
@AdamContois  We can continue the discussion in #129. May I also know which OS version are you using?

**Comment by tngan** [comment]
Confirmed that installation is broken in Node v10 [(FYI)](https://travis-ci.org/tngan/samlify/jobs/393726530). Meanwhile, you may try latest Node.js v8 first.

**Comment by AdamContois** [comment]
@tngan Thank you, Node 8 works fine

**Comment by Shelby-OL** [comment]
Went through about 1 hour of troubleshooting what I thought was a bad setup before realizing this. 100% a Node 10 issue, running Node 8 works fine for me.

**Comment by tngan** [comment]
@Shelby-OL Sorry for the inconvenience, I will create another issue for Node v10 supports.

**Comment by tngan** [comment]
All Node.js v10 related issues will be addressed in the thread #186.
