### ISSUE TITLE
single logout service

### ISSUE THREAD

**Issue by franklinjjeng** [tngan/samlify#185]
Hi @tngan, I'm utilizing your library and loving it.

I was just curious about single logout service. I noticed in issue #170 and #105 there are references that it exists but I can't seem to find anything in the code base to create logout requests through the SP or even accept IdP-initiated requests. I was wondering if you would be able to point me in the direction of them.

Thanks for your time.

**Comment by franklinjjeng** [comment]
Thanks! I appreciate the quick response. This looks to be what I needed, I'll play around with it some.

Also off topic, but wondering if there is a quick way to turn off X509Certificate requirement in the SAMLResponse (I can open a new question/issue if needed)

**Comment by tngan** [comment]
@franklinjjeng There is no option to turn it off right now. I am also considering to make the signature optional for testing use. For feature request, please open a new issue. Thanks.

**Comment by tngan** [comment]
Since this issue is not updated for a while, I will close this first. Please reopen it if needed.

**Comment by franklinjjeng** [comment]
Hi @tngan. I'm having trouble passing both the emailAddress and the sessionIndex in the logout redirect saml response. It seems to be passing the emailAddress without issue, but the sessionIndex is getting left out.

I'm attempting to build the redirect logout request below
```const { context } = sp.createLogoutRequest(idp, 'redirect', { logoutNameID: emailAddress, sessionIndex: sessionIndex });```

I based this off of what I saw in logoutRequestRedirectURL in binding-redirect.ts
```
      rawSamlRequest = libsaml.replaceTagsByValue(libsaml.defaultLogoutRequestTemplate.context, {
        ID: id,
        Destination: base,
        EntityID: metadata.init.getEntityID(),
        Issuer: metadata.init.getEntityID(),
        IssueInstant: new Date().toISOString(),
        NameIDFormat: namespace.format[initSetting.logoutNameIDFormat] || namespace.format.emailAddress,
        NameID: user.logoutNameID,
        SessionIndex: user.sessionIndex,
```

**Comment by 13Nunes** [comment]
I'm waiting for a logout example.

**Comment by aagirusairam** [comment]
@tngan, Does samlify support IDP-logout? If yes, Can you please provide me an example for such. If not, when i can expect it to be a part of samlify release.

**Comment by archerbj** [comment]
@franklinjjeng @tngan It seems samlify is already able to create logout request including `SessionID`. But I still have no idea how to do it. Could you please provide an example of it?

**Comment by franklinjjeng** [comment]
Unfortunately I don't have access to the code base that I built this with, but looking at past conversations, it looks like you need to create a custom template for the sessionId to appear. 

https://samlify.js.org/#/template?id=custom-templates.
https://github.com/tngan/samlify/pull/197#issuecomment-410906826

**Comment by netmiller** [comment]
Does anyone have working esampel for __createLogoutRequest__   or any advise.  I can't  find solution.  My __idp  is  Shibboleth__ instance, but I have not access to check how it should work .

**Comment by netmiller** [comment]
Wondering why is this issue Closed ?  Documentation seems missing this examples etc.
