### ISSUE TITLE
Expose InResponseTo in parseLoginResponse extract

### ISSUE THREAD

**Issue by benbabic** [tngan/samlify#188]
My broader use case is that I want to validate the response to my SP initiated login in a way that guarantees that a response can only be used once. For that I store the login request id provided by  `sp.createLoginRequest` and would like to check that the `InResponseTo` field matches that id. 

Does that sound legit? If so, would it be possible to extract the `InResponseTo` saml field and set it on the result of  `parseLoginResponse`? 

Would you be interested in a PR that does that by adding something like the following to the `parserFormat` options in https://github.com/tngan/samlify/blob/master/src/entity-sp.ts#L93
```typescript
{ localName: 'Response', attributes: ['InResponseTo'] }
```

**Comment by tngan** [comment]
Yes, I am happy to accept the PR.
