### ISSUE TITLE
npm audit reports 5 vulnerabilities

### ISSUE THREAD

**Issue by benbabic** [tngan/samlify#189]
I started working on a PR, and ran npm install, which prompted me to run npm audit which shows some vulnerabilities in the dependencies - see attached [audit.txt](https://github.com/tngan/samlify/files/2175206/audit.txt)

Do you have a strategy around this? Updating the dependencies should work but some of the dependency fixed their vulnerabilities in a major patch.

**Comment by tngan** [comment]
This is being resolved by updating the dependencies with moderate vulnerabilities. Thanks for reporting. See commit 766a290.
