### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by benbabic** [tngan/samlify#191]
Yet another question (sorry about that):
Do you know when the next release is going to be? I haven't found any workarounds for #174 and can't use the last release because of that. 
Is there any plan for a bugfix type release with the fix from https://github.com/tngan/samlify/commit/ddaf5fa2bf89feaf802cc724bdaf0d51825d8df1 or should I use the previous version?

**Comment by tngan** [comment]
@benbabic It's being published (v2.3.8) in npm.
