### ISSUE TITLE
Pre-commit hook

### ISSUE THREAD

**Issue by microadam** [tngan/samlify#193]
Running `yarn install samlify` fails with the following:

`<path to project dir>/node_modules/samlify/.git/hooks/pre-commit: No such file or directory`

Surely this should only be run when developing on the module?

Currently samlify gets removed next time I do anything with yarn, as the `yarn.lock` file doesn't get updated as it thinks the module didn't get installed correctly.

**Comment by tngan** [comment]
@microadam You are right, I remove that postinstall hook.

**Comment by microadam** [comment]
awesome, thank you! If you are able to release a new version with this fix in soon, that would be great!

**Comment by tngan** [comment]
@microadam Please refer to the release note [here](https://github.com/tngan/samlify/releases/tag/v2.4.0-rc1).
