### ISSUE TITLE
Can't pass sessionIndex in sp logout

### ISSUE THREAD

**Issue by franklinjjeng** [tngan/samlify#196]
It looks like I couldn't reopen my closed question from before. Sorry for the duplicate.

Hi @tngan. I'm having trouble passing both the emailAddress and the sessionIndex in the logout redirect saml response. It seems to be passing the emailAddress without issue, but the sessionIndex is getting left out.

I'm attempting to build the redirect logout request below
```const { context } = sp.createLogoutRequest(idp, 'redirect', { logoutNameID: emailAddress, sessionIndex: sessionIndex });```

I based this off of what I saw in logoutRequestRedirectURL in binding-redirect.ts
```
      rawSamlRequest = libsaml.replaceTagsByValue(libsaml.defaultLogoutRequestTemplate.context, {
        ID: id,
        Destination: base,
        EntityID: metadata.init.getEntityID(),
        Issuer: metadata.init.getEntityID(),
        IssueInstant: new Date().toISOString(),
        NameIDFormat: namespace.format[initSetting.logoutNameIDFormat] || namespace.format.emailAddress,
        NameID: user.logoutNameID,
        SessionIndex: user.sessionIndex,
```
I did notice that the namespace is set to SAML:1.1:nameid-format:emailAddress which could be the issue, but I'm not super well versed with the nameid formats.

**Comment by franklinjjeng** [comment]
In researching the package further I'm seeing that the default logout template doesn't appear to include the sessionIndex
```const defaultLogoutRequestTemplate = {
    context: '<samlp:LogoutRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="{ID}" Version="2.0" IssueInstant="{IssueInstant}" Destination="{Destination}"><saml:Issuer>{Issuer}</saml:Issuer><saml:NameID SPNameQualifier="{EntityID}" Format="{NameIDFormat}">{NameID}</saml:NameID></samlp:LogoutRequest>',```

I'll see if I can figure out how it's supposed to be structured

**Comment by franklinjjeng** [comment]
I created a PR #197 that should take care of this. I added `<samlp:SessionIndex>{SessionIndex}</samlp:SessionIndex>` into the `defaultLogoutRequestTemplate` and now it's showing up in my tests SAML calls. Let me know what tweaks I need to make or if SessionIndex is not always expected and only need to call it conditionally.

**Comment by franklinjjeng** [comment]
As tngan mentioned in the PR #197, you can use a custom template to handle this.

> You can use [custom template](https://samlify.js.org/#/template?id=custom-templates) to handle this use case.

Just make sure to follow the function sig values for createLogoutRequest.

**Comment by franklinjjeng** [comment]
With the new template, the ID, Destination, Issuer, IssueInstant, etc don't change and need to be included in the customTagReplacement function.

**Comment by franklinjjeng** [comment]
@tngan I saw that the PR was accepted. Do you have a timeline on your next version publish? If you have no plans on making it soon, I can try to make side version of this for the time being. Thanks!

**Comment by tngan** [comment]
2.4.0-rc2 is released
