### ISSUE TITLE
help wanted with samlify custom template post binding

### ISSUE THREAD

**Issue by tiagoernst** [tngan/samlify#199]
Hello I am trying to use the custom template attribute for a my saml request but i don't understand what is the purpose or how should I implement the replaceTagFromTemplate ,the example function in the documentation : 
"When you apply your own template, remember to do custom tag replacement when you send out the request. replaceTagFromTemplate is just the name here to illustrate but it's not fixed."
I logged the loginRequestTemplate and noticed it is only the template on xml encoding, do I have to replace the tags where i wanted the variables from samlify (ex : 'IssueIstant="{IssueInstant}" ' should i replace the var between the brackets) or is it somehting else ? 
Lastly i wanted the keep a part of the default request  (signatures values and digest too) without putting them on the template, or if I needed to put them (in the template) that they'll be generated by samlify because i don't know how to do it.  
Sorry if I wasn't clear enough it's my first time with SAML :p

**Comment by tngan** [comment]
@tiagoernst There is a test case telling how to make a custom template of saml request with post binding. You can define your own template and do the tag replacement in the callback of `createLoginRequest`.

https://github.com/tngan/samlify/blob/031cafdbb068dd32c4ec247bf829ab0598701046/test/flow.ts#L184-L202

**Comment by tiagoernst** [comment]
Thanks ! I ended up creating two SP's to have the values of signatures from the "default" request and replaced them in the template request ^^
