### ISSUE TITLE
JDK required at JAVA_HOME or in path to compile helper

### ISSUE THREAD

**Issue by pwilletts** [tngan/samlify#203]
Hello,
Having an issue when parsing SAML Response.  My express.js code looks like the below to received the response:

router.post('/login/saml/sso/longhorn', function(req, res, next){
  sp.parseLoginResponse(idp, 'post', req)
    .then(parseResult => {
      console.log(parseResult);
    })
    .catch(console.error)
  //res.redirect('https://mernapdevv.nhrmc.local');
})

When the response is routed, the parse fails with this error straight from the command line.

> tops-server@0.0.0 start D:\Longhorn\longhorn-server
> node ./bin/www

Connected
Found Java 10.0.2 at C:\Program Files\Java\jdk-10.0.2
It's a JDK!
here
JDK required at JAVA_HOME or in path to compile helper

I have ensured I had the Java JDK in the path variable , but am still receiving the error.  What am I missing or most likely misunderstanding?

**Comment by tngan** [comment]
https://github.com/nikku/node-xsd-schema-validator/blob/fac2fb3f9ee6d1c8bbc993a2ba857a01d44b1f79/lib/validator.js#L9-L25

The error is thrown in line 25. 

If you are not set `JAVA_HOME`, the validator assumes you have  put them in PATH, so try to run `java` and `javac` to see if it is correctly set.

**Comment by tngan** [comment]
@pwilletts Any feedback ?

**Comment by pwilletts** [comment]
Yes, was able to get it working.  the JDK was there, system wasn't able to see it.

**Comment by SantoshSKhavekar** [comment]
Hi ..I am also facing same  issue .when I checked my JAVA_HOME it is pointing my JDK but still i am getting same issue.I am not understanding why it still coming for me?

Please help me here

**Comment by SantoshSKhavekar** [comment]
I have solved my Issue by adding these lines,
`        ENV JAVA_HOME=/usr/lib/jvm/java-1.7-openjdk
	 RUN export JAVA_HOME
	 ENV PATH="$JAVA_HOME/bin:${PATH}"   
	 RUN java -version
	 RUN javac -version`

In my case, javac is not running inside docker container.Now fixed this issue.
