### ISSUE TITLE
Error: spawn java ENOENT

### ISSUE THREAD

**Issue by vinhtran-nwl** [tngan/samlify#204]
Hello,

Not sure if anyone else has had this issue but i've got a pretty interesting problem. I was able to get samlify working great on my local running OS X and I started deploying this to a test server on Centos 7.

On the Centos 7 server, I'm able to get the site Set up but when I do a SAML Post to the ACS url I get the following error

      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

I was able to track this down to the entity.js file in the samlify module and it appears that the body.call line is throwing an exception when it's invoking a child process.

Has anyone else had this issue before? I've set it up on a AWS AMI for the hell of it and it's giving the same results and I've scaled my code to the bare minimum to avoid any complexity in testing. It just seems that I'm missing a dependency or something when invoking that call.

Other then that the library has been working great. Would love to be able to deploy it to our test server to keep this project on track.

Any help is appreciated, Thanks!

**Comment by tngan** [comment]
@vinhtran-nwl Please take a look on [how to install Java JRE in centos 7](https://www.digitalocean.com/community/tutorials/how-to-install-java-on-centos-and-fedora). If it's still not working, I need to setup the environment for testing later on.

**Comment by tngan** [comment]
@vinhtran-nwl Any feedback ?

**Comment by vsh13** [comment]
I had similar error. If the server is behind proxy have needs to be given proxy url in of the dendencies @tngan. Can this be setup as a config.

**Comment by haoleman** [comment]
I had similar problems with `Error: spawn java ENOENT`. Giving node more memory via ``--max-old-space-size`` seems to help. Not sure when this will be out in the wild, but this PR solved for me:
[#273](https://github.com/tngan/samlify/pull/273)

**Comment by tngan** [comment]
v2.6.0 is released on npm. Feel free to reopen if needed.
You can use another validator now, or even customise your own.
