### ISSUE TITLE
`npm i samlify` installs old JS code for 2.4.0-rc2 release

### ISSUE THREAD

**Issue by nlfiedler** [tngan/samlify#205]
Just tried this and found that after running `npm i samlify`, the compiled JS code in the `build` directory appears to be out of date with the TS source. Is this a problem with the published package? Another thing I noticed is that the timestamps for many of the files are from 1985. Could that be related?

**Comment by nlfiedler** [comment]
I should have mentioned the versions, in case it matters: Node.js LTS (8.12.0) and npm 6.4.1. Yarn is at 1.9.4. Everything installed using Homebrew on macOS. I've reproduced this on two systems.

**Comment by tngan** [comment]
Please try on the latest version v2.4.0-rc4, to see if it is being resolved.
