### ISSUE TITLE
ERR_FAIL_TO_VERIFY_STE_SIGNATURE

### ISSUE THREAD

**Issue by pwilletts** [tngan/samlify#213]
My app is configured as SP for our Okta IDP.  What does this message indicate?  Using a SAML extension in Chrome I able to see the SAML response.  My code is below.  

```js
const idp = saml.IdentityProvider({
  metadata: fs.readFileSync('../saml/metadata.xml')
})

const sp = saml.ServiceProvider({
  metadata: fs.readFileSync('../saml/metadata.xml')
})

/* GET home page. */
router.get('/', function(req, res, next) {
  const { id, context } = sp.createLoginRequest(idp, 'redirect');
  return res.redirect(context);
});

router.post('/login/saml/sso/longhorn', function(req, res, next) {
  sp.parseLoginResponse(idp, 'post', req)
  .then(parseResult => {
    console.log(parseResult);
  })
  .catch(console.error);
})
```

**Comment by tngan** [comment]
https://github.com/tngan/samlify/blob/e3f37c4fb52c961e8667ee50e0398d5e2d19ebf2/src/flow.ts#L164-L174

That means the signature verification is incorrect. If the response is signed then encrypted (optional), it will go through the above section. Firstly, it will perform a decryption (if has) before the above mentioned block, then it will perform the signature verification.

**Comment by tngan** [comment]
@pwilletts Any feedback ?

**Comment by tngan** [comment]
This issue was not active for 3 months and the code base was changed. I have to closed it first and please reopen if needed.
