### ISSUE TITLE
Is it impossible to use with angular?

### ISSUE THREAD

**Issue by leandrovieiras** [tngan/samlify#214]
I really liked this project, but I can't use it with angular.
Is there a way to use it with angular?
How?

Thank you.

**Comment by tngan** [comment]
@leandrovieiras Short answer is yes. One of our users has written a blog post about how to set up SAML based SSO with samlify and angular.js, you may want to take a look.

https://www.codeproject.com/Articles/1248145/How-to-use-SAML-in-an-Angular-JS-Single-Page-Appli

**Comment by leandrovieiras** [comment]
@tngan 
Thanks for reply! I tryed this tutorial but for my app, I have to redirect to SAML provider using TypeScript.
I saw #158 and tryed to implement as an example.

Here's my code:

login.component.ts

`
import { Component, OnInit, Inject } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { ServiceProvider } from 'samlify/src/entity-sp';
import { IdentityProvider } from 'samlify/src/entity-idp';

@Component({
   selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})

export class LoginComponent implements OnInit {
    constructor(
        private route: ActivatedRoute,
        private router: Router
     ) { }

    ngOnInit() {
        this.saml();
    }

    protected saml(): void {
        let spXML: any;
        let idpXML: any;
        let samlURL: any;

        const spReader = new FileReader();
        const idpReader = new FileReader();

        spReader.readAsText(new File([''], '../assets/metadata/sp-metadata.xml'));
        spXML = spReader.result;

        idpReader.readAsText(new File([''], '../assets/metadata/idp-metadata.xml'));
        idpXML = spReader.result;

        const sp = new ServiceProvider({
          metadata: spXML
        });

        const idp = new IdentityProvider({
          metadata: idpXML
        });

        const { id, context } = sp.createLoginRequest(idp, 'redirect');

        samlURL = context;

        this.router.navigate(samlURL);
      }
}
`

So, when I compiled using ` ng serve `, I got this error:

ERROR in node_modules/samlify/src/extractor.ts(221,63): error TS2339: Property 'nodeValue' does not exist on type 'SelectedValue'.
  Property 'nodeValue' does not exist on type 'string'.
node_modules/samlify/src/extractor.ts(245,77): error TS2339: Property 'value' does not exist on type 'SelectedValue'.
  Property 'value' does not exist on type 'string'.
node_modules/samlify/src/extractor.ts(254,74): error TS2339: Property 'nodeValue' does not exist on type 'SelectedValue'.
  Property 'nodeValue' does not exist on type 'string'.
node_modules/samlify/src/extractor.ts(261,74): error TS2339: Property 'value' does not exist on type 'SelectedValue'.
  Property 'value' does not exist on type 'string'.
node_modules/samlify/src/extractor.ts(334,70): error TS2339: Property 'value' does not exist on type 'SelectedValue'.
  Property 'value' does not exist on type 'string'.
node_modules/samlify/src/extractor.ts(356,42): error TS2339: Property 'nodeValue' does not exist on type 'SelectedValue'.
  Property 'nodeValue' does not exist on type 'string'.
node_modules/samlify/src/libsaml.ts(354,25): error TS2345: Argument of type 'SelectedValue' is not assignable to parameter of type 'Node'.
  Type 'string' is not assignable to type 'Node'.
node_modules/samlify/src/libsaml.ts(358,51): error TS2339: Property 'parentNode' does not exist on type 'SelectedValue'.
  Property 'parentNode' does not exist on type 'string'.
node_modules/samlify/src/libsaml.ts(360,25): error TS2345: Argument of type 'SelectedValue' is not assignable to parameter of type 'Node'.
  Type 'string' is not assignable to type 'Node'.
node_modules/samlify/src/libsaml.ts(384,87): error TS2339: Property 'firstChild' does not exist on type 'SelectedValue'.
  Property 'firstChild' does not exist on type 'string'.
node_modules/samlify/src/libsaml.ts(514,54): error TS2345: Argument of type 'SelectedValue' is not assignable to parameter of type 'Node'.
  Type 'string' is not assignable to type 'Node'.
node_modules/samlify/src/libsaml.ts(559,43): error TS2345: Argument of type 'SelectedValue' is not assignable to parameter of type 'Node'.
  Type 'string' is not assignable to type 'Node'.

Is it possible fix this errors?

Cheers

**Comment by tngan** [comment]
In fact, you don't need to construct yourself, you can just initialize the instance as a function.

```ts
import { IdentityProvider, ServiceProvider } from 'samlify';

const idp = IdentityProvider(...idpProps);
const sp = ServiceProvider(...spProps);
```

Can you setup a sample repo ?

**Comment by leandrovieiras** [comment]
I don't have a repo because I cant turn this project public.
But, how can I set my Identity XML an Service Provider XML in this solution?

**Comment by tngan** [comment]
I mean you can create a sample angular app, and generate a sample metadata without your business secret.

`But, how can I set my Identity XML an Service Provider XML in this solution?` 

I don't understand your question. Please explain further. Thanks.

**Comment by leandrovieiras** [comment]
Hi @tngan.
After a lot of trying, It's working now!
Thanks fot your support!

**Comment by adil-h** [comment]
Hello @leandrovieiras,

Can you share the solution you found please? I'm trying to do the same, and I'm still strugling with those errors. (xpath , crypto, nodeValue in libsaml.ts,...).
if you can share an sample of the configuration with all dependencies (without business logic), it will be perfect.

Thank you for your help.

**Comment by Ederson01** [comment]
Hello @leandrovieiras
can you please share the complete solution?
I´m using node v10.15.0
angular : "7.0.0"

I´m having error.
`
ERROR in ./node_modules/node-rsa/src/NodeRSA.js
Module not found: Error: Can't resolve 'constants' in 'C:\dev\app-sso\node_modules\node-rsa\src'
ERROR in ./node_modules/node-rsa/src/encryptEngines/io.js
Module not found: Error: Can't resolve 'constants' in 'C:\dev\app-sso\node_modules\node-rsa\src\
encryptEngines'
ERROR in ./node_modules/node-rsa/src/encryptEngines/node12.js
Module not found: Error: Can't resolve 'constants' in 'C:\dev\app-sso\node_modules\node-rsa\src\
encryptEngines'
ERROR in ./node_modules/node-rsa/src/schemes/pkcs1.js
Module not found: Error: Can't resolve 'constants' in 'C:\dev\app-sso\node_modules\node-rsa\src\
schemes'
ERROR in ./node_modules/@authenio/xml-encryption/lib/xmlenc.js
Module not found: Error: Can't resolve 'crypto' in 'C:\dev\app-sso\node_modules\@authenio\xml-en
cryption\lib'
ERROR in ./node_modules/node-rsa/src/NodeRSA.js
Module not found: Error: Can't resolve 'crypto' in 'C:\dev\app-sso\node_modules\node-rsa\src'
ERROR in ./node_modules/node-rsa/src/utils.js
Module not found: Error: Can't resolve 'crypto' in 'C:\dev\app-sso\node_modules\node-rsa\src'
ERROR in ./node_modules/node-rsa/src/encryptEngines/io.js
Module not found: Error: Can't resolve 'crypto' in 'C:\dev\app-sso\node_modules\node-rsa\src\enc
ryptEngines'
ERROR in ./node_modules/node-rsa/src/encryptEngines/node12.js
Module not found: Error: Can't resolve 'crypto' in 'C:\dev\app-sso\node_modules\node-rsa\src\enc
ryptEngines'
ERROR in ./node_modules/node-rsa/src/encryptEngines/encryptEngines.js
Module not found: Error: Can't resolve 'crypto' in 'C:\dev\app-sso\node_modules\node-rsa\src\enc
ryptEngines'
ERROR in ./node_modules/node-rsa/src/libs/jsbn.js
Module not found: Error: Can't resolve 'crypto' in 'C:\dev\app-sso\node_modules\node-rsa\src\lib
s'
ERROR in ./node_modules/node-rsa/src/libs/rsa.js
Module not found: Error: Can't resolve 'crypto' in 'C:\dev\app-sso\node_modules\node-rsa\src\lib
s'
ERROR in ./node_modules/node-rsa/src/schemes/pss.js
Module not found: Error: Can't resolve 'crypto' in 'C:\dev\app-sso\node_modules\node-rsa\src\sch`

**Comment by hackintoshsa** [comment]
@leandrovieiras  Can you please share the solution .... i want to run samlify on Angular

**Comment by hackintoshsa** [comment]
@tngan do you have a solution for this on angular ?

**Comment by kelcoding** [comment]
Did anyone come up with a resolution for this ?

**Comment by androidparth90** [comment]
unfortunately no solution yet

**Comment by tngan** [comment]
@kelcoding @androidparth90 https://www.codeproject.com/Articles/1248145/How-to-use-SAML-in-an-Angular-JS-Single-Page-Appli

This article was written by one of the samlify users two years ago, you may want to take it as a reference. 
In fact, the major API of samlify doesn't change between v2.3.x and v2.7.x.
