### ISSUE TITLE
Java dependency

### ISSUE THREAD

**Issue by eugene1g** [tngan/samlify#216]
Hi,

After a brief code audit I think this library could become the most mature SAML implementation in NodeJS and was excited to try to integrate it into our projects. However, the lib currently depends on `javac`, which is a non-starter for many pure-JS/TS shops that try to keep libs/deployments small. Seems like a massive hammer to bring into the equation to do validation. Are there any plans to drop java as a hard dependency or provide a mock substitute if I understand the validation risks and willing to bear them?

**Comment by eugene1g** [comment]
@tngan I applaud your professionalism - my comment could have easily been interpreted as "you're doing it wrong!", and you took it in the good spirit it was intended. Thank you.

Validating user inputs is critical for a secure system, _especially_ in the authentication layer. Validating the XML structure may seem futile or useless as it can't give an attack vector, but just last week there was a vulnerability in a popular NodeJS SAML project which allowed authentication bypass because of an issue in the validation mechanism (https://snyk.io/vuln/SNYK-JS-PASSPORTSAML-72411) and this has serious implications for applications opened to the internet.

While testing this library, I wanted to avoid creating a fork that will fall behind over time, and did not want to install Java. The path I chose was to 'monkey-patch' the dependency tree with the `resolutions` capability in Yarn. Specifically, I overrode the dependency of `@passify/xsd-schema-validator` to use a mock validator function like so -
```json
  // package.json
  "resolutions": {
    "samlify/@passify/xsd-schema-validator": "./fake-validator"
  }
```
```js
// ./fake-validator/index.js
function FakeValidator() {}
FakeValidator.prototype.validateXML = function(input, ref, cb) {
  cb(null, { valid: true });
};

module.exports = FakeValidator;
```
This has the same 'bad bad bad' impact of skipping validation altogether and no one should be using it in production unless they understand the risks. However, it works well-enough for to continue testing while I decide a permanent solution to the validation issue.

My main goal was to "+1" the idea of carving out validation into an _optional_ dependency, as I expect it would make the library accessible to a much broader audience (especially in the age of micro-services and containers). I am satisfied that this goal was accomplished, so feel free to close this issue/comment.

**Comment by tngan** [comment]
@eugene1g Thanks for your input. I will consider to make a reference for your approach in documentation later on.
