### ISSUE TITLE
Use only IdP WantAuthnRequestsSigned to enable AuthNRequest signature

### ISSUE THREAD

**Issue by pavb74** [tngan/samlify#221]
Hi

I am currently implementing a service which use different Idp to automatically logged the users depending of their domain or origin. These Idp have different requirements on the request signatures.

Currently it is not possible because we check the consistency of the Idp and sp metadata and I don't want to manage multiple metadata for my sp.

method: createLoginRequest
```
if (this.entityMeta.isAuthnRequestSigned() !== idp.entityMeta.isWantAuthnRequestsSigned()) {
    throw new Error('ERR_METADATA_CONFLICT_REQUEST_SIGNED_FLAG');
}
```

To bypass this check and make it works I have added this before generating the login request.
```
// Adapt Sp to the Idp configuration
serviceProvider.entityMeta.isAuthnRequestSigned = () => idp.entityMeta.isWantAuthnRequestsSigned();
```

I am wondering if it won't be easier to sign the request if it is require by the Idp without checking the sp metadata and just add a test in this case to check if the private key of the sp has been provided.

Thanks a lot

Pierre-André

**Comment by tngan** [comment]
@pavb74 I would say the original design of entity constructor is a little bit of overkilling. I also keep rethinking if there is a way to simplify the flow, and make it more clear and easy to use.

**Comment by tngan** [comment]
@pavb74 I would close this issue first.

**Comment by pavb74** [comment]
Hi 

Sorry I didn't see your comment on October, Thanks for your response.
We use your lib every day, it works great thanks !

PA

**Comment by tngan** [comment]
@pavb74 Good to know, thanks.
