### ISSUE TITLE
Signed 'Response' must include the certificate?

### ISSUE THREAD

**Issue by eugene1g** [tngan/samlify#223]
Hi,

My iDP provides signed responses, but the response body does not include the X509 certificate. I have their certificate in both the metadata file, and as an external PEM file, and would like to use it for verifying the signature.

In the current implementation, `postFlow` defines parameters to be used by `verifySignature` at https://github.com/tngan/samlify/blob/a70665489617acecd1f7f70ea61a791e6ecb2a6c/src/flow.ts#L131-L134. It is not possible to inject custom properties here (e.g. cannot add `keyFile`), so the only way to instruct it to use a certificate is via the `cert` property.  The `cert` property is correctly used by `verifySignature` but it also expects the Response to include an embedded X509 as per https://github.com/tngan/samlify/blob/a70665489617acecd1f7f70ea61a791e6ecb2a6c/src/libsaml.ts#L377-L382 In my case the Response does not have the certificate, and this triggers runtime error `TypeError: Cannot read property 'firstChild' of undefined`

I think a 'quick' solution would be to either accept optional `keyFile` as a parameter for `sp.parseLoginResponse` or forego checking for X509 presence in the Response when it is provided via the `cert` property (but I worry if this has any security implications).

**Comment by tngan** [comment]
Hi @eugene1g, this check is for the use case (at least one of our uses has such use case) that IDP uses rolling certificates for signature, and the response would have signature with one of the certificates, so you can consider it's just a whitelist checking for such use case.

In fact, the signature specification is not under SAML standard but XML's one. I took some time to have a look at the RFC 3275. Here is the result:

```xml
 <Signature ID?>
  <SignedInfo>
    <CanonicalizationMethod/>
    <SignatureMethod/>
    (<Reference URI? >
      (<Transforms>)?
      <DigestMethod>
      <DigestValue>
    </Reference>)+
  </SignedInfo>
  <SignatureValue>
(<KeyInfo>)?
(<Object ID?>)*
</Signature>
```

Therefore, the number of `KeyInfo` can be zero. In addition, the `X509Data` come with it, if you response does include `KeyInfo`, you need to follow the specification.

Schema Definition:

```xml
<element name="KeyInfo" type="ds:KeyInfoType"/>
<complexType name="KeyInfoType" mixed="true">
  <choice maxOccurs="unbounded">
    <element ref="ds:KeyName"/>
    <element ref="ds:KeyValue"/>
    <element ref="ds:RetrievalMethod"/>
    <element ref="ds:X509Data"/>
    <element ref="ds:PGPData"/>
    <element ref="ds:SPKIData"/>
    <element ref="ds:MgmtData"/>
    <any processContents="lax" namespace="##other"/>
    <!-- (1,1) elements from (0,unbounded) namespaces -->
  </choice>
  <attribute name="Id" type="ID" use="optional"/>
</complexType>
```

To conclude, please feel free to submit a PR for the enhancement.

https://github.com/tngan/samlify/blob/a70665489617acecd1f7f70ea61a791e6ecb2a6c/src/libsaml.ts#L369

I suggest to move the variable declaration of selectedCert under the above line and assign this to as default value before going into the whitelist check. In fact, I am rewriting the logic of signature checking from looping basis into more declarative.

**Comment by eugene1g** [comment]
Thanks for the tip! It's a quick change so I plan to do a PR this weekend

**Comment by tngan** [comment]
Sounds good.

**Comment by tngan** [comment]
For the use case with rolling certificate, I keep this restriction when there are more than one certificates specified in metadata for now, since it is not efficient to blindly loop through all certificates specified in metadata to validate the signature in response without specifying which certificate is actually selected.

For single certificate, I relax this restriction based on the specification.
