### ISSUE TITLE
Extreme slowdown after upgrading to version 2.4.0

### ISSUE THREAD

**Issue by kiejo** [tngan/samlify#224]
Hi,
I'm currently in the process of upgrading from version 2.3.7 to 2.4.0, but my SSO related tests now run in 16 seconds vs less than a second before. I saw that there were some large changes in the latest release and Java was added as a dependency, but is such an extreme slowdown expected or is there something I can do to fix it?

**Comment by jonathanperret** [comment]
The Java dependency is a showstopper for us for deployment reasons. In any case, I doubt the performance of validation can improve much considering you're spawning an external process to process each SAML login.

Maybe something like https://www.npmjs.com/package/cxsd (or anything that generates plain JS from XSD) could be worth investigating?

**Comment by D-32** [comment]
@jonathanperret the Java dependency was a problem for me too, although it was just javac (compiler) that isn't available on my server. If you can run `java`, just not `javac`, using my fork might help. I basically just provide a compiled variant of the java code inside node-xsd-schema-validator (also had to fork that repo).

**Comment by jonathanperret** [comment]
@D-32 It's true that the first block we encountered was the lack of `javac` in our CI environment, so your approach does work around that issue. But the requirement for `java` is still very annoying, and  the performance issue is a blocker for us.

**Comment by kiejo** [comment]
Thanks @jonathanperret for providing more context. It definitely sounds like `spawning an external process to process each SAML login` is what's causing the performance degradation.

Making the validation process pluggable sounds like it could help solve the performance issue if it enables users to use `libxmljs` as before.

Overall I'm not sure if having such bad performance is a good default for the library as I can imagine this being a blocker for many projects. Unfortunately I don't know about the specific issues the previous solution caused and I assume there were good reasons to move to the Java based approach.

**Comment by tngan** [comment]
@kiejo You may also want to checkout this discussion thread. https://github.com/tngan/samlify/issues/216

**Comment by tngan** [comment]
I will close it first since there is an option to get rid of this issue from external schema validator.
