### ISSUE TITLE
Can't install it on Windows

### ISSUE THREAD

**Issue by ErickXavier** [tngan/samlify#240]
Can't install it using windows, because of the need of the 'make' command line.

Trying through yarn:
`$ yarn add samlify
yarn add v1.13.0
warning package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning express-html@0.0.1: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error C:\Users\erick\Projects\myproject\node_modules\samlify: Command failed.
Exit code: 1
Command: make validator
Arguments:
Directory: C:\Users\erick\Projects\myproject\node_modules\samlify
Output:
'make' is not recognized as an internal command
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

Trying through NPM:
`$ npm i samlify
npm WARN rm not removing C:\Users\erick\Projects\myproject\node_modules\.bin\semver.cmd as it wasn't installed by C:\Users\erick\Projects\myproject\node_modules\semver
npm WARN rm not removing C:\Users\erick\Projects\myproject\node_modules\.bin\semver as it wasn't installed by C:\Users\erick\Projects\myproject\node_modules\semver
samlify@2.5.0-rc1 preinstall C:\Users\erick\Projects\myproject\node_modules\samlify
make validator
'make' is not recognized as an internal command
npm WARN express-html@0.0.1 No repository field.
npm WARN express-html@0.0.1 No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! samlify@2.5.0-rc1 preinstall: `make validator`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the samlify@2.5.0-rc1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\erick\AppData\Roaming\npm-cache\_logs\2019-01-30T16_31_30_430Z-debug.log`

**Comment by sylvainlap** [comment]
I got the same error. Is there a way to still install samlify on Windows ?

**Comment by ErickXavier** [comment]
@sylvainlap great, thanks! :)

For now, my solution was to install an older version.

**Comment by tngan** [comment]
@sylvainlap @ErickXavier I haven't tested it but see if you can install bash shell on windows.

https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by ErickXavier** [comment]
> @sylvainlap @ErickXavier I haven't tested it but see if you can install bash shell on windows.
> 
> https://docs.microsoft.com/en-us/windows/wsl/install-win10

I tried with multiple shells, including Git Bash, Ubuntu shell from Windows Store, PowerShell, etc.

**Comment by tngan** [comment]
@ErickXavier How about cygwin ?

**Comment by vdveer** [comment]
@ErickXavier That worked for the Windows users in our team.

**Comment by tngan** [comment]
@vdveer Thanks for your feedback, let me close this first and feel free to reopen if needed.

**Comment by ErickXavier** [comment]
> @vdveer Thanks for your feedback, let me close this first and feel free to reopen if needed.

@tngan yeah, for me too, after some windows updates. Thanks ;)
