### ISSUE TITLE
How to add  a AuthnContextClassRef ?

### ISSUE THREAD

**Issue by puneetmakkar** [tngan/samlify#241]
I want to have the following authentication context in SAML request 
 
<saml2p:RequestedAuthnContext Comparison="minimum">
    <saml2:AuthnContextClassRef xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">https://login.norton.com/sso/saml_2.0_profile/show_update_profile_email</saml2:AuthnContextClassRef>
  </saml2p:RequestedAuthnContext>

Is there a way to achieve it via config?

**Comment by tngan** [comment]
Yes, you can apply custom template for SAML request, and apply it to the , you can either hard-code the `saml2p:RequestedAuthnContext` section or inject it at runtime via the callback (3rd argument) in `createLoginRequest` function.

Documentation: https://samlify.js.org/#/template

**Comment by tngan** [comment]
@puneetmakkar Have you resolved this ?

**Comment by puneetmakkar** [comment]
Yes! Thank you
