### ISSUE TITLE
How to generate SAML Response for Idp

### ISSUE THREAD

**Issue by jerryOkafor** [tngan/samlify#242]
I need to implement Idp for a project I am working, I can not see how to generate SAML response. Is it not possible with this module.

**Comment by tngan** [comment]
Hi @jerryOkafor, you may want to check the examples in test file, and `flow.ts` includes a lot of common use cases, from building a simple login request to a complete sp/idp initiated sign on and logout with redirect/post binding.

Here is for you.

https://github.com/tngan/samlify/blob/70d1f529858d665f30dd9fc3ea0b84c82e23c59e/test/flow.ts#L200-L204

**Comment by jerryOkafor** [comment]
This is fine, what if you do not have the details of the SP?

**Comment by tngan** [comment]
@jerryOkafor If you do not have the detail of the SP, where will you send the response to ? Also, some information in the response is given by the SP detail. In other words, if you don't know any detail about SP, what is the usage of that response ?

**Comment by tngan** [comment]
@jerryOkafor Did you resolve this ?

**Comment by tngan** [comment]
@jerryOkafor  Since there is no feedback for 3 months, I would close it and feel free to reopen if you have further question. :)
