### ISSUE TITLE
Assertion signature invalid

### ISSUE THREAD

**Issue by morgan-monger** [tngan/samlify#252]
# Summary
When creating a SAML response for a HTTP-POST binding in `IdentityProvider.createLoginResponse()`, the assertion signature block is missing a required transformation algorithm and results in a signature validation error in a service provider. Adding a reference to the assertion signature code allows transformation algorithms to be honored from a service provider entity.

# Details
The transformation algorithms are passed properly for message signatures:
https://github.com/tngan/samlify/blob/master/src/libsaml.ts#L278
https://github.com/tngan/samlify/blob/master/src/binding-post.ts#L160

The transformation algorithms are passed from opts.transformationAlgorithms instead of the default values:
https://github.com/tngan/samlify/blob/master/src/libsaml.ts#L270

The transformation algorithms are not passed for the assertion signature:
https://github.com/tngan/samlify/blob/master/src/binding-post.ts#L140-L148

When the transformation algorithms are not passed, xml-crypto uses a default that excludes a required transformation algorithm. The same transformationAlgorithm variable references should be applied to assertion signature as the working message signature code. 

## Service Provider Stack Trace
Here is a stack trace from a Grails Spring Security SAML application which highlights the missing transformation algorithm error:
```
Caused by: org.opensaml.common.SAMLException: Response doesn't have any valid assertion which would pass subject validation
        at org.springframework.security.saml.websso.WebSSOProfileConsumerImpl.processAuthenticationResponse(WebSSOProfileConsumerImpl.java:229)
        at org.springframework.security.saml.SAMLAuthenticationProvider.authenticate(SAMLAuthenticationProvider.java:87)
        ... 52 common frames omitted
Caused by: org.opensaml.xml.validation.ValidationException: Transforms did not contain the required enveloped transform
        at org.opensaml.security.SAMLSignatureProfileValidator.validateTransforms(SAMLSignatureProfileValidator.java:242)
        at org.opensaml.security.SAMLSignatureProfileValidator.validateSignatureImpl(SAMLSignatureProfileValidator.java:86)
        at org.opensaml.security.SAMLSignatureProfileValidator.validate(SAMLSignatureProfileValidator.java:56)
        at org.springframework.security.saml.websso.AbstractProfileBase.verifySignature(AbstractProfileBase.java:264)
        at org.springframework.security.saml.websso.WebSSOProfileConsumerImpl.verifyAssertionSignature(WebSSOProfileConsumerImpl.java:419)
        at org.springframework.security.saml.websso.WebSSOProfileConsumerImpl.verifyAssertion(WebSSOProfileConsumerImpl.java:292)
        at org.springframework.security.saml.websso.WebSSOProfileConsumerImpl.processAuthenticationResponse(WebSSOProfileConsumerImpl.java:214)
        ... 53 common frames omitted
```

## SAML Response Snippets
The difference between the two snippets is that `<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />` is missing from the failing response.
### Failing
```xml
<saml:Assertion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_1e930f6f-3e7d-4cca-865e-a8616b4fcb0d" Version="2.0" IssueInstant="2019-03-20T11:05:21.314Z" >
	<saml:Issuer>https://localhost:3001/saml/auth</saml:Issuer> 
		<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
			<ds:SignedInfo>
				<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
				<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
				<ds:Reference URI="#_22094a0e-604a-4790-a5c5-c57cd3b15a1f">
					<ds:Transforms>
						<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
					</ds:Transforms>
					<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
					<ds:DigestValue>rDidFxSDARJTMZjEaPO3L+3PHDxROyb20wIX+dw4ZfA=</ds:DigestValue>
				</ds:Reference>
			</ds:SignedInfo>
```

### Working
```xml
<saml:Assertion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_1e930f6f-3e7d-4cca-865e-a8616b4fcb0d" Version="2.0" IssueInstant="2019-03-20T12:01:19.477Z" >
	<saml:Issuer>https://localhost:3001/saml/auth</saml:Issuer>
		<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
			<ds:SignedInfo>
				<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
				<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
				<ds:Reference URI="#_1e930f6f-3e7d-4cca-865e-a8616b4fcb0d">
					<ds:Transforms>
						<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
						<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
					</ds:Transforms>
					<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
					<ds:DigestValue>S9ymlmlgnNHV6fvApn9Dn25Wtt04t10IWzYHufj6Rg8=</ds:DigestValue>
				</ds:Reference>
			</ds:SignedInfo>
```

# Proposed Solution
In the long run, changing variable reference `opts.transformationAlgorithms` to `transformationAlgorithm` in `libsaml.constructSAMLSignature()` will use the same default algorithms for assertion and message signatures. Unfortunately, this change would break several unit tests and may have other side effects for consumers. In the short term, adding `transformationAlgorithms: spSetting.transformationAlgorithms` to `postBinding.base64LoginResponse()` will be sufficient for a consumer to specify the transformation algorithms for assertion and message signatures. I also suggest updating the signed-saml-response.md file to highlight the use of the `transformationAlgorithms` property when signature validation fails for service providers.

**Comment by tngan** [comment]
@morgan-monger I will take a look very soon. Thanks for your support!

**Comment by tngan** [comment]
PR is merged. It's scheduled to release with v2.5.

**Comment by morgan-monger** [comment]
Thank you very much for merging the PR. Would it be possible to get a new 2.5 RC so we can start using the change ahead of the official 2.5 release?

**Comment by tngan** [comment]
@morgan-monger  I was out of town since last week. I will try to make a release within this week.
