### ISSUE TITLE
doc Okta : 

### ISSUE THREAD

**Issue by fas3r** [tngan/samlify#255]
Hello, 

any chance to get the doc okta updated ? 

https://github.com/tngan/samlify/blob/master/docs/okta.md

Also where do I get the SP xml metadata for okta ? 

they are just providing the IDP xml file. Would not be simple to just provide the url to the metadata or the endpoint of SingleSignOn like passport-saml ?

Thanks

**Comment by tngan** [comment]
@fas3r Oh, I didn't see you have created another ticket, let me move the comment in #254 here.

It can be done, you can create the metadata yourself (https://samlify.js.org/#/sp), or use parameter for configuration of your service provider.

Example:

https://github.com/authenio/react-samlify/blob/d6b294be215b1c824898175a9d91adc9703325c6/middleware/index.ts#L19-L33

If we do provide the url to the metadata and we fetch the metadata for you, next time when the metadata get changed (supposed it is not changed frequently), it will accept it because it always trust the source url.

Metadata is like a contract that agreed by both service and identity provider, so we think the consumer side should get acknowledged whenever it get changed.

**Comment by tngan** [comment]
@fas3r I haven't consolidated the documentation yet, but there is some guideline you can follow.

1. There is a screenshot for configuration of okta side. (https://github.com/authenio/react-samlify/issues/2).

2. The example repository contains how you can initiate the single sign on and single logout with different binding. (https://github.com/authenio/react-samlify)

**Comment by fas3r** [comment]
Hello @tngan , 

I saw that the example of the react-samlify was using OKta but it still does not work. The screenshot helped to understand the missing endpoint but I'm still getting the following error : 
 
```
Construct service provider - missing signatureConfig
``` 
and 
```
[FATAL] when parsing login response sent from okta TypeError: Cannot read property 'SAMLResponse' of undefined
   ....
```

Here the code : 

```
          const idp = saml.IdentityProvider({
            metadata: response.data,
            wantLogoutRequestSigned: true
          });

          const sp = saml.ServiceProvider({
            entityID: 'http://localhost:8080/sp/metadata',
            authnRequestsSigned: false,
            wantAssertionsSigned: true,
            wantMessageSigned: true,
            wantLogoutResponseSigned: true,
            wantLogoutRequestSigned: true,
            privateKey: fs.readFileSync(__dirname + '/ssl/sign/privkey.pem'),
            privateKeyPass: 'VHOSp5RUiBcrsjrcAuXFwU1NKCkGA8px',
            isAssertionEncrypted: false,
            assertionConsumerService: [{
              Binding: saml.Constants.namespace.post,
              Location: 'http://localhost:8080/sp/acs',
            }]
          });

          app.post('/sp/acs', async (req, res) => {
            try {
              const { extract } = await sp.parseLoginResponse(req.idp, 'post', req);
              const { login } = extract.attributes;

              console.log(login);
              // get your system user
              // const payload = getUser(login);
              //
              // // assign req user
              // req.user = { nameId: login };
              //
              // if (payload) {
              //   // create session and redirect to the session page
              //   const token = createToken(payload);
              //   return res.redirect(`/?auth_token=${token}`);
              // }
              //throw new Error('ERR_USER_NOT_FOUND');
            } catch (e) {
              console.error('[FATAL] when parsing login response sent from okta', e);
              return res.redirect('/');
            }
          });

          app.get('/login', async (req, res) => {
                const { id, context } = await sp.createLoginRequest(idp, 'redirect');
                //console.log(context);
                return res.redirect(context);
              });


          app.get('/sso/redirect', async (req, res) => {
            const { id, context: redirectUrl } = await sp.createLoginRequest(req.idp, 'redirect');
            return res.redirect(redirectUrl);
          });

          app.get('/sp/metadata', (req, res) => {
            console.log("here");
            res.header('Content-Type', 'text/xml').send(idp.getMetadata());
          });
        });
```

I don't have problem making pr ... but first I need to implement it ;)

Thanks.

**Comment by tngan** [comment]
@fas3r 

1. `missing signatureConfig` is just a warning, don't worry about that first.
2. Please install body-parser (https://www.npmjs.com/package/body-parser) in order to get the corresponding response from request body.

**Comment by fas3r** [comment]
Hello @tngan , 

It works, thanks for the help. Here is the procedure : 

### Pre-requirement : 

samlify, express ( or other ), body-parser.

1 ) create a new web app with SAML2.0 in okta : 

![image](https://user-images.githubusercontent.com/11342586/54870114-a3396880-4da2-11e9-9e79-3debd7f6c93f.png)

2 ) Configure SAML_integration : 

2.1 ) General setting : 

![image](https://user-images.githubusercontent.com/11342586/54870126-b8ae9280-4da2-11e9-9154-39a697e0a69a.png)

2.2 Configure SAML : 

     - "Single Sign on URL" : the uri where to "POST" the auth request 
     - "Audience URI" : The uri where the metadata are accessible. This is not mandatory if you don't want to share the metadata file. See : [bottom_of_page_here](https://samlify.js.org/#/metadata-distribution)
     - "Assertion Encryption" : We set to "Encrypted". Determines whether the SAML assertion is encrypted or not. Encryption ensures that nobody but the sender and receiver can understand the assertion.
     - "Encryption Certificate" : Upload the path to the certificate `*.cer` to use to encrypt the assertion.

![image](https://user-images.githubusercontent.com/11342586/54870230-f7911800-4da3-11e9-920e-66c22fca8b14.png)

     - and the attributes statement/groups to return from the assertion : 

![image](https://user-images.githubusercontent.com/11342586/54870264-9289f200-4da4-11e9-8ce4-560aaa8e99d7.png)

2.3 Feedback  : 

     - Select what meet your need.

![image](https://user-images.githubusercontent.com/11342586/54870275-b1888400-4da4-11e9-96ec-d09a61cf00a5.png)

3 : Next you will see in the "Sign On" tab the following :

     - 3.1 The Red Arrow : The SAML 2.0 Certificat;
     - 3.2 The Green Arrow : Will help you to get the idp XML file of your application with all the information
     - 3.3 The Blue Arrow : Is a direct link to the metadata file of the application.

![image](https://user-images.githubusercontent.com/11342586/54870311-18a63880-4da5-11e9-815f-f73ab237e954.png)

In the "General" tab you should see something like : 

![image](https://user-images.githubusercontent.com/11342586/54870350-a2ee9c80-4da5-11e9-8c32-c05eaae3d7c9.png)

Very basic example : 

```
   var express = require('express');
    var fs = require('fs');
    var saml = require('samlify');
    var axios = require('axios');
    var bodyParser = require("body-parser");
    var app = express();
    app.use(bodyParser.urlencoded({ extended: true }));
    app.use(bodyParser.json());

    app.use(serveStatic(path.resolve(__dirname, 'public')));

    // URL to the okta metadata
    const uri_okta_metadata = 'https://dev-xxxxxxx.oktapreview.com/app/APP_ID/sso/saml/metadata';

    axios.get(uri_okta_metadata)
        .then(response => {

          const idp = saml.IdentityProvider({
            metadata: response.data,
            isAssertionEncrypted: true,
            messageSigningOrder: 'encrypt-then-sign',
            wantLogoutRequestSigned: true
          });

          const sp = saml.ServiceProvider({
            entityID: 'http://localhost:8080/sp/metadata?encrypted=true',
            authnRequestsSigned: false,
            wantAssertionsSigned: true,
            wantMessageSigned: true,
            wantLogoutResponseSigned: true,
            wantLogoutRequestSigned: true,
            // the private key (.pem) use to sign the assertion; 
            privateKey: fs.readFileSync(__dirname + '/ssl/sign/privkey.pem'),       
            // the private key pass;
            privateKeyPass: 'VHOSp5RUiBcrsjrcAuXFwU1NKCkGA8px',                     
            // the private key (.pem) use to encrypt the assertion;
            encPrivateKey: fs.readFileSync(__dirname + '/ssl/encrypt/privkey.pem'),             
            isAssertionEncrypted: true,
            assertionConsumerService: [{
              Binding: saml.Constants.namespace.post,
              Location: 'http://localhost:8080/sp/acs?encrypted=true',
            }]
          });

          app.post('/sp/acs', async (req, res) => {
            try {
              const { extract } = await sp.parseLoginResponse(idp, 'post', req);
              console.log(extract.attributes);
              /*
              *
              * 
              *    Do your logic here. extract.attributes, should contains : firstName, lastName, email, uid, groups 
              * 
              *           
               */
            } catch (e) {
              console.error('[FATAL] when parsing login response sent from okta', e);
              return res.redirect('/');
            }
          });

          app.get('/login', async (req, res) => {
                const { id, context } = await sp.createLoginRequest(idp, 'redirect');
                console.log(context);
                return res.redirect(context);
              });

          app.get('/sp/metadata', (req, res) => {
            console.log("here");
            res.header('Content-Type', 'text/xml').send(idp.getMetadata());
          });
        });
```

**Comment by tngan** [comment]
@fas3r Awesome, do you want to do a PR for it, or you want me to take over.

I will add a credit for you in the documentation as well. :D

**Comment by fas3r** [comment]
Hello @tngan, 

Sure go ahead:)

**Comment by tngan** [comment]
FYI: https://samlify.js.org/#/okta

Thanks for your contribution. @fas3r

**Comment by matth-c3** [comment]
@tngan thanks to you for taking the time to answer my questions.

**Comment by matth-c3** [comment]
Hello @tngan , 

I saw that you did some changes. Does something change regarding the doc that we prepared ?

Thanks in advance.

**Comment by matth-c3** [comment]
hello @tngan ,

Up.

Thanks in advance.
