### ISSUE TITLE
Invalid binding is used for redirect

### ISSUE THREAD

**Issue by krassx** [tngan/samlify#261]
It seems that "binding.post" is incorrectly used in case of redirect binding, which in turn, leads to malformed AssertionConsumerServiceURL value (saved as "undefined").

The line with the incorrect value is here: https://github.com/tngan/samlify/blob/master/src/binding-redirect.ts#L96

**Comment by tngan** [comment]
@krassx Yes, that's a good catch.

**Comment by tngan** [comment]
@krassx Oh, I misunderstood the question. `AssertionConsumerServiceURL` is where the endpoint accepting SAML response, in fact it can be with Artifact or Post binding, but we only support POST binding (which is the most common use case) right now.

Therefore, the `binding.post` argument is correct.

**Comment by tngan** [comment]
I already rollback the change, so ignore the referenced commit above. Also, there is a related issue on that.

https://github.com/tngan/samlify/issues/98

**Comment by krassx** [comment]
Got it. Thank you for the explanation @tngan!
