### ISSUE TITLE
automatic optional library dependencies not optimal for cross-compile

### ISSUE THREAD

**Issue by lmcmgig** [tngan/samlify#263]
I saw 2.5.0 going out.  The release candidate approach with SAML_VALIDATOR allows us to specify the target optional lib to use.

You can do auto-detection if you need to, but also include a way to manually force the chosen library for cross-compile cases.

**Comment by tngan** [comment]
@lmcmgig Please try the latest v2.6.0-rc1, we have a new implementation on how to make use of schema validator modules.

**Comment by tngan** [comment]
v2.6.0 is released on npm. Feel free to reopen if needed.
