### ISSUE TITLE
Cannot read property 'SAMLResponse' of undefined

### ISSUE THREAD

**Issue by pgcorreia** [tngan/samlify#267]
Hello, I'am currently developing a small project with SAML and I have installed the version 2.5.0 of samlify.

I have the following error;
 TypeError: Cannot read property 'SAMLResponse' of undefined.

I'm new to SAML and I cannot understand why this error is happening. Also read the issue #156 and #177 but I am not able to get the SAML response.

I have the following code:

```js
router.get('/acs', (req, res, next) => {
  saml_req = sp.createLoginRequest(idp, 'post');
  sp.parseLoginResponse(idp, 'post', saml_req.context)
  .then(parseResult => {
    console.log(parseResult)
  })
  .catch(console.error);
});
```

I also tried using the code provided on the tutorial, parsing the SAMLRequest on the req, but still, no luck.

I read that the API got some updates since the tutorial was written. Is there any tutorial for the latest versions?

Thank you in advance.

**Comment by tngan** [comment]
@pgcorreia You need body-parser to get the incoming request body under the property `req.body`.

**Comment by pgcorreia** [comment]
I already use body-parser. The error wasn't in the code...I misunderstood your tutorial...In the code I wrote above, I am trying to parse a login response to the SP but I am actually using a SAML request...that is why I cannot read that property.

If you want, delete this issue because it doesn't makes sense. 

Thanks for your time!

**Comment by tngan** [comment]
@pgcorreia I will close this issue. By the way, for the endpoint that receive response from idp, we won't do GET but POST.
