### ISSUE TITLE
Connection issue - ERROR_UNMATCH_CERTIFICATE_DECLARATION_IN_METADATA

### ISSUE THREAD

**Issue by Hugofromfrance** [tngan/samlify#269]
Hello guys,

I get this error trying SAML connect:
samlify version: 2.5.0
Node version: 8.10.0

It works like a charm with samlify 2.0.0 !

```json 
{"error":"Error: ERROR_UNMATCH_CERTIFICATE_DECLARATION_IN_METADATA\n    at /Users/PROJETS/api/node_modules/samlify/build/src/libsaml.js:297:31\n    at Array.forEach (<anonymous>)\n    at Object.verifySignature (/Users/PROJETS/api/node_modules/samlify/build/src/libsaml.js:266:23)\n    at /Users/PROJETS/api/node_modules/samlify/build/src/flow.js:186:55\n    at step (/Users/PROJETS/api/node_modules/samlify/build/src/flow.js:32:23)\n    at Object.next (/Users/PROJETS/api/node_modules/samlify/build/src/flow.js:13:53)\n    at fulfilled (/Users/PROJETS/api/node_modules/samlify/build/src/flow.js:4:58)\n    at <anonymous>"}
```

Do you need more informations to investigate ?

Thank you 😉

**Comment by tngan** [comment]
@Hugofromfrance How many certificates you specify in the idp metadata ? 

If there are more than one, means that the idp is using more than one certificate in rolling based. I also want to know if the SAML response contains certificate (which is optional in specification).

That error comes out when there are more than one certificates used by idp, and SAML response doesn't contain any one of them.

**Comment by Hugofromfrance** [comment]
It works well
I had 2 certificates in my IDP, you helped me to understand how Google generate IDPMetadata.xml
I only need only one certificate in my case.

However, it worked well with 2 certificates in previous version.

Can you tell me in which case i can use more than one certificates and how can i handle that ?

Thank you

**Comment by tngan** [comment]
@Hugofromfrance You may want to check if the response xml contains a certificate first. You can use more than one certificate for sure if the response xml contains the selected certificate.

Samlify doesn't do the trial-and-error when verifying the signature.

**Comment by Hugofromfrance** [comment]
Ok tnx @tngan 

Good job 👌😉
