### ISSUE TITLE
Add documentation for `messageSigningOrder`

### ISSUE THREAD

**Issue by oddlyfunctional** [tngan/samlify#272]
I spent a whole day trying to figure out why my SAML response was failing to validate the signature even though it was valid according to https://www.samltool.com/, and only after a long time investigating the issues and debugging the code I found about the `messageSigningOrder` configuration entry (thanks to this old comment: https://github.com/tngan/samlify/issues/125#issuecomment-330396839).
I couldn't find anything about it in the https://samlify.js.org, can I suggest adding an entry to the documentation? Maybe a "troubleshooting" section, or even better a complete description of all possible settings for the entities! 🙂

**Comment by tngan** [comment]
0e0ba5b7743bdcf2e46fb235a3204f60e2c2116c
