### ISSUE TITLE
InvalidNameIDPolicy from IDP made sp.parseLoginResponse throw

### ISSUE THREAD

**Issue by marwej** [tngan/samlify#279]
I got this in a response from IdP (AD FS):

```xml
  <samlp:Status>
    <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Requester">
      <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:InvalidNameIDPolicy" />
    </samlp:StatusCode>
  </samlp:Status>
```

It took me a long time to realize because `const parseResult = await sp.parseLoginResponse(idp, 'post', req);` threw an error `ERR_EMPTY_ASSERTION` (https://github.com/tngan/samlify/blob/master/src/flow.ts#L36).

Would it be possible to return a parsed response in these cases too (with correct status code)?

**Comment by tngan** [comment]
0e0ba5b7743bdcf2e46fb235a3204f60e2c2116c

**Comment by tngan** [comment]
Sorry, it was accidentally closed.

**Comment by csgruenebe** [comment]
I got the exact same error from our AD.

**Comment by tngan** [comment]
@csgruenebe  https://samlify.js.org/#/sp-configuration 

Do you mean the `nameIDFormat` ?

**Comment by csgruenebe** [comment]
@tngan ah sorry, did not see it was an array :) so it is already there :)

**Comment by tngan** [comment]
@csgruenebe Can you help to open another ticket ?

**Comment by tngan** [comment]
@csgruenebe Please move the discussion to #284. This ticket will be for the enhancement of handling failed status code inside samlify.

**Comment by tngan** [comment]
@marwej v2.5.1 is released to npm.

The following test covers this use case.

https://github.com/tngan/samlify/blob/846ab75ab176b2443abb4b7edf85abdcf1f8e4cd/test/flow.ts#L655-L661

**Comment by marwej** [comment]
I have now started to get an empty `statusCode` in `const { statusCode, nameID } = parseResult.extract;` but the response from another IdP (Google) is success.

Tried to rollback to an earlier version but same error. Nothing to do with `samlify` then I guess.

Do you recognize this?

**Comment by tngan** [comment]
@marwej If the response is not succeeded, it will throw an error with the top and second tier error message before hit the line you have. The only case must be succeeded when you get the `parseResult`.

Can you show me the code how you construct the handler of SAML response ?
 
I have already removed the `statusCode` in the extractor though.

**Comment by marwej** [comment]
It is a successful result (not the one above).

```xml
<saml2p:Status>
    <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
  </saml2p:Status>
```

The code is basically this:

```javascript
const parseResult = await sp.parseLoginResponse(idp, 'post', req);
if (!isPlainObject(parseResult.extract)) throw new Error('Could not parse SAML response');
const { statusCode, nameID } = parseResult.extract;
if (!isString(statusCode)) throw new Error('No status code');
if (statusCode !== STATUS_CODES.success) throw new Error('Non-successful response');
```

Could I just assume the respons is successful if parsing is ok then?

**Comment by tngan** [comment]
@marwej There is no `statusCode` anymore, you are not supposed to see that since i have removed it.

```js
try {
  const parseResult = await sp.parseLoginResponse(idp, 'post', req);
  console.log(parseResult.extract); // if this line hits, indicating that the status is success
} catch (e) {
  console.error(e);
}
```

**Comment by marwej** [comment]
Roger that. Thanks for a great package!
