### ISSUE TITLE
Usage of Make

### ISSUE THREAD

**Issue by big-kahuna-burger** [tngan/samlify#290]
Thanks for this package.

Q: Is not to having `make` used as a part of `test` script in future considered?

I understand there are lots of linux users out there but this is just a showstopper for anyone using windows out there and preventing possible PRs from windows users or making it hard to get there.

If you do intend to do that, please let me know I'd be happy to help, but I don't want to make major changes to not have my PR merged. 

Thanks

**Comment by tngan** [comment]
Hi @big-kahuna-burger 

Thanks for your feedback, we don't have a plan to change the usage of Makefile. Windows users can use alternative terminal that allows them to do `make` operation.

Related issue: https://github.com/tngan/samlify/issues/240
