### ISSUE TITLE
statusCode no longer on SAMLResponse/loginResponseFields

### ISSUE THREAD

**Issue by haoleman** [tngan/samlify#292]
I am upgrading from 2.4 to 2.6 and noticed that `statusCode` has been removed from parseResult.extract. What is the logic, for knowing the status of the SAMLResponse POST without it?

**Comment by tngan** [comment]
Hi @haoleman, yes, `statusCode` is gone, we now have a better error handling and support two-tiers failure of status code according to the spec.

See more on https://github.com/tngan/samlify/issues/279

**Test case:**

https://github.com/tngan/samlify/blob/12e74120fcf44447b9a0a854413fec360bba1bc6/test/flow.ts#L669-L675

**Comment by tngan** [comment]
If the response is not succeeded, it will throw an error with the top and second tier error message before hit the line you have. The only case must be succeeded when you get the parseResult.

**Comment by haoleman** [comment]
tracking. thank you.
