### ISSUE TITLE
How to specify Certificate Fingerprint

### ISSUE THREAD

**Issue by AwoyoToyin** [tngan/samlify#293]
@tngan 

I am using a custom service that expects a certificate fingerprint and a fingerprint algorithm. I have looked through the docs and everything I can find on the internet but, all example makes direct use of the certificate.

How do I use a fingerprint and algorithm instead?

**Comment by tngan** [comment]
@AwoyoToyin Hello, there is no function exported in samlify that allows you to compute the fingerprint programatically now.

If you want to have a function that can calculate the fingerprint, that would be a feature request. If you just want to calculate the fingerprint manually, there is a tool for you to do that.

https://www.samltool.com/fingerprint.php

**Comment by AwoyoToyin** [comment]
@tngan Thanks for the quick reply.

I have a fingerprint. The service I want to consume requires me to send the fingerprint and the algorithm. Problem is, there are example like this:

`<KeyDescriptor use="signing">
      <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
          <ds:X509Certificate>...</ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
    </KeyDescriptor>`

No example detailing how to specify the fingerprint either in the metadata or otherwise

**Comment by tngan** [comment]
@AwoyoToyin What is the expected place of your custom service that the information should put? Fingerprint and algorithm is not included in the specification as I remembered.

It is not practical to include it in the SAML document, it should be computed during runtime. Typically, your custom service (IDP) should request you to input manually, then calculate the fingerprint with the algorithm again whenever the request/response comes in, instead of directly compare the preset one inside the document.

**Comment by AwoyoToyin** [comment]
@tngan 

Here's an instruction for the onelogin implementation:

```
// Public x509 certificate of the IdP
'x509cert' => '',
/*
*  Instead of use the whole x509cert you can use a fingerprint
*  (openssl x509 -noout -fingerprint -in "idp.crt" to generate it,
*   or add for example the -sha256 , -sha384 or -sha512 parameter)
*
 *  If a fingerprint is provided, then the certFingerprintAlgorithm is required in order to
*  let the toolkit know which Algorithm was used. Possible values: sha1, sha256, sha384 or sha512
*  'sha1' is the default value.
*/
'certFingerprint' => 'AE:AD:C2:11:...',
'certFingerprintAlgorithm' => 'sha1',
```

I am quite new to SAML so, forgive me if I can't really explain what I'm looking for

**Comment by tngan** [comment]
@AwoyoToyin 

It looks like that you want to set the IdP and SP, and **you are not using samlify but OneLogin's SAML PHP Toolkit, so you should put this ticket to https://github.com/onelogin/php-saml**, but i think i can comment something.

1. Are you using OneLogin as your IdP ? If yes, you should be able to get the OneLogin certificate when you create an application. Then use the above-mentioned openssl command to get the fingerprint and algorithm.

2. If you are using samlify to be the IdP, you can create a self-signed x509 certificate for testing purpose, using the same openssl command to generate the fingerprint and algorithm.

**Comment by AwoyoToyin** [comment]
@tngan 

I am using the samlify tool.

1. I am not using OneLogin directly as my IDP. I am working on a project for a company that handles the IDP. I was referred to the OneLogin's SAML PHP Toolkit by them 'cause I believe they have used it on a previous yii project.

2. I understand I can create a self-signed cert but, It won't work 'cause what they expect is a fingerprint that I have.

What I showed you:
```
// Public x509 certificate of the IdP
'x509cert' => '',
/*
*  Instead of use the whole x509cert you can use a fingerprint
*  (openssl x509 -noout -fingerprint -in "idp.crt" to generate it,
*   or add for example the -sha256 , -sha384 or -sha512 parameter)
*
*  If a fingerprint is provided, then the certFingerprintAlgorithm is required in order to
*  let the toolkit know which Algorithm was used. Possible values: sha1, sha256, sha384 or sha512
*  'sha1' is the default value.
*/
'certFingerprint' => 'AE:AD:C2:11:...',
'certFingerprintAlgorithm' => 'sha1',
```

Is just something the OneLogin's SAML PHP Toolkit supports.

My questions does samlify support it as well?

**Comment by tngan** [comment]
@AwoyoToyin We haven't support this yet.
