### ISSUE TITLE
Default logout request template NameID attributes are not matching with default login template

### ISSUE THREAD

**Issue by purmac** [tngan/samlify#295]
I've run into the issue when implementing logout function for ADFS SAML2. When I did the logout request, I got the following error from ADFS.

```
The SAML Single Logout request does not correspond to the logged-in session participant. 
Requestor: http://localhost/v1/customers/mycustomerId 
Request name identifier: Format: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress, NameQualifier:  SPNameQualifier: http://localhost/v1/customers/mycustomerId, SPProvidedId:  
Logged-in session participants: 
Count: 1, [Issuer: http://localhost/v1/customers/mycustomerId, NameID: (Format: urn:oasis:names:tc:SAML:2.0:nameid-format:persistent, NameQualifier:  SPNameQualifier: , SPProvidedId: )]  
```

After digging into the source code, I found the default logout request template added the `SPNameQualifier` attribute NameId.
https://github.com/tngan/samlify/blob/28e111eb8167e77eb126870217141b61503073fb/src/libsaml.ts#L139 

But the same attribute is not presented in the default login request template. Replace the default logout request template with one without `SPNameQualifier` resolves the ADFS error.

Additionally `logoutNameIDFormat` prop is missing in type `ServiceProviderSettings` and `IdentityProviderSettings`. However, the logout requester is trying to use this prop for NameID format. Otherwise, it will always default to email format. Typescript build will fail due to Type error.
https://github.com/tngan/samlify/blob/28e111eb8167e77eb126870217141b61503073fb/src/binding-redirect.ts#L137

I could help to fix these bugs but I would like to confirm my investigation first.

**Comment by tngan** [comment]
@purmac Nice, a good catch.

1) Yes, please remove it from the LogoutRequest. `SPNameQualifier` and `NameQualifier` are optional according to the specification. If other IDP really needs this, user can always replace the default template with a customised one.

2) I didn't adapt the same changes that I have made for the NameIDFormat simplification. (See PR #285, and ticket #284). I think we should do the same for the `logoutNameIDFormat` as they basically share the same logic.

**Comment by purmac** [comment]
Hi @tngan,  I just created a PR. I also notice that the `customTagReplacement` function has inconsistent function type at  https://github.com/tngan/samlify/blob/28e111eb8167e77eb126870217141b61503073fb/src/binding-redirect.ts#L142

Other functions only take template string but not the required tags. Does this consider as a defect?

**Comment by tngan** [comment]
v2.6.1 is published

**Comment by tngan** [comment]
v2.6.1 is released.

For the above question related to `customTagReplacement`, it is not a defect, but we can do it better and make it more consistent, since those are requiredTags, we can always do the replacement regardless of using default template or custom template.
