### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by johndevedu** [tngan/samlify#304]
On mac 10.14.6, npm 6.4.1, tsc 3.5.3. running npm run build fails because of missing module

```
> npm run build

> samlify@2.6.1 build ./samlify-new
> make rebuild

rm -rf build; \
 tsc; \

test/flow.ts:9:28 - error TS2307: Cannot find module '@authenio/samlify-xsd-schema-validator'.

9 import * as validator from '@authenio/samlify-xsd-schema-validator';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

make: *** [rebuild] Error 2
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! samlify@2.6.1 build: `make rebuild`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the samlify@2.6.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I suspect it's related to https://github.com/tngan/samlify/pull/259#issuecomment-479646134. The comment states that `samlify-libxml-xsd` should be installed by default, but it does not get installed since it's a peerDependency. Since npm v3, peerDependencies do not get installed.

Thoughts on adding libxml-xsd as a dependency instead? I'm going to test that scenario, but wanted your thoughts.

**Comment by tngan** [comment]
@johndevedu Yes, the module is only used for unit tests. The validator module is now decided on user side, that's why I don't put it under `dependencies`. The reason why I put in `peerDependencies` is to lock the version range that user installs the validator module when using samlify.

What we can do better is to move the unit tests that are related to validator, to the validator module itself, however, it would have duplication when you modify/add one unit tests, you need to modify/add all. That's why those unit tests are still here.

Another approach that I haven't tested is to delegate the validator-related tests to travis, so for local test, those tests are ignored, but we can install the validator module during travis test, and test specific files one by one, that could also solve this issue.

**Comment by johndevedu** [comment]
@tngan thank you for the quick response. Do you have any documentation on how to decide the validator on "user side"? I probably have to dig into the code more, but it'd be nice to see some documentation around that. Validations are mentioned briefly in the Advanced section of the doc, but it'd be nice to see some details. If not, I'll try to make some contributions.

**Comment by johndevedu** [comment]
Wow, just realized it's front and center on the github README. lol

Question: what are your thoughts on separating the builds for src vs test? For newbs like me, it took a little to wrap my head around why a clone -> build was failing. Was assuming the README contents were more for consumers of the lib instead of developers.

**Comment by tngan** [comment]
@johndevedu Feel free to cross check the pull request. I have separated the runtime build and test build. I am still thinking a better way instead of duplicating the integration tests to all supported validator modules, and welcome to any suggestion.

**Comment by johndevedu** [comment]
@tngan really appreciate your quick responses and accommodations! I'll try and take a look later.

**Comment by tngan** [comment]
@johndevedu Sure. Take your time.

**Comment by tngan** [comment]
@johndevedu Any update on this issue ?

**Comment by johndevedu** [comment]
@tngan sorry been super busy lately. Can't really dive deeper ATM, but did a quick clone -> `npm build` again to see if the PR fixed the issue. But I still get an error.

```src/entity-idp.ts:56:11 - error TS2345: Argument of type '{ wantAuthnRequestsSigned: boolean; tagPrefix: { encryptedAssertion: string; }; } & IdentityProviderSettings' is not assignable to parameter of type 'EntityConstructor'.
  Types of property 'signingCert' are incompatible.
    Type 'string | Buffer | undefined' is not assignable to type 'string | undefined'.
      Type 'Buffer' is not assignable to type 'string'.

56     super(entitySetting, 'idp');
             ~~~~~~~~~~~~~

src/entity-sp.ts:46:11 - error TS2345: Argument of type '{ authnRequestsSigned: boolean; wantAssertionsSigned: boolean; wantMessageSigned: boolean; } & ServiceProviderSettings' is not assignable to parameter of type 'EntityConstructor'.
  Types of property 'signingCert' are incompatible.
    Type 'string | Buffer | undefined' is not assignable to type 'string | undefined'.
      Type 'Buffer' is not assignable to type 'string'.

46     super(entitySetting, 'sp');
             ~~~~~~~~~~~~~

src/entity.ts:70:5 - error TS2322: Type '({ wantLogoutResponseSigned: boolean; messageSigningOrder: string; wantLogoutRequestSigned: boolean; allowCreate: boolean; isAssertionEncrypted: boolean; requestSignatureAlgorithm: string; dataEncryptionAlgorithm: string; keyEncryptionAlgorithm: string; generateID: () => string; relayState: string; } & string & { .....' is not assignable to type 'EntitySetting'.
  Types of property 'singleLogoutService' are incompatible.
    Type '{ isDefault?: boolean | undefined; Binding: string; Location: string; }[] | undefined' is not assignable to type '({ Binding: string; Location: string; }[] & { [key: string]: string; }[]) | undefined'.
      Type '{ isDefault?: boolean | undefined; Binding: string; Location: string; }[]' is not assignable to type '{ Binding: string; Location: string; }[] & { [key: string]: string; }[]'.
        Type '{ isDefault?: boolean | undefined; Binding: string; Location: string; }[]' is not assignable to type '{ [key: string]: string; }[]'.
          Type '{ isDefault?: boolean | undefined; Binding: string; Location: string; }' is not assignable to type '{ [key: string]: string; }'.
            Property 'isDefault' is incompatible with index signature.
              Type 'boolean | undefined' is not assignable to type 'string'.
                Type 'undefined' is not assignable to type 'string'.

70     this.entitySetting = Object.assign({}, defaultEntitySetting, entitySetting);
       ~~~~~~~~~~~~~~~~~~


Found 3 errors.```

Don't have much time now to dig into a better suggestion at this time. Please feel free to close this issue as you see fit. Thanks again for an awesome lib!
