### ISSUE TITLE
Example with own IDP and multiple SP?

### ISSUE THREAD

**Issue by georgyfarniev** [tngan/samlify#310]
Hello, is there any example how to create custom IDP for my SP's? It's unclear from documentation how to do it, there's no full example. Thanks

**Comment by tngan** [comment]
@georgyfarniev We had a full example long time ago, but I removed it after the code base was revamped. One of our library users made an example but it was in private, you may ask in the following discussion thread on spectrum.

https://spectrum.chat/samlify/general/hi~78c76c34-c56b-47d1-b33f-f1ef4ed95ffc
