### ISSUE TITLE
Error: ERR_FAILED_STATUS with top tier code: urn:oasis:names:tc:SAML:2.0:status:Requester, second tier code: urn:oasis:names:tc:SAML:2.0:status:RequestDenied

### ISSUE THREAD

**Issue by hesantoshm** [tngan/samlify#313]
this issue  produce when I config sp without using the metadata file . 

```js
const sp = saml.ServiceProvider({
  entityID: "https://v2-auth.com/auth/logincallback",
  assertionConsumerService: [{ 
    binding: 'redirect',
    location: 'https://v2-auth.com/auth/logincallback'
  }]
});
```

here in this case, assertionConsumerServiceURL is undefined in sample request and i got 
Error: ERR_FAILED_STATUS with top tier code: `urn:oasis:names:tc:SAML:2.0:status:Requester`, second tier code: `urn:oasis:names:tc:SAML:2.0:status:RequestDenied`

**Comment by hesantoshm** [comment]
how  to get  rid of this error

**Comment by tngan** [comment]
@hesantoshm Looks like the NameIDFormat is not set properly.

Checkout this https://samlify.js.org/#/sp-configuration?id=required-parameters for detail.

**Comment by hesantoshm** [comment]
can you give exaple for sp configuration without using metadata file

**Comment by tngan** [comment]
Hi @hesantoshm,

https://github.com/tngan/samlify/blob/32948dfdf8083bef4106e1f8980ea29866461b22/test/issues.ts#L41-L76

**Comment by tngan** [comment]
Hi @hesantoshm, any update on this issue ?

**Comment by tngan** [comment]
@hesantoshm I will close this ticket since there is no update for couple weeks. Feel free to reopen the ticket if you have further question.
