### ISSUE TITLE
Potential typo in the documentation

### ISSUE THREAD

**Issue by mr-m0u5e** [tngan/samlify#314]
### Under "Advanced -> IDP/SP Configuration -> Service Provider -> Metadata: String" ###
If I understand it correctly, it should be SP issued metadata? Or am I missing something?

**Comment by tngan** [comment]
@mr-m0u5e metadata is the context of the metadata file, it can be either `string` or `buffer`. If it is a buffer, we will then convert it back to string internally.

https://github.com/tngan/samlify/blob/5b1b14535ce3f924222d2002eb20a4fcc7a729b4/src/metadata.ts#L31-L32

**Comment by tngan** [comment]
@mr-m0u5e Oh sorry, I misunderstood your question. Yes, it should be a typo, feel free to create a PR for that. Good catch!

**Comment by mr-m0u5e** [comment]
Submitted a PR, closing the issue. 
Thank you for all your work!
