### ISSUE TITLE
messageSigningOrder question

### ISSUE THREAD

**Issue by mr-m0u5e** [tngan/samlify#316]
Hi, 
Having an issue verifying a signed response w/ signed & encrypted assertion (though OneLogin's SAML tool has no problem validating the response with the certs and keys provided). 
I suspect it might have something to do with the signing order, so my question is what is the right way to set "messageSigningOrder: SigningOrder"? Could you maybe give an example of how to set it correctly?

Thank you.

**Comment by tngan** [comment]
@mr-m0u5e You may do something like

```js
const idp = saml.IdentityProvider({
  isAssertionEncrypted: true,
  messageSigningOrder: 'encrypt-then-sign',
});
```

The default value is `sign-then-encrypt`. Which iDP are you using ?

**Comment by mr-m0u5e** [comment]
Got it! Thank you
Working with a 3rd party that are using PingFederate as their iDP it seems like.

**Comment by tngan** [comment]
@mr-m0u5e You can consider to make an example for PingFederate, and PR for documentation is welcome.

Just like what @fas3r has done before, see https://github.com/tngan/samlify/issues/255.

**Comment by mr-m0u5e** [comment]
@tngan I'll be honest with you - I still haven't figured it out, the signing order wasn't the issue. Still unable to verify their signatures on signed response w/ signed & encrypted assertion. 
But if I do figure it out, I'll try to do a PR.

**Comment by mr-m0u5e** [comment]
@tngan Thanks! Sent you a pm.
