### ISSUE TITLE
Digest verification failure for assertion

### ISSUE THREAD

**Issue by keerthivasan-r** [tngan/samlify#320]
Hi, 

We are facing issue when the digest validation happens in the receiver. By debugging the code, we figured out there are changes that are been done to the assertion node, without changing its meaning like

- adding inclusive namespace
- closing tag replaced with </>
- The order of attributes

Can someone guide?

**Comment by keerthivasan-r** [comment]
We were able to solve this problem by changing to a different transformation / canonical algorithm. Thnak

**Comment by rastko-florencehc** [comment]
@keerthivasan-r hi, we are experiencing the similar issue... Transformations that are present in the signature element are:

- EnvelopedSignature
- ExclusiveCanonicalization

The _ ExclusiveCanonicalization_ is the one that modifies the assertion node and causes the digest to fail.

Can you give me a bit more details how have you fix this issue?
