### ISSUE TITLE
XML Validator without external dependecies?

### ISSUE THREAD

**Issue by tmedanovic** [tngan/samlify#324]
Is there any validator that doesn't require Java or Python?

**Comment by tngan** [comment]
@tmedanovic Yes,  https://github.com/authenio/samlify-node-xmllint

**Comment by tngan** [comment]
@tmedanovic Any update ?

**Comment by tmedanovic** [comment]
@tngan Sorry for taking so long. It works. I think that should be the recommended validator, I'm sure lots of people don't want to use Java/Python in their node project if they absolutely don't have to.

**Comment by tngan** [comment]
@tmedanovic Thanks for your update. That's the reason why we have made the validator module to be pluggable, you can even write your own one if you want. I agree such extra dependency is not really friendly for the user side though.

**Comment by tmedanovic** [comment]
@tngan Thats great feature! I think it would help to update the documentation explaining the differences between different ones in https://github.com/tngan/samlify#installation. I was actually surprised to see java spawning :)
