### ISSUE TITLE
No validation function found.

### ISSUE THREAD

**Issue by rajatdhir** [tngan/samlify#325]
Is there any change in the library?
I have been using Samilify to authenticate with Okta and it was working fine. Now I am getting an error.

"Your application is potentially vulnerable because no validation function found. Please read the documentation on how to set up the validator. (https://github.com/tngan/samlify#installation)"

Kindly suggest what changes are required for this. 
Technology: Nodejs

**Comment by tngan** [comment]
@rajatdhir Yes, we made the usage of schema validator in a dynamic way starting from `v2.6.0`. You can checkout the release note here.

https://github.com/tngan/samlify/releases/tag/v2.6.0

If you want to keep the previous validator, you can continue with using `@authenio/samlify-xsd-schema-validator`.

**Comment by rajatdhir** [comment]
HI,
I am using okta with Node.Js (Version 10) and saml version is 2.5.0. I have taken a reference from the saml URL https://samlify.js.org/#/okta.  
I am facing this error "Your application is potentially vulnerable because no validation function found. Please read the documentation on how to set up the validator" when I am trying to execute my current code.
what changes are required for this current code? 

My Code:-

const idp = saml.IdentityProvider({
	metadata: metaresponse.data,
	isAssertionEncrypted: false,
	messageSigningOrder: 'encrypt-then-sign',
	wantLogoutRequestSigned: true
});
		
const sp = saml.ServiceProvider({
	entityID: 'https://app.infraguard.io/api/metadata?encrypted=true',
	authnRequestsSigned: false,
	wantAssertionsSigned: false,
	wantMessageSigned: true,
	wantLogoutResponseSigned: true,
	wantLogoutRequestSigned: true,
	// the private key (.pem) use to sign the assertion; 
	privateKey: fs.readFileSync(__dirname + '/ssl/privkey.pem'),       
	// the private key pass;
	privateKeyPass: '7cd5fb629cc68c1f6790703ca97f9e74',
	// the private key (.pem) use to encrypt the assertion;
	encPrivateKey: fs.readFileSync(__dirname + '/ssl/key.pem'),             
	isAssertionEncrypted: true,
        assertionConsumerService: [{
             Binding: saml.Constants.namespace.post,
	     Location: 'https://app.infraguard.io/api/authenticate?encrypted=true',
	}]
});

const { extract }  = await sp.parseLoginResponse(idp, 'post', req);

**Comment by tngan** [comment]
@rajatdhir Have you read through the documentation? The instruction tells you to read  https://github.com/tngan/samlify#installation. You can just follow the instruction to set up the validator.

**Comment by tngan** [comment]
@rajatdhir I will close it first. Please reopen if you have further question.

**Comment by ramyakotteswaran** [comment]
I am getting this Error"Your application is potentially vulnerable because no validation function found. Please read the documentation on how to setup the validator"
using samlify:2.6.2
NODE: v10.16.3
NPM: 6.9.0,
When i have followed the instruction in documention, I am getting below Error,
Module not found: Error: Can't resolve '@authenio/samlify-xsd-schema-validator'
@tngan  Can you please help me fix this issue.

Thanks in Advance!
