### ISSUE TITLE
How to setup saml 2.0 in vue.js?

### ISSUE THREAD

**Issue by dipakdas99** [tngan/samlify#327]
I've no idea how to configure saml 2.0 in vue.js although I have idp `.crt` and `.xml` file. Could you please guide me to configure that?

**Comment by tngan** [comment]
@dipakdas99 You can take a look on the example, https://github.com/authenio/react-samlify. You can use samlify regardless of any frontend framework, because you should do the url generation and response parsing on the backend, say inside the handlers in router and controller.

**Comment by tngan** [comment]
@dipakdas99 It's not directly related to the samlify core, I will close this issue first, please feel free to open another ticket in another repository https://github.com/authenio/react-samlify if needed.
