### ISSUE TITLE
Your application is potentially vulnerable because no validation function found. Please read the documentation on how to setup the validator

### ISSUE THREAD

**Issue by ramyakotteswaran** [tngan/samlify#331]
I am getting this Error "Your application is potentially vulnerable because no validation function found. Please read the documentation on how to setup the validator"
using samlify:2.6.2
NODE: v10.16.3
NPM: 6.9.0,
When i have followed the instruction in documention, I am getting below Error,
Module not found: Error: Can't resolve '@authenio/samlify-xsd-schema-validator'
@tngan Can you please help me fix this issue.

Thanks in Advance!

**Comment by tngan** [comment]
@ramyakotteswaran You need to install the validator module separately. You can simply run

`yarn add @authenio/samlify-xsd-schema-validator`

**Comment by ramyakotteswaran** [comment]
Yes, I have done, after this when i start the application, I am facing below Error,

import validator from '@authenio/samlify-xsd-schema-validator';

const saml = require('samlify');

saml.setSchemaValidator(validator);

saml.setSchemaValidator({
  validate: (response) => {
    /* implment your own or always returns a resolved promise to skip */
    return Promise.resolve('skipped');
  }
});

This Lines i have setup in my server.js file
Can you please give me a clarity for setup the validator if any?

**Comment by tngan** [comment]
@ramyakotteswaran 

`import * as validator from '@authenio/samlify-xsd-schema-validator';`

instead of 

`import validator from '@authenio/samlify-xsd-schema-validator';`

Since there is no default export from the validator module.

**Comment by tngan** [comment]
> Yes, I have done, after this when i start the application, I am facing below Error,
> 
> "TypeError: Cannot read property 'validate' of undefined "
> 
> 
> ```js
> import validator from '@authenio/samlify-xsd-schema-validator';
> 
> const saml = require('samlify');
> 
> saml.setSchemaValidator(validator);
> 
> saml.setSchemaValidator({
>   validate: (response) => {
>     /* implment your own or always returns a resolved promise to skip */
>     return Promise.resolve('skipped');
>   }
> });
> ```
> 
> Getting Error in this Line
> 
> https://github.com/tngan/samlify/blob/6bdadbf264c7afff7ac2a6d58a60ccc1e58276ff/src/api.ts#L16
> 
> ** **
> This Lines i have setup in my server.js file
> Can you please give me a clarity for setup the validator, if any?
> I have gone through the steps in doc, still unable to get clear idea. :(

You don't need the second `setSchemaValidator`, it's because you have already imported the validator, otherwise, it will get override, the second one is for custom validation or even skip it.

**Comment by ramyakotteswaran** [comment]
Yeah, I agree, After done with these changes i didnt find any message in Terminal, But Page is still loading and unable to see the application. When i saw in console 
`Unrecognized Content-Security-Policy directive 'referrer'.`
Do you have any idea about this?

If yes, It will be very helpful for me bec i am completely blocked here

**Comment by NitinBhasneria** [comment]
@tngan I am not able to install validator. 
When I try npm i @authenio/samlify-xsd-schema-validator it gives error.
![a](https://user-images.githubusercontent.com/44112080/127435483-14435b7a-ce54-4240-b6f0-bcdfa056ea90.png)
Is there any other way?

**Comment by ramyakotteswaran** [comment]
Hey , Check you java version amd clean cache and try once more time

**Comment by NitinBhasneria** [comment]
@ramyakotteswaran It doesn't work. Getting the same error.

**Comment by NitinBhasneria** [comment]
It worked after the installation of java Thanks @ramyakotteswaran .
I have a doubt that is it necessary to install java?? or there is any other way.

**Comment by ramyakotteswaran** [comment]
You are welcome.

**Comment by NitinBhasneria** [comment]
@ramyakotteswaran 
I am getting error in web server while installing @authenio/samlify-xsd-schema-validator
![ss](https://user-images.githubusercontent.com/44112080/127632384-0fc5d2bb-b27c-4dc2-885c-e50899b14a73.png)
Please have a look.

**Comment by ramyakotteswaran** [comment]
Hi Tngan/Samlify

If u see the Error, it says there is no peer dependencies try install
samlify>=2.6.0 and check *validator.js* file is available or not
Thanks

**Comment by Iliyas-tech** [comment]
> @ramyakotteswaran You need to install the validator module separately. You can simply run
> 
> `yarn add @authenio/samlify-xsd-schema-validator`

@tngan even after doing npm i @authenio/samlify-xsd-schema-validator, Still getting this error
Your application is potentially vulnerable because no validation function found. Please read the documentation on how to setup the validator. (https://github.com/tngan/samlify#installation) 
Please tell me how to resolve it

**Comment by ramyakotteswaran** [comment]
Hi Tony,

Do you have any docker run or running locally are you facing it.

check java version or check have u able to find
/usr/src/app/node_modules/xsd-schema-validator
&&
/usr/bin/javac support/XMLValidator.java

Regards,
Ramya Kotteswaran
