### ISSUE TITLE
Please replace deflate-js (license issue)

### ISSUE THREAD

**Issue by drkinder123** [tngan/samlify#334]
Hi, I appreciate your work a lot, but I have found a issue: `deflate-js` is distributed under **GPLv2**, that means samlify cannot be distributed under **MIT** license.

May be you can switch to another deflate library, such as **pako** ?

Reference: https://github.com/beatgammit/deflate-js/blob/master/LICENSE

Thanks

**Comment by tngan** [comment]
@drkinder123 Thanks for pointing out. In order to keep samlify to be distributed under MIT license, I will see if I can replace it with https://github.com/nodeca/pako, and release with version 2.7.

**Comment by tngan** [comment]
Remarks: The test failure was fixed with 0c0bc337e1ee2a6af93c3ef7c12b1332908ca716 in master branch.

**Comment by drkinder123** [comment]
Thanks for the quick response and resolution

**Comment by tngan** [comment]
@drkinder123 It will be planned to release as 2.7 by the end of Jan.

**Comment by tngan** [comment]
@drkinder123 Released with 2.7.0.
