### ISSUE TITLE
Node.js prints Deprecation Warning for Buffer

### ISSUE THREAD

**Issue by bryaningl3** [tngan/samlify#338]
ERROR	(node:8) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

See: https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/

**Comment by tngan** [comment]
@bryaningl3 Thanks for your report, I am glad to have you working on the PR, what do you think ? There are several files still using the constructor.

**Comment by bryaningl3** [comment]
Pull request created...

**Comment by tngan** [comment]
@bryaningl3 The commit is released with 2.7.0.
