### ISSUE TITLE
Error: spawn java ENOENT at Process.ChildProcess._handle.onexit

### ISSUE THREAD

**Issue by ramyakotteswaran** [tngan/samlify#342]
i'm getting this strange issue referenced here. it works in my local machine. but, it doesn't seem to work when containerised in a docker environment.

node -v: 10.19.0
npm -v : 6.13.4
samlify: 2.4.0-rc2

getting this Error **Error: spawn java ENOENT at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19) at onErrorNT (internal/child_process.js:362:16) at _combinedTickCallback (internal/process/next_tick.js:139:11) at process._tickCallback (internal/process/next_tick.js:181:9)**

I have tried 2.7.1 samlify, Getting This Error `You intend to have time validation however the document doesn't include the valid range. `

Its a Big Blocker for me, Can you help me to fix this?

Please let me know, which version to use @this time?

**Comment by rastko-florencehc** [comment]
@ramyakotteswaran do you have JAVA runtime installed in docker environment?

**Comment by ramyakotteswaran** [comment]
rastko-florencehc Yeah Docker Environment JRE

**Comment by tngan** [comment]
@ramyakotteswaran I recommend that you can upgrade to latest v2.7.1. Then, you can choose a non-java validator module.

**Comment by tngan** [comment]
@ramyakotteswaran `You intend to have time validation however the document doesn't include the valid range.`, this is not an error but a warning.

Do you have a sample of SAML response without sensitive information?

**Comment by ramyakotteswaran** [comment]
I will try latest Version but how i choose non-java validator module?

**Comment by tngan** [comment]
@ramyakotteswaran I don't know how your application is setup. It would help if you can create an example repository without sensitive information.

**Comment by ramyakotteswaran** [comment]
I build Application Base of this `https://github.com/kriasoft/react-starter-kit`

**Comment by tngan** [comment]
@ramyakotteswaran I recommend you to remove `node_modules` and run `yarn` again if you are using the latest version of samlify, it shouldn't compile with node-gyp. It does for old version but not the latest one.

You can use `@authenio/samlify-validate-with-xmllint` which is one of the non-java validator module. This one is commonly used based on the download statistics I have right now.

**Comment by tngan** [comment]
@ramyakotteswaran Have you fixed this issue ?

**Comment by tngan** [comment]
I will close this ticket since there is a workaround and no more updates on this ticket. Feel free to reopen it when you have further question.
