### ISSUE TITLE
reason for console log?

### ISSUE THREAD

**Issue by burkeallen** [tngan/samlify#343]
is there a reason for the console.log on line 267 of entitiy.js file?

`
 console.log('Verifying signature: ', res, opts.from.entityMeta, opts.from.entitySetting.requestSignatureAlgorithm);
`

if this is only there for debugging purposes,  can you please remove it or put a conditional flag on it so that it is not output in normal production use?

thanks

**Comment by tngan** [comment]
@burkeallen Which version of samlify are you using ?

**Comment by burkeallen** [comment]
sorry, I should have mentioned that in my original post

@ampliflex/samlify":  2.1.1

**Comment by tngan** [comment]
@burkeallen That one is a forked version and pretty old. You can use to work with the latest version of `"tngan/samlify": 2.7.1`. Otherwise, you should open ticket inside the forked repository.

**Comment by burkeallen** [comment]
Thank you, i did not realize that. I will switch to your version

Ths you for your timely response and the development of such a useful
library.
