### ISSUE TITLE
Log out functionality

### ISSUE THREAD

**Issue by vi-cat** [tngan/samlify#348]
Hello!

I am trying to implement a logout flow for my application, but I can't seem to find any information about that in this package. Do I have to implement it manually? how have other people done so?

Thank you.

**Comment by tngan** [comment]
@virginc Hello, you can find the logout example in https://github.com/authenio/react-samlify, it integrates with Okta IDP. 

You can also find the use cases in flow.ts. 

https://github.com/tngan/samlify/blob/c6a17ff815de04779fb245a8a6e1088df7dfd513/test/flow.ts#L233-L266

**Comment by tngan** [comment]
@vi-cat I will close this ticket first. Feel free to reopen it when you have further question.
