### ISSUE TITLE
Idp metadata fails validation at samltest.id due to SingleSignOnService index attribute

### ISSUE THREAD

**Issue by matthewsanders** [tngan/samlify#352]
Currently there is an extra `index` attribute that is added to the SingleSignOnService that causes validation of Idp metadata to fail at https://samltest.id/.

The error:

moment.metadata:1: element SingleSignOnService: Schemas validity error : Element '{urn:oasis:names:tc:SAML:2.0:metadata}SingleSignOnService', attribute 'index': The attribute 'index' is not allowed.

The element that is procedurally produced by samlify:

`<SingleSignOnService index="0" Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://some-location-here"/>`

Note the additional `index="0"`

**Comment by tngan** [comment]
@matthewsanders Good catch. With referring to the [metadata schema](https://docs.oasis-open.org/security/saml/v2.0/saml-schema-metadata-2.0.xsd), `SingleSignOnService` is with `EndpointType` but not `IndexedEndpointType`, so `index` attribute shouldn't be applied.

**Comment by tngan** [comment]
2.7.2 is released.
