### ISSUE TITLE
Aliasing an exported type as the default export hides needed types

### ISSUE THREAD

**Issue by shellscape** [tngan/samlify#354]
Referencing the way that this project exports the public members here: https://github.com/tngan/samlify/blob/728fde86f6452e6610d19c18ea63c378a979dde4/index.ts#L2

By using `IdentityProvider` as the default export alias, the actual `IdentityProvider` class (https://github.com/tngan/samlify/blob/master/src/entity-idp.ts#L30) is being hidden from resolution by consuming code.

If we're trying to build say, a cache that contains one or more `IdentityProvider` class instances, and type that cache properly, there's no way to reference that type.

We'd be forced to use a module file path:

```ts
import { IdentityProvider } from 'samlify/types/src/entity-idp';
import { ServiceProvider } from 'samlify/types/src/entity-sp';
```
and that's **_really really bad_** since that approach is well known to be prone to breaking between patch versions.

A better solution here would be to export such like:

```ts
export * from './src/entity-idp';
```

and export a named function in entity-idp.ts:

```ts
const createIdentityProvider = (props: IdentityProviderSettings) => {
  return new IdentityProvider(props);
}

export default createIdentityProvider;
```

Or, at the very least, export the types for `IdentityProvider` and `ServiceProvider` in a minor version without breaking changes.

**Comment by tngan** [comment]
@shellscape We better get rid of introducing breaking change. I already have a plan to release v3 by the end of this year, by simplifying the logic, and have better API design.

What we can do for now is to export something like

```javascript
// index.ts
import IdentityProvider, { IdentityProvider as IdentityProviderInstance } from './src/entity-idp';
import ServiceProvider, { ServiceProvider as ServiceProviderInstance } from './src/entity-sp';
// ...
export {
  IdentityProvider,
  IdentityProviderInstance,
  ServiceProvider,
  ServiceProviderInstance
}
// samlify.IdentityProvider won't break with this approach, it's still calling the default function
```

For the cache, it can be something like as follow.

```ts
type Cache = {
  [issuer: string]: IdentityProviderInstance | ServiceProviderInstance
};
let cache: Cache;
```

Any better idea?

**Comment by FreifeldRoyi** [comment]
Any update on this issue? This is actually preventing me from migrating to Samlify from another lib

**Comment by tngan** [comment]
@shellscape @FreifeldRoyi How's the above mentioned proposal? This wouldn't break the current typing definition.

**Comment by FreifeldRoyi** [comment]
Sounds good

**Comment by natevecc** [comment]
@FreifeldRoyi as a work around you can use  `ReturnType`
```ts
import { IdentityProvider, ServiceProvider } from 'samlify';

let idp: ReturnType<typeof IdentityProvider>;
let sp: ReturnType<typeof ServiceProvider>;
```

**Comment by tngan** [comment]
@FreifeldRoyi @shellscape Feel free to check the release of 2.7.4.
