### ISSUE TITLE
NameIDFormat extraction from IDP metadata return undefined

### ISSUE THREAD

**Issue by ebrurak** [tngan/samlify#361]
Hello,
I'm running samlify tests and I've noticed an issue on '_NameIDFormat_' extraction.
Why nameIDFormat cannot be extracted from IDP metadata (for example from test/misc/idpmeta.xml)? The library always return **undefined**.

From binding-post.ts:
> const nameIDFormat = idpSetting.nameIDFormat;
> const selectedNameIDFormat = Array.isArray(nameIDFormat) ? nameIDFormat[0] : nameIDFormat;

Work well here:
> const nameIDFormat = spSetting.nameIDFormat;
> const selectedNameIDFormat = Array.isArray(nameIDFormat) ? nameIDFormat[0] : nameIDFormat;

 Thanks in advance

**Comment by tngan** [comment]
@ebrurak Looks like nameIDFormat is missing when configuring the IDP's entitySetting.

https://github.com/tngan/samlify/blob/ee94a249d3cb60698df5c0bc419575f0262ba726/src/entity.ts#L69-L88

**Comment by ebrurak** [comment]
Yes, you're quite right. It's OK when setting it into 'idp' entitySetting.
Thanks

**Comment by tngan** [comment]
@ebrurak I will do a patch later on.
