### ISSUE TITLE
Validator issue when installing on AWS EC2

### ISSUE THREAD

**Issue by mikevbaker** [tngan/samlify#365]
I'm using AWS Elastic Beanstalk (backed up by EC2) to host an application on nodejs with ngnix.
When I assemble the zip file and deploy the application, I get an error about the post-install step because it doesn't have java support. 
Do any of the validator options listed on the home page not require the java support?
I used the technique you provided to resolve the validation but I'd like to use one of the ones provided if possible.
Thanks

**Comment by tngan** [comment]
@mikevbaker Yes, you can install another validator module, e.g. `samlify-node-xmllint`.

```typescript
import * as samlify from 'samlify';
import * as validator from '@authenio/samlify-node-xmllint';
// const validator = require('@authenio/samlify-node-xmllint');
samlify.setSchemaValidator(validator);
```

**Comment by mikevbaker** [comment]
Thanks for the help. I have that in place but now I'm getting a different error ERR_SUBJECT_UNCONFIRMED. I looked for that message in the src and I see only one place... it's checking the time? I don't see anything in my SAML response about notBefore, notOnOrAfter, etc. Is a time constraint a requirement that you've added? (I originally wrote this in the summer of 2017)
Thanks, Mike

**Comment by tngan** [comment]
@mikevbaker Yes, you can use the clock drift setting to add time tolerance based on the drift between client and server. Is it solved?

**Comment by mikevbaker** [comment]
Yes, thanks for the info on the validator. I was able to put that one in place and deploy it to AWS without any issues. The client still has to test it out but this issue is resolved.
