### ISSUE TITLE
Can I use this with any Identity provider

### ISSUE THREAD

**Issue by NilukaSripalim** [tngan/samlify#367]

**Comment by tngan** [comment]
@NilukaSripalim Yes, with SAML 2.0.

**Comment by NilukaSripalim** [comment]
Could you please list steps for access this with other identity provider, and is this use any HTTP client

**Comment by tngan** [comment]
@NilukaSripalim Nope, we don't have HTTP client inside, this library helps you to build the SAML request and response regardless of any Node.js web framework.

See https://github.com/authenio/react-samlify for the example.
