### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by Inderjit1** [tngan/samlify#375]
Hello,

This may not be a bug, I did not see any area where to message for specific questions.
I followed the instructions as listed in the Okta documentation. How exactly am I supposed to trigger the okta login screen? I am supposed to navigate to http://localhost:3000/login to do this?

```js
const uri_okta_metadata = 'https://xxxxxx/metadata;
axios.get(uri_okta_metadata)
  .then(response => {
    
    const idp = saml.IdentityProvider({
      metadata: response.data
    });

    const sp = saml.ServiceProvider({
      entityID: 'http://localhost:3000/sp/metadata',
      authnRequestsSigned: false,
      wantAssertionsSigned: false,
      wantMessageSigned: true,
      wantLogoutResponseSigned: false,
      wantLogoutRequestSigned: true,
      // the private key (.pem) use to sign the assertion; 
      // privateKey: fs.readFileSync(__dirname + '/ssl/sign/privkey.pem'),       
      // the private key pass;
      //privateKeyPass: 'VHOSp5RUiBcrsjrcAuXFwU1NKCkGA8px',                     
      // the private key (.pem) use to encrypt the assertion;
      //encPrivateKey: fs.readFileSync(__dirname + '/ssl/encrypt/privkey.pem'),             
      isAssertionEncrypted: true,
      assertionConsumerService: [{
        Binding: saml.Constants.namespace.post,
        Location: 'http://localhost:3000/sp/acs',
      }]
    });

    app.get('/login', (req, res) => {
      console.log("Inside login");
      const { id, context } = sp.createLoginRequest(idp, 'redirect');
      console.log(context);
      return res.redirect(context);
    });

    app.post('/sp/acs', (req, res, next) => {
      try {
        console.log("Before extract");
        const { extract } = sp.parseLoginResponse(idp, 'post', req);
        console.log("Inside sp/acs");
        console.log(extract.attributes);
        /**
        *
        * Implement your logic here. 
        * extract.attributes, should contains : firstName, lastName, email, uid, groups 
        *           
        **/
      } catch (e) {
        console.log("Failed to post");
        console.error('[FATAL] when parsing login response sent from okta', e);
        return res.redirect('/users');
      }
    });

    app.get('/sp/metadata', (req, res) => {
      res.header('Content-Type', 'text/xml').send(idp.getMetadata());
    });

  });
```

**Comment by tngan** [comment]
@Inderjit1 If you configure Okta correctly, when you access `http://localhost:3000/login`, it will redirect you to the login screen. If you have already logged in to Okta, Okta will send the response and redirect it back to the assertion consumer endpoint `/sp/acs` for validation and parsing on SP side. This is the flow of SP-initiated SSO.

Same example you can find in https://github.com/authenio/react-samlify/blob/d36744c53f979e376b6380ae5368dd1ed70172a4/server.ts#L39-L42.

**Comment by Inderjit1** [comment]
@tngan Thank you for the quick response. This is how I setup my Okta configuration, I don't see anything wrong.

![image](https://user-images.githubusercontent.com/15989922/83062682-e41ab600-a013-11ea-9d0f-d9bfdf658b31.png)

**Comment by tngan** [comment]
@Inderjit1 Then, what problem are you encountering right now though?

**Comment by Inderjit1** [comment]
When I access localhost:3000/login nothing happens, it just keeps loading
(Okta screen does not appear) and eventually times out.

**Comment by tngan** [comment]
@Inderjit1 Do you see any log message from the Okta dashboard?

**Comment by Inderjit1** [comment]
I do not. The Okta login screen does not even get triggered. Is there
anything you see that could be wrong? I believe I followed your
documentation exactly and I believe my Okta configuration is correct.

**Comment by Inderjit1** [comment]
I was able to initiate the okta login screen. After signing in, I receive this error:

[FATAL] when parsing login response sent from okta Your application is potential
ly vulnerable because no validation function found. Please read the documentatio
n on how to setup the validator. (https://github.com/tngan/samlify#installation)

**Comment by tngan** [comment]
@Inderjit1 Now Okta does send you back the response. We have introduced dynamic schema validator since 2.5, you have to set it according to the documentation.

```typescript
import * as samlify from 'samlify';
import * as validator from '@authenio/samlify-validate-with-xmllint';

samlify.setSchemaValidator(validator);
```

**Comment by tngan** [comment]
@Inderjit1 Any updates on that?

**Comment by tngan** [comment]
@Inderjit1 I will close this ticket first. Feel free to reopen the ticket later on when you have further questions.
