### ISSUE TITLE
Support http://www.w3.org/2009/xmlenc11#aes128-gcm for data encryption algorithms

### ISSUE THREAD

**Issue by wanyunli** [tngan/samlify#390]
Hi, 

could we also support http://www.w3.org/2009/xmlenc11#aes128-gcm for data encryption algorithms?  As I checked this algorithms is in the https://github.com/auth0/node-xml-encryption support list. 

Br,
Yunli

**Comment by tngan** [comment]
@wanyunli Yes, PR is welcome.

**Comment by wanyunli** [comment]
Hi, PR is created.

**Comment by tngan** [comment]
@wanyunli Thank you so much, it's merged and will be included in the next release.
