### ISSUE TITLE
High severity vulnerability in xml-crypto dependency

### ISSUE THREAD

**Issue by ndesimone** [tngan/samlify#396]
According to Github, the dependency 'xml-crypto' has the [GHSA-c27r-x354-4m68](https://github.com/advisories/GHSA-c27r-x354-4m68) vulnerability.  It looks like this has been addressed in 2.0.0.  

Any chance this will get updated soon?

<img width="924" alt="2020-10-28_09-03-11" src="https://user-images.githubusercontent.com/1914205/97463289-d340da00-18fc-11eb-98cb-a688dda92364.png">

**Comment by tngan** [comment]
@ndesimone Updated and 2.7.6 was released.
