### ISSUE TITLE
SP triggered Single Logout

### ISSUE THREAD

**Issue by sebakerckhof** [tngan/samlify#40]
Are there plans to add SP triggered single logout?

**Comment by tngan** [comment]
@sebakerckhof Yes, however it won't be seen in v1.x.x since alpha version of v2.0.0 is released just few minutes ago, and it would be included in the future plan.

**Comment by sebakerckhof** [comment]
Okay, I'm currently in the process of selecting a SAML library to integrate in my app. This seems to be the only one that's written decently and actively maintained, so thanks for this.
Would you suggest I try to integrate 1.x.x first or go directly fro 2.0.0 (read: how 'alpha' is the 2.0.0 alpha)? Would it be a lot of work to switch later on or is it mostly backwards compatible?

**Comment by tngan** [comment]
It's not backward compatible since some APIs will be changed in the future. However, it still takes some time until release, that's why you can try out 1.x.x first.

**Comment by tngan** [comment]
This library could allow to do that, but it doesn't include in the current example set, the plan is to include it in the example after v2 is released.

**Comment by tngan** [comment]
This issue will move to the example repository later on.
