### ISSUE TITLE
Documentation bug? nameID field casing

### ISSUE THREAD

**Issue by mixedCase** [tngan/samlify#402]
I see the docs in https://samlify.js.org/#/saml-response refer to a `nameid` field in the assertion's extract object, but `src/extractor.ts` points to the field being called `nameID` and indeed after trying it out with samltest.id I get that the field is called `nameID`.

Is this just a typo in the documentation or is the casing IdP-specific and I'm just missing something?

**Comment by tngan** [comment]
@mixedCase It's just a typo, thanks for reporting.
