### ISSUE TITLE
Make it work with Auth0

### ISSUE THREAD

**Issue by nearbody** [tngan/samlify#408]
Hi,
I need help with making it work with Auth0, I saw this project [https://github.com/authenio/react-samlify](react-samlify) that work with Okta, but, I need to make it work with Auth0 also. Any help will be appreciated.
Thanks.

**Comment by nflaig** [comment]
Hi @nearbody,
this library works with every identity provider which supports SAML 2.0. I used the library in combination with the following identity providers:  AzureAD, SapCloud, Okta, Auth0, Keycloak
There might be minor differences between IdPs but generally if they follow the SAML 2.0 specification you should not face any issues.

**Comment by tngan** [comment]
@nearbody You can take a look on the unit test for the login/logout flow. It includes most of the common use cases for you to kickstart.

https://github.com/tngan/samlify/blob/master/test/flow.ts#L135
