### ISSUE TITLE
azure SAML auth

### ISSUE THREAD

**Issue by matth-c3** [tngan/samlify#409]
Hello, 

Does anyone setup SAMLIFY with Azure SAML auth ? 

Thanks

**Comment by nflaig** [comment]
Hi @matth-c3,

do you mean SAML based single sign-on with Azure AD?

**Comment by matth-c3** [comment]
Hello @nflaig , yes exactly.

**Comment by nflaig** [comment]
@matth-c3 we are using SAMLIFY with different identity providers and Azure AD is one of them. Did not face any issues so far

**Comment by matth-c3** [comment]
Hello @nflaig , 

Sorry I never got back to you, I actually did not try yet. 

I read somewhere that Azure SAML 2 limits the number of groups to 150 when returned by SAML, did you got this issue ?

Thanks

**Comment by nflaig** [comment]
@matth-c3 no we havent faced an issue yet using Azure SAML2, maybe did no reach the group limit
