### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by qr-ghassenrjab** [tngan/samlify#414]
I need to build a SAML IdP on Node.js and I found this library.

Here is the scenario that I am trying to build:

1. The IdP accepts SAML requests from an SP;
2. Then redirects the user to our login page (already developed in another project);
3. After login, the user will be redirected back to the IdP with confirmation of login;
4. And then the IdP sends a SAML response back to the SP.

My questions are:

1. Is this scenario well suited for SAML protocol? Or I need to change it?
2. Is it possible to this with samlify? Especially redirecting to the login project, as this is not documented in the website.

Thanks for you help!

**Comment by tngan** [comment]
Let's move the discussion to here. #447
