### ISSUE TITLE
Define key other than email to get NameID value from user 

### ISSUE THREAD

**Issue by Keithcat767** [tngan/samlify#417]
Hello! I was wondering if it was possible to define a key other than email for the default template NameID. In my use case we are using a user id and not the email. Happy to provide a PR if this is something you think would be useful.

Thanks!

**Comment by tngan** [comment]
@Keithcat767 Yes, you can define your own template and interpolate the field value during runtime using the callback function. Here is the example.

https://github.com/tngan/samlify/blob/56d1bb59361ee21338b9fd495ca479b8934ede0c/test/flow.ts#L34-L41

https://github.com/tngan/samlify/blob/56d1bb59361ee21338b9fd495ca479b8934ede0c/test/flow.ts#L518-L539

I know I am too lazy to reply issue. I hope this answer helps for those who experience the same question in the future.
