### ISSUE TITLE
ERR_MISSING_SIG_ALG error

### ISSUE THREAD

**Issue by lchenshui** [tngan/samlify#419]
I am getting a ERR_MISSING_SIG_ALG error but I don't know what to do to fix it. I figure there's probably a config error but can someone point me in the right direction?

**Comment by tngan** [comment]
It happens when you put configured `wantAuthnRequestsSigned` as true, but there is no `sigAlg` params in the redirect url.

**Comment by tngan** [comment]
Feel free to reopen if you still encounter issue.
