### ISSUE TITLE
Working example of custom IDP?

### ISSUE THREAD

**Issue by ChristopherJosephDeanSchaefer** [tngan/samlify#438]
Is there a working sample of an IDP using samlify that I can access. I'm having trouble figuring out how to implement a custom identity provider with the documentation available. For example I don't know how to tell the service provider what user they are or how to start an identity provider initiated SSO.

**Comment by tngan** [comment]
@ChristopherJosephDeanSchaefer You need to set up an endpoint on the idp service, and construct an idp and corresponding service provider in backend create an identity provider, and the handler performs `createLoginResponse` function.

This test case simulates the idp-initiated sso.
https://github.com/tngan/samlify/blob/49e25153dc2584461613ded9dfaf30f55e964ce4/test/flow.ts#L363-L375

**Comment by joshuablanco** [comment]
Thanks for your answer @tngan, so, I can just provide the response with thew "createLoginResponse"?, I was checking your https://samlify.js.org/#/?id=samlify, but I'm not sure if I can build a reliable IDP.
Please I'd be really thankful if you could provide extra documentation.
Thank you very much.

**Comment by OscarJVD** [comment]
Hi @tngan, How it's going! Thanks for the answer

I'd like to know if you have some extra docs. 

I've been checking this link: https://github.com/tngan/samlify/tree/f2b6a2f8c36dc0ff887d0442c48cd0f2c0a4a778/examples/idp

And it's not working, could you provide us a working IDP?, please, if you have it. Thank you very much.

**Comment by tngan** [comment]
@joshuablanco 

- You need to handle IdP authentication yourself, i.e. the password verification when user login to your idp. 
- Second, you need to setup an endpoint to accept SAML login request, if user is not logged in, redirect it to your IdP login page.
- After verifying the request using `parseLoginRequest`, use the essential payload returned from this function to do further checking on your side (i.e. role for authorization, company, etc)
- Send back response constructed by `createLoginResponse`

IdP is more about application oriented, this library only provides you simple function to parse request and generate standard response.

**Comment by tngan** [comment]
@OscarJVD This one is created with an older version of this library, since the API has breaking change after 2.x, so we don't maintain that example anymore.

**Comment by tngan** [comment]
Let's move the discussion to here. https://github.com/tngan/samlify/discussions/447
