### ISSUE TITLE
Update xmldom dependency

### ISSUE THREAD

**Issue by zbuc** [tngan/samlify#443]
Unfortunately there was a security vulnerability reported in xmldom, and they lost their ability to publish to the existing package name on npm.

The dependency will need to be changed to https://www.npmjs.com/package/@xmldom/xmldom to get the latest bug fixes.

**Comment by tngan** [comment]
Release @v2.8.0, thanks for your report. @zbuc

**Comment by ronnn** [comment]
@tngan I think you forgot to adapt the imports (`xmldom` -> `@xmldom/xmldom`). Using 2.8.0 fails with `MODULE_NOT_FOUND`. 

```bash
➜  ~/dev/projects/samlify git:(master) npm run test
[...]
Error: Cannot find module 'xmldom'
```

**Comment by tngan** [comment]
@ronnn Oh, right, just publish v2.8.1. Thanks for your report.
