### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by netmiller** [tngan/samlify#444]
I'm getting (occasionally) error/warning message : 

```
08:10:08: (node:187192) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 21 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:390:17)
    at process.addListener (events.js:406:10)
    at Object.xmllint.validateXML (/opt/iris3/server/node_modules/node-xmllint/xmllint.js:12:2315)
    at /opt/iris3/server/node_modules/@authenio/samlify-node-xmllint/index.ts:15:34
    at new Promise (<anonymous>)
    at exports.validate (/opt/iris3/server/node_modules/@authenio/samlify-node-xmllint/index.ts:14:10)
    at Object.<anonymous> (/opt/iris3/server/node_modules/samlify/src/libsaml.ts:636:22)
    at step (/opt/iris3/server/node_modules/samlify/build/src/libsaml.js:38:23)
    at Object.next (/opt/iris3/server/node_modules/samlify/build/src/libsaml.js:19:53)
    at /opt/iris3/server/node_modules/samlify/build/src/libsaml.js:13:71
```

This is Express-backend serving React client, I think quite normal anyway.
Samlify is updated (yesterday) to `samlify@2.7.7` .
Node app is using typescript, and transpiled with `tsc`. 
Some days ago I tried to increase maxListeners adding : `process.setMaxListeners(20)`  to main.ts. I think default is 10. But this does not help except error message is complaining : 21 uncaughtException....

Any idea what is this and is there anything to change in application.

**Comment by tngan** [comment]
Hi @netmiller, thanks for your report. Let me check the lint library.

**Comment by tngan** [comment]
@netmiller There is one ticket in the repo of lint library. Let's continue the discussion in the following ticket.

https://github.com/authenio/samlify-node-xmllint/issues/4

**Comment by netmiller** [comment]
This memory leak has fixed now by removing schema-validator `@authenio/samlify-validate-with-xmllint`.
Now skipping validation totally :

```
samlify.setSchemaValidator({
    validate: (response: string) => {
        return Promise.resolve('skipped');
    }
});
```

and app seems to behave much better. 
This validator (samlify-validate-with-xmllint) has serious bug, and should avoid, imho.
