### ISSUE TITLE
"TypeError: nrsa is not a constructor" when updating to 2.8.1

### ISSUE THREAD

**Issue by oniemela** [tngan/samlify#449]
We have been using version 2.7.7 for a while, and when we tried to update to using 2.8.1 (same for 2.8.0), we faced a weird issue with getting redirect url.

Call:
serviceProvider.createLoginRequest(identityProvider, 'redirect', (logoutRequestTemplate) => { ...  })

Failure exception:
Exception: TypeError: nrsa is not a constructor
Stack: TypeError: nrsa is not a constructor
    at Object.constructMessageSignature (C:\....\node_modules\samlify\build\src\libsaml.js:457:32)
    at buildRedirectURL (C:\....\node_modules\samlify\build\src\binding-redirect.js:80:135)
    at Object.loginRequestRedirectURL (C:\....\node_modules\samlify\build\src\binding-redirect.js:119:22)
    at ServiceProvider.createLoginRequest (C:\....\node_modules\samlify\build\src\entity-sp.js:88:51)

Line where it fails:
https://github.com/tngan/samlify/blob/68181d872cfb16cd8d7b3247066effd6ca18a564/src/libsaml.ts#L543

We use @authenio/samlify-xsd-schema-validator and Azure functions typescript implementation (typescript version 4.0.3)

Same call works fine when calling with the 2.7.7, but we would need to upgrade  to get the xmldom security update. Is there any changes between the version that would give a hint as to what could cause the function to fail?

**Comment by tngan** [comment]
@oniemela Let me check if dependencies upgrade causes this issue.

**Comment by arthurrump** [comment]
Looks like this is similar #448, so it may be caused by the `"esModuleInterop": true` configuration change in tsconfig.json, as noted [in that issue](https://github.com/tngan/samlify/issues/448#issuecomment-917457911).

**Comment by tngan** [comment]
@arthurrump @oniemela Please try the latest patch release v2.8.2 for the fixes. Sorry for causing the upgrade issue.
