### ISSUE TITLE
No attributes when Parse Login Response

### ISSUE THREAD

**Issue by joshuablanco** [tngan/samlify#456]
Hello!.

I made an IDP with this library based on SP init.
When I send back the SAML Response to the SP and use the  `await req.sp.parseLoginResponse(req.idp, 'post', request);`

I always get this. 
![image](https://user-images.githubusercontent.com/20365187/141885943-d76c215c-23d9-4780-859f-5ec4e54fca2b.png)

My IDP is sending the context back just like this.
![image](https://user-images.githubusercontent.com/20365187/141886030-eb28cff6-0e18-452f-88da-a43d2c503464.png)

then I return only the context from the createLoginResponse result.
the IDP metadata is almost the same as provided by a previous tutorial by @tngan 
![image](https://user-images.githubusercontent.com/20365187/141886186-7e2e1784-2d5e-4818-8b05-53c9812c215f.png)

and the metadata that I'm using is the next one
![image](https://user-images.githubusercontent.com/20365187/141886224-b54523ed-d037-4f24-a7f3-527b9bece1ed.png)

probably I'm making an obvious mistake, but I really appreciate your help.

**Comment by tngan** [comment]
@joshuablanco What is your third argument when calling `parseLoginResponse`?

Code example

https://github.com/tngan/samlify/blob/9a56afda0d3baf0d2f0eac6ae60d88ba3cbc77c9/test/flow.ts#L364-L375

**Comment by joshuablanco** [comment]
Mr @tngan Thank
