### ISSUE TITLE
OKTA example SP binding setting error

### ISSUE THREAD

**Issue by TrendAlan** [tngan/samlify#457]
Hi Bro, it took me a long time to locate this issue, the binding setting for SP in the [OKTA example](https://samlify.js.org/#/okta) should be
`saml.Constants.namespace.binding.post`
instead of 
`saml.Constants.namespace.post`
If not, the assertionConsumerServiceURL will be `undefined `in the SAML AuthnRequest

**Comment by tngan** [comment]
@TrendAlan My bad, I will correct the OKTA example. Thanks for reporting.
