### ISSUE TITLE
IDP expired x509 certificate validation

### ISSUE THREAD

**Issue by fatton139** [tngan/samlify#464]
Hi,

I have a testing IDP whose x509 certificate has expired, I would've expected some validation error to be thrown but everything seems to still be fine.

Is it intended that the devs themselves to implement this and validate the certificate?

I've tried toggling `authnRequestsSigned` and `wantAssertionsSigned` but seems to have no effect.

Thanks for all your work.

**Comment by tngan** [comment]
@fatton139 Yes, it's up to devs to implement the certificate validation for now.
