### ISSUE TITLE
[Bug] LogoutRequest POST binding using wrong location

### ISSUE THREAD

**Issue by carsonwah** [tngan/samlify#469]
When doing `sp.createLogoutRequest()` with POST binding, the IDP location is retrieved by Redirect binding. If Redirect binding is not defined in IDP metadata/config, it results in a LogoutRequest like `<samlp:LogoutRequest Destination="[object Object]" ...`.

createLogoutRequest():
https://github.com/tngan/samlify/blob/49e25153dc2584461613ded9dfaf30f55e964ce4/src/entity.ts#L160-L162

base64LogoutRequest():
https://github.com/tngan/samlify/blob/49e25153dc2584461613ded9dfaf30f55e964ce4/src/binding-post.ts#L231

As a temporarily workaround, I added the same location as Redirect binding.
```
singleLogoutService: [{
    Binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
    Location: '<IDP Location>',
  },{
    Binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
    Location: '<IDP Location>',
  }]
```

**Comment by joshuablanco** [comment]
I was getting the same problem.

**Comment by tngan** [comment]
It should be already fixed and patched. 

https://github.com/tngan/samlify/blob/9ed5af54e1d44efdad639869048359edeb7944a9/src/binding-post.ts#L231
