### ISSUE TITLE
Invalid Digest in SamlResponse - basic configuration

### ISSUE THREAD

**Issue by nathandeburn-ws** [tngan/samlify#478]
Created IdP using Samlify (It rocks, thank you, BTW).  The token verifies correctly on samltool.com and works with a test samlify sp, but when hooking it up to okta, the signature validation fails.  After banging my head on for a while, I tried other saml token verifiers.  samltool.io and others report an invalid digest.  The exact error from samltool.io is:

XMLJS0013: Cryptographic error: Invalid digest for uri '#_647977ff-e6ee-42af-8ac5-a2e46c41d53e'. Calculated digest is GXKRELGDFv8lyeq2/siPY8aLewLBci9NPceM1FHyC9k= but the xml to validate supplies digest BR4ua9mQc6HBPD435jaCr6dP+Ce9VPCzNAohTYb4qRs=

I then built a very basic IdP just for generating the token data for testing.  It dumps the token directly to browser to be checked on samltool.io.  The token generated gives the same digest error.  I can supply the code to this simple project if needed for full testing.  Here is the code generating the token.

`// This is /routes/sso.js
const express = require("express");
const router = express.Router();

const saml = require("samlify");
//const validator = require("@authenio/samlify-node-xmllint");
const validator = require("@authenio/samlify-xsd-schema-validator");
saml.setSchemaValidator(validator);

const bodyParser = require("body-parser");
const urlencodedParser = bodyParser.urlencoded({ extended: false });
router.use(urlencodedParser);

const fs = require("fs");

const sp = saml.ServiceProvider({
  metadata: fs.readFileSync("./metadata/metadata_sp_localhost.xml"),
  privateKey: fs.readFileSync("./certs/spSignKey.pem"),
});

const idp = saml.IdentityProvider({
  //metadata: fs.readFileSync('./metadata/metadata_localhost.xml')
  //metadata: fs.readFileSync("./metadata/metadata_localhost.xml"),
  assertionConsumerService: "http://localhost:2000/sso/acs",
  entityID: "http://localhost:2001/sso/metadata",
  isAssertionEncrypted: false,
  wantAuthnRequestsSigned: false,
  signingCert: fs.readFileSync("./certs/idpSignCert.cer"),
  privateKey: fs.readFileSync("./certs/idpSignKey.pem"),
  encryptCert: fs.readFileSync("./certs/idpEncryptCert.cer"),
  encPrivateKey: fs.readFileSync("./certs/idpEncryptKey.pem"),
  nameIDFormat: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
  singleSignOnService: [
    {
      Binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
      Location: "http://localhost:2001/sso/authn",
    },
  ],
  //signatureConfig: {
  //  prefix: "ds",
  //  location: {
  //    reference: "/samlp:Response/saml:Issuer",
  //    action: "after",
  //  },
  //},
  clockDrifts: [-5000, 3000],
});

router.get("/metadata", (req, res) => {
  res.header("Content-Type", "text/xml").send(idp.getMetadata());
});

router.get("/idp-init", async (req, res) => {
  const user = { email: "user@email.com" };
  const minRequest = { extract: { request: { id: "idp_initiated" } } };
  let tokenData = {};
  try {
    tokenData = await idp.createLoginResponse(sp, minRequest, "post", user);
  } catch (e) {
    console.log("error: ", e);
  }
  res.header("Content-Type", "application/json").send(tokenData);
});

module.exports = router;`

Am I missing something or have something incorrect?  Seems to be an incorrect digest in both our implementation and this simple token generator.

**Comment by nathandeburn-ws** [comment]
transform: http://www.w3.org/2000/09/xmldsig#enveloped-signature is missing from the algorithms.  It appears to be an issue in constructSAMLSignature - opts.transformationAlgorithms vs var transformationAlgorithms.  If I set the opts.transformationAlgorithms after it is set to var transformationAlgorithms, the correct transforms are put in the token.  And the token signature validates correctly.

**Comment by nathandeburn-ws** [comment]
The issue can be overridden by adding:
`transformationAlgorithms: [
      'http://www.w3.org/2000/09/xmldsig#enveloped-signature',
      'http://www.w3.org/2001/10/xml-exc-c14n#',
    ],`

to the SP constructor.

**Comment by tngan** [comment]
@nathandeburn-ws Thanks for your question here.

```ts
[
  'http://www.w3.org/2000/09/xmldsig#enveloped-signature',
  'http://www.w3.org/2001/10/xml-exc-c14n#',
]
```

Yes, the above is the default transformation algorithm if you don't pass in the one in construction properties of SP.
