### ISSUE TITLE
InResponseTo is not handled correctly in IDP initiated SLO flow

### ISSUE THREAD

**Issue by sinbino** [tngan/samlify#479]
The following code uses samlify to handle Logout Requests from IDPs.
```typescript
const requestInfo = await sp.parseLogoutRequest( idp, 'redirect', { query } )
const { context } = sp.createLogoutResponse( idp, requestInfo, 'redirect', relayState )
redirectTo( context )
```
The InResponseTo attribute of the SAMLResponse in the redirect URL is "{InResponseTo}".

This seems to be caused by around line 305 of binding-redirect.ts, which is called from createLogoutResponse.
```typescript
// binding-redirect.ts: line 304-
if (requestInfo && requestInfo.extract && requestInfo.extract.logoutRequest) {
  tvalue.InResponseTo = requestInfo.extract.logoutRequest.id;
}
```
The location of the ID returned by parseLogoutRequest is contained in requestInfo.extract.request.id.
This mismatch appears to be causing createLogoutResponse to incorrectly set the InResponseTo attribute.

Am I using this wrong? Or is it a samlify issue?

**Comment by tngan** [comment]
@sinbino Oh, you are right, it should be `extract.request.id`.

**Comment by tngan** [comment]
It will be patched in the upcoming release.
