### ISSUE TITLE
SP-initiated Single Log-out 

### ISSUE THREAD

**Issue by Satyavemana** [tngan/samlify#484]
As per document, SP-initiated Single Log-out in development. When this feature will be added in samlify lib ? any roadmap?.
is there any alternative approach to implement SP initiated logout using samlify lib?.

**Comment by tngan** [comment]
You can create the logout request as follow.

https://github.com/tngan/samlify/blob/56d1bb59361ee21338b9fd495ca479b8934ede0c/test/flow.ts#L325-L339

**Comment by Satyavemana** [comment]
> You can create the logout request as follow.
> 
> https://github.com/tngan/samlify/blob/56d1bb59361ee21338b9fd495ca479b8934ede0c/test/flow.ts#L325-L339

Thanks for response. will try

**Comment by Satyavemana** [comment]
The sp initiate logout we found it in samlify
