### ISSUE TITLE
vulnerable dependency @xmldom/xmldom:0.8.3

### ISSUE THREAD

**Issue by dan-diaz** [tngan/samlify#493]
Unfortunately,@xmldom/xmldom:0.8.3 has now been flagged as a vulnerable version.

Thanks for your timely response on this issue last time.
https://github.com/tngan/samlify/issues/492

Looks like @xmldom/xmldom:0.8.5 is currently safe

**Comment by tngan** [comment]
@dan-diaz 0.8.6 is updated now, release v2.8.7 is published.
