### ISSUE TITLE
Rebrand and next step of express-saml2

### ISSUE THREAD

**Issue by tngan** [tngan/samlify#76]
Next big plan would be to remove the bundle with express.js, because this library should not be limited by a single framework.

**Some thoughts**

- Rename but will keep the version history
- The current example folder will be separated into new repositories, it's more easier to let user get started instead of cloning the whole library
- An open-source and standalone identity provider to provide self-hosted federation services driven by this library
- Easy integration for applications

Feel free to discuss here.

**Comment by sebakerckhof** [comment]
Sounds good

**Comment by tngan** [comment]
Yes, it's definitely not bounded to express.js, so no need to name it as a prefix and we can remove the ambiguity. 

**Name suggestion (keep updating)**
- saml2pass
- samlify
- js-saml2

**Comment by tngan** [comment]
Examples will be moved into a new organization later on.

https://github.com/Passify

**Comment by tngan** [comment]
@sebakerckhof How about we rename it as **samlify** before the release ? 

- [ ] github repo rename
- [ ] package.json (pre-release as `2.0.0-rc.1` before the real release next week)

**Comment by sebakerckhof** [comment]
Yeah, I agree we should do the rename before the release. 
Although before the final release I think we should really have some more tests. The coverage of the entity and binding files is really low seeing how much of the functionality is in there.

**Comment by vbakke** [comment]
I quite liked the name express-saml2.  But since this library has no connection with express.js, it shouldn't have a connection via the name either. I support a name change. :)

I haven't had time to test v2 yet, but I'm planning to work more on my SAML2 project tomorrow.  I can upgrade then, and give feedback if I find anything. 

Vegard :)

**Comment by sebakerckhof** [comment]
Btw, what about registering an npm scope? So we can do @passify/samlify or something like that.

**Comment by tngan** [comment]
I have already make the first rc release in npm. `npm install samlify@2.0.0-rc.1`
