### ISSUE TITLE
API proposal for v3

### ISSUE THREAD

**Issue by sebakerckhof** [tngan/samlify#82]
This is more of a general ideas thread for a possible v3.

I came across https://github.com/socialtables/saml-protocol and while it doesn't look like a very well maintained/supported library, I really like the API.

More specifically how you give a 'model' to the 'sp'/'idp' with functions like:
```
getIdentityProvider(entityID): resolves an IDP's config object by Entity ID
storeRequestID(requestID, idpConfig): stores a request ID for later verification
verifyInResponseTo(requestID, idpConfig): verifies that a request with requestID was sent by the SP, rejecting on failure
invalidateRequestID(requestID, idpConfig): invalidates a request ID after a response has been processed to prevent duplicate assertion playback attacks
```

That allows them to do a bunch of useful stuff.

**Comment by sebakerckhof** [comment]
Btw, to give some more background on why I think this is a nice api:

1) The  `getIdentityProvider` function of the model allows for some nice things:
It allows you to just pass the request variables are body params to the assert functions. The library can then extract the 'entityId' (e.g. from 'Issuer' in the XML) and find the IDP settings. Thus your SP can have all the IDPs use the same endpoints and you only need 1 SP definition.

This is as opposed to this library where the user has to pass the identity provider. However, for an SP that supports multiple IDPs you would need multiple end points (routes) per IDP in order to know which IDP to pass in. This means that you need metadata per IDP and therefore you're gonna have to create an SP for every IDP. 

2) The models Request/Response ID functions enforces good security practices while maintaining flexibility. 
Good security practices because it allows the library to verify request ids belong to the correct idp & the library will invalidate the processed request ids to prevent replay attacks. So the user of the library doesn't have to think about it. However, at the same time the user stays in charge on how to store IDP and request data.

**Comment by tngan** [comment]
Yes, I agree that enforcing association and flexibility could be the next step. Let me draft the proposal during summer, and probably we can release v3 by the end of this year, and keep discussing here.

**Comment by tngan** [comment]
Discussion thread is now moved to #90.
