### ISSUE TITLE
parseResult.extract.issuer duplicated

### ISSUE THREAD

**Issue by haoleman** [tngan/samlify#86]
https://github.com/tngan/samlify/blob/master/src/entity.ts#L253 gets thrown because issuer is twice with comma in parseResult.extract Here is results of "console.log(`=====\n here is pR issuer:\n ${parseResult.extract.issuer}`);":

"here is pR issuer: http://blah/asdf
,
http://blah/asdf"

**Comment by tngan** [comment]
@haoleman I think `parseResult.extract.issuer` could be an array of string in this case. Can you just print out the `console.log(parseResult.extract.issuer);` instead of doing string interpolation ? I wonder if there is some special character like \r\n.

**Comment by haoleman** [comment]
=====
here is pR issuer:
http://www.okta.com/dummyIssuer,http://www.okta.com/dummyIssuer
====

^ I sent another request from okta and replaced values for posting here. Don't think it's special characters. Here's the SamlResponse:

[saml_response_dupes_issuer.xml.txt](https://github.com/tngan/samlify/files/1096564/saml_response_dupes_issuer.xml.txt)

**Comment by haoleman** [comment]
by here https://github.com/tngan/samlify/blob/master/src/entity.ts#L241  the fields.issuer is already a comma separated "multi-value" (same with nameidformat and others), which makes sense since there are multiple in samlresponse. However, I can't imagine where these two would ever be different values (if they are throw an error or something), so it's kinda like for extractor.issuer split it by "," and set it to [0] before https://github.com/tngan/samlify/blob/master/src/libsaml.ts#L529

**Comment by tngan** [comment]
@haoleman I used `libsaml.extract` to test the input document, some trailing spaces are not trimmed and line break exists. If `parseResult.extract.issuer` is an array, when you parse it as string, it would be comma separated, but the libsaml.extract function is supposed to return an array if multiple instances exist.

I have made a patch and test for this issue.

**Comment by haoleman** [comment]
awesome. figured u'd dig in and find the "real" solution. thx a lot. great library.

**Comment by tngan** [comment]
Thank you for making this library better.
