### ISSUE TITLE
enforce signed SamlResponse for IDP-Initiated

### ISSUE THREAD

**Issue by haoleman** [tngan/samlify#87]
Right now, I am able to send a SamlResponse w/o a signature and it gets through. Handy during dev, but show stopper for me in production.

I noticed here https://github.com/tngan/samlify/blob/master/src/entity-sp.ts#L97 , we are setting "verifySignature"  (prolly need to fix the mispelling) to true AND we set to true to get into here
https://github.com/tngan/samlify/blob/master/src/entity.ts#L243 to verify signature.  Since, we're defaulting to true to "verifySignature", prolly need a check for "selection" here https://github.com/tngan/samlify/blob/master/src/libsaml.ts#L451  to make sure there is a signature in samlresponse. Could add a configuration setting, but default to "must have signature",  to make sure nobody mucked with assertion.

PSEUDO
`if (config.must_have_signature && (!selection || selection.length < 1)) {
    throw new Error('No signature found');
}`

**Comment by tngan** [comment]
@haoleman In v1, response signature is optional, but now we guarantee response must have a signature starting from v2 (message signature or assertion signature, or both). Add a checking in that function is useful and makes sense, will include it in the next patch.
