### ISSUE TITLE
cannot validate signature with signed response and encrypted assertion (not signed though)

### ISSUE THREAD

**Issue by haoleman** [tngan/samlify#89]
Using both OneLogin and Okta, I am not able to validate the signature when using a signed response with encrypted assertion. The assertion decrypts (I suspect something in here... like a space) and the encrypted data is replaced with the decrypted assertion, but the signature validation fails here:
https://github.com/tngan/samlify/blob/master/src/entity.ts#L249.  If I send a signed response with unencrypted and unsigned assertion, it works fine from both OneLogin and Okta...so I suspect something in xml-encryption.decrypt, but this renders me unable to use samlify (as I must support signed response with encrypted assertion).

**Comment by tngan** [comment]
Let me know how you construct your service provider, or create a sample repository so that we can make sure the initial is correct first.

**Comment by haoleman** [comment]
`sp = ServiceProvider({
				encPrivateKey: fs.readFileSync(path.resolve(path.dirname(require.main.filename), [path_to_key)),
				metadata: fs.readFileSync(path.resolve(path.dirname(require.main.filename), spFile))
			})`

That what u need?

**Comment by tngan** [comment]
How do you define the identity provider (okta/onelogin) in order to use parseLoginResponse ? In the test suite, I didn't include the signed response with encrypted assertion (without signature). I will try to add it later on.

You can try out a simple flow, saying signed assertion first and make sure the key setting is correct. [Here](https://github.com/tngan/samlify/blob/master/test/flow.ts#L247)

**Comment by haoleman** [comment]
For both okta/onelogin, I upload my cert for them to use for encryption of assertion. They use their cert to sign samlresponse.

**Comment by tngan** [comment]
@haoleman You can checkout the test case that newly added. I also want to know what signature algorithm they use, maybe there is mismatch. Another possibility is the order of signature and encryption, samlify's idp strictly follows sign-then-encrypt approach and sp follows decrypt-then-verify.

**Comment by haoleman** [comment]
I thought about the order too, afaict okta and onelogin using sign-then-encrypt too. here's signature from both...SHA1. I check and xml-crypto is using SHA1 to hash.

`onelogin

<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
            <ds:Reference URI="#pfx9b071616-8b51-4364-7634-1e6a35b038fb">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                <ds:DigestValue>a7+C/QuV4Fg6rIIen6uGugflt38=</ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>asdfasdfasdf</ds:SignatureValue>
        <ds:KeyInfo>
            <ds:X509Data>
                <ds:X509Certificate>asdfasdfasdf</ds:X509Certificate>
            </ds:X509Data>
        </ds:KeyInfo>
    </ds:Signature>

okta


<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
            <ds:Reference URI="#pfx9b071616-8b51-4364-7634-1e6a35b038fb">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                <ds:DigestValue>a7+C/QuV4Fg6rIIen6uGugflt38=</ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>asdfsadf</ds:SignatureValue>
        <ds:KeyInfo>
            <ds:X509Data>
                <ds:X509Certificate>asdfsadfsadf</ds:X509Certificate>
            </ds:X509Data>
        </ds:KeyInfo>
    </ds:Signature>`

**Comment by haoleman** [comment]
Also, this might be a helpful enhancement for future issues with signatures. I added this libsaml.ts (verifySignature):
`let valid = sig.checkSignature(xml);
          if (!valid) {
            console.log(`Errors checking signature:\n${sig.validationErrors}`);
          }
          res = res && valid;`

**Comment by haoleman** [comment]
figured out the "problem"...the IDP is encrypting-then-signing. I added a config option to samlify "messageSigningOrder" (just for quick verification) to entity config to allow some logic to verify signature before/after decrypting and it worx. I'll put together an MR, unless you're already working on something like this. Quick look into code, "hardes" thing will be tweaking testing framework. Changes to entity and urn are minimal.

**Comment by tngan** [comment]
@haoleman Interesting, this is [another discussion](https://crypto.stackexchange.com/questions/5458/should-we-sign-then-encrypt-or-encrypt-then-sign) thread for the order. A config option is good for it, it also affects the order of decryption and verification in service provider side.

If idp encrypts then signs, sp should verify then decrypt, and eventually verify the assertion signature if there is one.

If idp signs and encrypts, sp should decrypt, then verify signature(s). 

Pull request is welcome :)

**Comment by tngan** [comment]
Both Onelogin and Okta are doing encrypt-then-sign ?

**Comment by haoleman** [comment]
okta for sure. i'll have to check onelogin, again. my trial period expired.
