### ISSUE TITLE
TypeError: Cannot read property 'find' of undefined at IdpMetadata.getSingleSignOnService

### ISSUE THREAD

**Issue by mdeltito** [tngan/samlify#91]
This occurs when an IdP does not specify a `SingleLogoutService`, which afaik is not required (Salesforce IdP, for example, omits this). I believe this could be a typo on the following line:

https://github.com/tngan/samlify/blob/master/src/metadata-idp.ts#L140

Shouldn't `singlelogoutservice` be `singlesignonservice` here, or am I missing something? If I make this change in the src I no longer get the error.

**Comment by tngan** [comment]
@mdeltito Nice catch, fix will be included in the patch.
