### ISSUE TITLE
Getting "This is not private key" error

### ISSUE THREAD

**Issue by puneetmakkar** [tngan/samlify#92]
var fs = require('fs');
var saml = require('samlify');

var settings = {
    privateKeyFile: fs.readFileSync(__dirname + '/config/ll_nsl-dev-key.pem'),
    metadata: fs.readFileSync(__dirname + '/config/nsl_sp_metadata.xml')
};

var sp = saml.ServiceProvider(settings);
var idp = saml.IdentityProvider({
  metadata: fs.readFileSync(__dirname + '/config/nsl_idp_metadata.xml')
});

var redirecturl = sp.createLoginRequest(idp, 'redirect');
/* I get Error: This is not private key
    at Error (native)
    at NodeRSA.module.exports.NodeRSA.sign (/Users/puneet.makkar/memberportal/node_modules/node-rsa/src/NodeRSA.js:317:19)*/

**I have tested the private key seprartely with node_rsa module and key looks fine to me.** 
var key = new NodeRSA(fs.readFileSync(__dirname + '/config/ll_nsl-dev-key.pem'));
var text = 'Hello RSA!';
var encrypted = key.encrypt(text, 'base64');
console.log('encrypted: ', encrypted);
var decrypted = key.decrypt(encrypted, 'utf8');
console.log('decrypted: ', decrypted); //Hello RSA!

@tngan Can you suggest me where I mite be going wrong ?

**Comment by puneetmakkar** [comment]
Figured out the issue.
In the settings, it should be 

**privateKey**: fs.readFileSync(__dirname + '/config/ll_nsl-dev-key.pem'),

**Comment by tngan** [comment]
@puneetmakkar The documentation seems not updated, I will update it in the next patch. :)
