### ISSUE TITLE
Question --> when 2.0.2 Release available?

### ISSUE THREAD

**Issue by haoleman** [tngan/samlify#95]
Happy 4th. Just wondering when release for 2.0.2 will be available via NPM.  Thanks.

**Comment by tngan** [comment]
v2.0.2 should be released (just fix the test build), I will bump v2.0.3 tonight as well.

**Comment by tngan** [comment]
New version is already bumped. https://github.com/tngan/samlify/releases/tag/v2.0.3

**Comment by haoleman** [comment]
2.0.3 did the trick. I'm able to handle saml2 prefixes and encrypt-then-sign. THX.

**Comment by tngan** [comment]
@haoleman Thanks for your pull request as well.
