### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by tngan** [tngan/samlify#97]

**Comment by killalau** [comment]
@tngan any details for this enhancement? I can help.

**Comment by tngan** [comment]
@killalau Target of first pass is to minimise the number of `any` and submit it to DefinitelyTyped.

Some basic functions must be included.

- [ ] constructor of metadata, entities (idp & sp)
- [ ] createLoginResponse
- [ ] createLoginRequest
- [ ] parseLoginRequest
- [ ] parseLoginResponse

**Comment by Seikho** [comment]
You don't need to submit to definitelytyped if you export the types from your package.

See: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by tngan** [comment]
First pass is done. Thanks @Seikho
